### ISSUE TITLE
Name giving in Node-Red for Domoticz flow not consistent, resulting in errors

### ISSUE THREAD

**Issue by knielen** [heishamon/HeishaMon#122]
After an update to 0.5 most names of topics are wrong in node-red for Domoticz, resulting in not being recognized and ignored.
For example:

Quite mode TOP18: 
Name in Heisha: Quite_Mode_Level
Name in Node-Red: Quitemode_Level

**Comment by MiG-41** [comment]
Yes, that was decided ,to recheck all names. Sorry for that.

**Comment by Dylantje** [comment]
I have the correct node Red Names almost working

**Comment by Egyras** [comment]
> I have the correct node Red Names almost working

@Dylantje make a pull request for fix

**Comment by Dylantje** [comment]
In my github a Alfa version, i do not have the time @ the moment, to make all working... 
https://github.com/Dylantje/Heisha-mon-Global-setup/blob/master/Globalsetup

**Comment by knielen** [comment]
I have a new list, which should be correct. I did a pull request, but this is my first attempt so please do a double check.
