### ISSUE TITLE
no measurement values in grafana

### ISSUE THREAD

**Issue by robvos** [heishamon/HeishaMon#131]
I have a setup with Domoticz, node red and influx/grafana
In Domoticz I get the right values.
In grafana I can select the sensors like flow, temperatures and a lot more.
But when I select one, I do not get any measurement values.

Do you know what I can do about it?

**Comment by Egyras** [comment]
@robvos  please show any screenshot, also go in InfluxDB admin in Grafana and show measurement values.

**Comment by robvos** [comment]
Sorry. It is already solved.
In grafana, I had to select the field numvalue instead of the strvalue.
I was not aware of this. 
Thank you for the good work.

**Comment by Egyras** [comment]
Closing then.
