### ISSUE TITLE
heishamon.yaml - #### SENSORS BELOW ARE NOT IN FIRMWARE ####, not working

### ISSUE THREAD

**Issue by bse4792** [heishamon/HeishaMon#158]
heishamon.yaml
sensors are giving unknown see picture
i have not changed anything in yaml file all others sensor/switches works perfectly
![image](https://user-images.githubusercontent.com/29598723/93016719-a2fae180-f5c3-11ea-84d0-3d6c4df2e194.png)

**Comment by trsqr** [comment]
You are using Home Assistant, right? I recently committed a change that should have fixed those. Did you pull the master recently or which version are you using (this would be helpful to mention in a bug report)?

**Comment by bse4792** [comment]
Hi. Yeah updated firmware and reset settings, pulled latest yaml file yesterday.

**Comment by trsqr** [comment]
Hi, currently on mobile, but try this:

Under   #Energy use/production look at places where it says sensor.heishamon_blahblah and replace those with sensor.heishamon_aquarea_blahblah. So basically just add the aquarea into the variable names for the power consumption and production.

Let me know if it works and I'll commit the fix tomorrow when back home.

**Comment by MiG-41** [comment]
@trsqr , could you in the same time change pattern of MQTT topics , from "heishamon_heat_pump/"  to "panasonic_heat_pump/" ?
"panasonic_heat_pump" is still standard one , with heishamon gives ,and since it is not changed till that time it will probably stay longer....

**Comment by bse4792** [comment]
@trsqr i could not get it to work last night, could not find correct sensor.bla_bla_bla.
also i agree with @MiG-41 on topics

**Comment by trsqr** [comment]
@bse4792 can you please test the yaml in: https://github.com/Egyras/HeishaMon/pull/159

**Comment by geduxas** [comment]
Also there was a problem, that COP is calculated before it get's energy values. Fixed that in future release.

https://github.com/Egyras/HeishaMon/commit/e0bf1e34d510de5b1e8166a065608f40e322c8de

For my HA with that YAML everything works fine now.

**Comment by trsqr** [comment]
@bse4792, please test and close this if ok.

**Comment by bse4792** [comment]
All fixed in 1.0
