### ISSUE TITLE
Model decode

### ISSUE THREAD

**Issue by geduxas** [heishamon/HeishaMon#189]
I starting to see some similarities in model numbers

| Value | IDU code       | ODU code       | IDU            | ODU        | KIT           | Power [kW] | 1ph/3ph | T-CAP/HP           |
|-------|----------------|----------------|----------------|------------|---------------|------------|-------- |--------------------|
|     2 | E2 CF 0D 77 09 | 12 D0 0B 05 11 | WH-SXC09H3E5   | WH-UX09HE5 | KIT-WXC09H3E5 |          9 |     1ph | T-CAP              |
|     4 | E2 CF 0D 85 05 | 12 D0 0C 94 05 | WH-SXC09H3E8   | WH-UX09HE8	| KIT-WXC09H9E8 |          9 |     3ph | T-CAP              |
|     5 | E2 CF 0D 86 05 | 12 D0 0C 95 05 | WH-SXC12H9E8   | WH-UX12HE8	| KIT-WXC12H9E8 |         12 |     3ph | T-CAP              |
|    13 | E2 CF 0C 74 09 | 12 D0 0D 95 05 | WH-ADC0916H9E8 | WH-UX12HE8	| KIT-AXC12HE8  |         12 |     3ph | T-CAP - All-In-One |
|     6 | E2 CF 0D 87 05 | 12 D0 0C 96 05 | WH-SXC16H9E8   | WH-UX16HE8 | KIT-WXC16H9E8 |         16 |     3ph | T-CAP              |

we have 2 devices with same ODU, `WH-UX12HE8`, for one code is `12 D0 0C 95 05` second one `12 D0 0D 95 05` almost identical. only `0C` and `0D` maybe it it would be some date code, or manufactured location.. mine is with `0D`, and date in sticker 2020.01

second we have different power values but same model. 9, 12 and 16 kW with t-cap and without
|Code| Model | Type|
|---|---|---|
|12 D0 0C 94 05 |WH-UX09HE8| T-Cap|
|12 D0 0C 91 05 | WH-UQ09HE8 | T-CAP - Super Quiet |
|12 D0 0B 97 05 | WH-UD09HE8| HP |
|12 D0 0C 95 05 |WH-UX12HE8| T-Cap|
|12 D0 0C 96 05 |WH-UX16HE8| T-Cap|

I think all that data is for internal and external data units, or maybe main boards for hydro module and indoor unit. 

May be it will help in decoding data.

**Comment by MiG-41** [comment]
For sure byte 131 with 0B means monoblock cover . Also it maches to Super Quiet unit , where ODU cover is monoblock.

EDIT: But also J-series All-In One have 0B.... So not really true....

**Comment by trsqr** [comment]
Yeah, I was last week trying to write this open bit-by-bit to find similarities. Separation between IDU and ODU codes is one possibilty indeed. I also have here one J-gen 5kW split unit that I'll get up and running soon - have already a HeishaMon ready for that too.

**Comment by MiG-41** [comment]
> `0C` and `0D` maybe it it would be some date code, or manufactured location.. mine is with `0D`, and date in sticker 2020.01

One of these WH-UX12HE8 is mine (12 D0 0C 95 05 ), and it is manufactured in 2018.07 , manufactured location ... Malaysia

**Comment by geduxas** [comment]
> manufactured location ... Malaysia

Yesterday we have discussed about H generation. And have found that latest H series have SMART DHW support, as J series. So I still think that it could be revision number, or software version :)

**Comment by IgorYbema** [comment]
New version of code just compares all 10 bytes to produce an ID.

**Comment by Joeknx** [comment]
My WH-MDC09J3E5 monoblock is not recognized.

Hexdump:

Heishamon stats: Uptime: 0 days 3 hours 42 minutes 24 seconds ## Free memory: 73% 26440 bytes ## Wifi: 80% ## Mqtt reconnects: 4 ## Correct data: 93.87%
Requesting new panasonic data
sent bytes: 111 including checksum value: 18 
data: 71 6C 01 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
data: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
data: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
data: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Received 203 bytes data
data: 71 C8 01 10 55 55 52 49 00 55 00 01 00 00 00 00 00 00 00 00 59 15 11 55 55 1D 55 55 55 19 00 00 
data: 00 00 00 00 00 00 80 80 80 80 B4 71 71 97 99 00 00 00 00 00 00 00 00 00 00 00 80 85 15 8A 85 85 
data: D0 7B 78 1F 7E 1F 1F 79 79 8D 8D B7 A3 7B 8F B7 A3 7B 8F 98 85 80 8F 8A 94 9E 8F 8A 94 9E 85 8F 
data: 8A 11 3D 78 C1 0B 7E 7C 1F 7C 7E 00 00 00 55 55 55 21 87 15 55 05 1C 12 65 00 00 00 00 00 00 00 
data: 00 C2 D3 0B 35 65 B2 D3 0B 96 65 8F 00 00 8F 8E 8F 32 32 A3 A3 32 32 32 80 A3 8F 8E 97 8F 8E 61 
data: 91 61 92 3B 01 01 01 00 00 22 00 01 01 01 01 79 79 01 01 01 00 00 01 00 00 01 00 00 01 00 00 0A 
data: 01 01 01 01 01 01 01 02 00 00 30 
Checksum and header received ok!

**Comment by IgorYbema** [comment]
Added and will be available in next beta release, see commit
https://github.com/IgorYbema/HeishaMon/commit/1b24c180175c578ec56444d70db9ae4e374e1779

**Comment by IgorYbema** [comment]
@Joeknx you can find a working new beta here https://github.com/IgorYbema/HeishaMon/blob/main/binaries/HeishaMon.ino.d1-v2.1-iy-4.bin

**Comment by geduxas** [comment]
interesting findings, just by accident found secret meniu:
![image](https://user-images.githubusercontent.com/18700450/142239277-c687d154-855e-40ff-93d1-cab7929fd148.png)

and by that there is interesting addresses: 

![image](https://user-images.githubusercontent.com/18700450/142239637-706460cf-cc29-4416-85a6-a9e1e942aff7.png)

this maps almost same values as we use as model numbers :) maybe there is more interesting stuff there ? 

E2 CF | 0C 74 09 | 12 D0 | 0D 95 05

but somehow 12 0D apperes as 0x0D11, and 0c 74 09 as 0x09740B also in address 93 i have 0xCFE1 (but in heisha e2 cf )

**Comment by trsqr** [comment]
Interesting.

My model string is:
62 D2 --- 0B 41 54 --- 32 D2 --- 0C 45 55

Address 93: 0xD2 61
Address 94: 0x54 41 0A
Address 95: 0xD2 31
Address 96: 0x55 45 0B

Byte order seems to be different in these fields (big-endian vs. little-endian). In addition, the last number in the Address 93-96 is smaller by one than in the model string.

**Comment by MiG-41** [comment]
My model:
E2 CF --- 0D 86 05 --- 12 D0 --- 0C 95 05

Address 93: 0xCF E1
Address 94: 0x05 86 0C
Address 95: 0xD0 11
Address 96: 0x05 95 0B

So yes, looks like you can read this string also from control panel , good find !

**Comment by IgorYbema** [comment]
I believe all values are stored in those 'addresses' but some addresses contain only one byte some two bytes and some more bytes. That's why they only have 96 addresses and we have 203 bytes. They are also not in the same order.

**Comment by MiG-41** [comment]
Maybe not All , but  for sure some of them could be find , most of them in hex values . ( At least now we know what is in 93-96 adresses ;) )

**Comment by geduxas** [comment]
> Maybe not All , but for sure some of them could be find , most of them in hex values . ( At least now we know what is in 93-96 adresses ;) )

Also 12 :) as manual shows it's flow meter
It seams that there is all data remote controler gets.. it could be useful data to determinate unrecognized bytes and structure..

**Comment by MiG-41** [comment]
It is only usefull , when you do something near HP... 
Some time ago tried to figure out some of them:
https://forum.murator.pl/topic/163560-panasonic-aquarea/page/394/#comment-7627892
 For me most usful is adress 8 ( with gives Target / Outlet Temp) and adress 9 (  Heater Exchenger / Inlet Temp) .
