### ISSUE TITLE
CN-NMODE isn't working (v1.0)

### ISSUE THREAD

**Issue by ThePrincelle** [heishamon/HeishaMon#203]
Hi, 

I have a Panasonic WH-SDC07F3E5 and unfortunately the connector for CN-CNT isn't soldered on the PCB so I turned to the CN-NMODE connector instead.

I bought [this HeishaMon interface on Tindie](https://www.tindie.com/products/thehognl/heishamon-v31-communication-pcb/) and connected it to the HP. While the interface is correctly powered, I do not get any data on my web interface. 

Is there something to enable for the CN-NMODE or the interface that I ordered isn't compatible ?

Is there a way to obtain some logs of the connexion between the HP and the interface ?

Thanks in advance for your response,
Maxime

**Comment by MiG-41** [comment]
Unfortunatly your HP is not H or J series , it is earler F series ( this letter is in your type) , with is not supported by HeishaMon.

Maybe you can find something for F series , here was some tries: https://github.com/v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy
