### ISSUE TITLE
how SO watthour counter should be configured?

### ISSUE THREAD

**Issue by jaripetteri** [heishamon/HeishaMon#205]
I'm using two kwh meter with pulse output connected to heishamon. How this is suppused to function? On v0.9b it added kwh values on previous value and I think it was showing meaningful values. Now on v1.0 it has changed and I remember same behavion was also earlier version before v0.9b. There is value divider both on heishamon settings and also on heishamon.yml template for Home Assistant and output is more or less nonsence to me now. Has old version somehow come back or what is behind this?

**Comment by MiG-41** [comment]
Can you show some graphs  , or at least more information , why you think it is nonsence now ?
This functions is continiously improving by @IgorYbema , and no one said that is perfect now. 
And i can't see any divider in heishamon.yml .... Actual consumption is in W , and total calculater energy is in kWh ( so divided by 1000...)

**Comment by jaripetteri** [comment]
Here is how it was ln v0.9. Pulses were counted together.
![Screenshot_2021-01-31-09-36-05-850_com google android apps photos~2](https://user-images.githubusercontent.com/23222746/106378092-74cb4200-63aa-11eb-8c82-85fc025c8f43.jpg)

Here is go it is now on v1.0. So it shows every counted pulse, or two, or three, or half?
![Screenshot_2021-01-31-09-50-35-228_io homeassistant companion android~2](https://user-images.githubusercontent.com/23222746/106378128-c2e04580-63aa-11eb-9951-1198740a1487.jpg)

Dividers are here
![Screenshot_2021-01-31-09-47-15-899_com android chrome~2](https://user-images.githubusercontent.com/23222746/106378139-d8556f80-63aa-11eb-9f9a-f2f006c5c89f.jpg)

and here
![Screenshot_2021-01-31-09-34-24-141_com android chrome~2](https://user-images.githubusercontent.com/23222746/106378150-ec996c80-63aa-11eb-90a9-c7b7dae1af2e.jpg)

**Comment by IgorYbema** [comment]
I am not sure where it got changed in which version. But now you have WattHour and WattHourTotal.
The first one is per mqtt message so you need to add them together yourself. And the second is the total.

**Comment by IgorYbema** [comment]
So you either change the topic in the yml file from WattHour to WattHourTotal or create another measurement to add watthourtotal.

**Comment by IgorYbema** [comment]
And I notice I already changed it in my repo https://github.com/IgorYbema/HeishaMon/blob/main/Integrations/Home%20Assistant/heishamon.yaml

The main repo (from egyras) will have this corrected soon.

**Comment by jaripetteri** [comment]
I have actually commented out value template on my heishamon.xlm. so received values are now like 0,003 or so on that screenshot. With value template those would be 0,000003 or so.

Does it still count some pulses together and send those in one message so that all pulses are counted?
I need to try that WattHourTotal, didn't see that at all and still using WhattHour.

Watts are showing fine, or I understand the concept there.
![Screenshot_2021-01-31-10-10-47-922_io homeassistant companion android~2](https://user-images.githubusercontent.com/23222746/106378422-50bd3000-63ad-11eb-8a40-2a5ea4e8ef8f.jpg)

**Comment by IgorYbema** [comment]
I thought I was clear enough in my earlier message. WattHour only counts watthour between mqtt messages. So each received mqtt message should be added together by the receiving system. You can use this for example if you want to split watthour between cool, dhw and heat runs. You then create a script which adds the watthour mqtt message together based on the current run (cool/dhw/heat).

For your situation, just change the WattHour to WattHourTotal and get the value_template back.

**Comment by IgorYbema** [comment]
And ofcourse please close the issue if you are satisfied :)

**Comment by jaripetteri** [comment]
Sure, thanks for the clarification.
