### ISSUE TITLE
Cunfusion around 'SetPumpSpeed'

### ISSUE THREAD

**Issue by supersjimmie** [heishamon/HeishaMon#207]
My HP has a Max Pump Duty setting in the standard remote controller.

When I set it very low to e.g. 0x5A (which is 90 decimal), the pump will run at a maximum of around 1950 rpm.
This RPM can be found in TOP65 Pump_Speed = 1950.
The value that I have set, the Duty, is seen in TOP93 Pump_Duty = 90.

When I use SetPumpSpeed, I do not set the Pump_Speed but the Pump_Duty.
So Speed and Duty are confusing here.

Even more, when I set it to 90 and the HP stops, the value in TOP93 goes to 0 while in my remote controller it is still 0x5A.

So how can I see the real setting 0x5A (as seen in the remote controller) when the HP is not running?
I would like to use that value as the feedback to the Home Assistant slider that I want to use to control the pump.
(just like many others have both read value and set value for a slider)
I cannot find any TOPxx that represents the 0x5A of 90 value in the remote controller when the HP is not active.

A am able to Set the value, but I cannot always retrieve it from the HP.

**Comment by geduxas** [comment]
I think dutty  that is showing in TOP are calculated values from HP, in controller you set maximum value in which it could go. So it's two separate values.

**Comment by MiG-41** [comment]
> When I use SetPumpSpeed, I do not set the Pump_Speed but the Pump_Duty.

True, name could be better. But in English langauage in controller option this is named : "Pump maximum speed"

But in the same time in Service cloud , TOP93 is the same , what shows "Duty".





> Even more, when I set it to 90 and the HP stops, the value in TOP93 goes to 0 while in my remote controller it is still 0x5A.
> 
> So how can I see the real setting 0x5A (as seen in the remote controller) when the HP is not running?

TOP93 is actual duty , not Max Pump Speed ( Duty). HP can modulate water pump below Max Pump Speed (Duty) to keep DeltaT ,and can be also 0 , when water pump is not running.
For Max Pump Speed (Duty) there is a byte 45 ,but no one ask for TOP from it. 
In HA for feedback you can use the same topic with you send command , and belive ,that Heishamon really set it :)

**Comment by supersjimmie** [comment]
Thanks, so I would need to modify heishamon to create a TOPxx for that byte 45?
About the feedback, yes sure I can believe it. But what if it is changed on the remote controller, like many other things can be changed at more points than only in HA? That is why I would like the TOPxx as feedback of the current setting.

**Comment by IgorYbema** [comment]
Do you also need to set the byte 45 or only read?
edit: to be clear SetPumpSpeed is to override any logic and set the pump to your request speed, just like in service menu in controller. If you want to set the pump speed for normal operation you set the MaxPumpDuty (currently not a command) just like in the normal menu of the control.

**Comment by IgorYbema** [comment]
My bad. SET15 | SetPumpSpeed already sets byte 45 but the name is wrong. It should be SetMaxPumpDuty .. i'll change that also in next beta release.

**Comment by IgorYbema** [comment]
You can try this version: https://github.com/IgorYbema/HeishaMon/blob/main/binaries/HeishaMon.ino.d1-v1.0-iy-8.bin

It contains topic95 for maxduty and changes the SetPumpSpeed command to SetMaxPumpDuty

**Comment by gregor-samosir** [comment]
Igor, you are right.

But I think, Supers is also asking for an additional TOP to have the aktual setting on the HP

TOP | 45 | 97 | (hex) 96 = 97 | Maximum set pump speed

Oh, now you are faster

**Comment by IgorYbema** [comment]
Yes: 

TOP95 | main/Max_Pump_Duty | Max pump duty configured
-- | -- | --

**Comment by supersjimmie** [comment]
Thanks Igor!!!
are there any other changes in that bin that I should be aware off?
(It's going to be very cold next week and I don't want to risk malfunction due to something that changed while I didn't know)

**Comment by IgorYbema** [comment]
You can check the commit lines (for example in https://github.com/IgorYbema/HeishaMon/tree/main/binaries). They are a bit technical. But the changes are minor and only improvements.

**Comment by IgorYbema** [comment]
please close the issue if you are happy with the result

**Comment by supersjimmie** [comment]
I have checked it and yes TOP95 is good!
