### ISSUE TITLE
problems with version 1.0 and 2.0

### ISSUE THREAD

**Issue by bse4792** [heishamon/HeishaMon#221]
Hi, i'm facing some problems with data/connection to mqtt server

i have tried to upgrade the firmware to both 1.0 and 2.0, but i always had to revert back to 0.9, as many data does not get send to mqtt and also loses connection to wifi

also "Correct received data" never reaches 100% as on 0.9

one thing i found was that model # was not shown in 2.0, but it's looking nice in 0.9

i dont know if reset would fix the issue or not, but could you please look into this?

**Comment by MiG-41** [comment]
For me it is the same topic: https://github.com/Egyras/HeishaMon/issues/196
What hardware you use ? Perhaps ou can easly "erase flash" and share if that helps.

**Comment by bse4792** [comment]
Hi Hardware is made by @MTrab, i think its a WeMos D1, he has done the programming, and i'm not that familiar with this kind of work, but i have flashed D1's before

**Comment by mi-hol** [comment]
@Egyras guess its time to close this issue
