### ISSUE TITLE
Question: Knowledge about which parameters end up in lifetime-limited non-volatile storage in heatpump?

### ISSUE THREAD

**Issue by NerdyProjects** [heishamon/HeishaMon#225]
Hey there,

thanks a lot for HeishaMon! I am considering using this or at least the decoded protocol information for my own aquarea automation/monitoring solution.

Thinking about automation, especially maximising solar usage, I wonder which parameters are safe to be controlled every few minutes?

A lot of the parameters should be stored in non-volatile storage in the heatpump (e.g. EEPROM or flash) that has limited write cycles (for example 10000 to 100000 for an EEPROM) - If I do one write every hour, the eeprom cell would be broken after a bit more than 10 years (for 100000 writes - if it only lasts 10k, it's just over 1 year).

I am wondering especially about everything that changes heating curves (as is done in the "smart controller" every few minutes) or temperature offsets - I wonder if not the SG signals should be used for that instead.

I guess there is also no long-term experience, e.g. somebody who already did more than 10000 writes to any of those parameters?

**Comment by IgorYbema** [comment]
I guess no one can give you an answer about this. Interesting question. Would make a special support case at panasonic as long you have warranty :)

**Comment by michalwoz** [comment]
@NerdyProjects I'm at the same point as you are. Have you considered using demand control? Originally it is 0-10V, but everything says it can be emulated. I think that it should be designed to allow changing demand with not limited frequency. At least from potential flash/EEPROM point of view. Of course changing demand 0%,100%,0%,100% etc, doesn't make any sense and will be very bad for compressor, but I can imagine some algorithm which makes +5%,-3%, +2% adjustments every 15 minutes.

**Comment by MiG-41** [comment]
@michalwoz ,Demand Control only sounds good , but in reality you will be not able to conrol anything . It work in special way , what we find out ,it has influence on Compressor current. In my case minimum set 5% limiting it to 3A. But 3A it is a lot in normal conditions ( let say around 0) , something like 40Hz in my case.  In many situations you will find , that this Demand Control do nothing....  Limiting Demand Control to 5% behaving more/less like to set Quiet Mode 3.

**Comment by NerdyProjects** [comment]
In addition to demand control there is the SG signals. As I don't have the heatpump yet, I don't know exactly how they will behave and how quick the heatpump will react - I understood it so you can set two temperature factors (SG1 and SG2) from 0.5 .. 1.5 that will be multiplied with the currently requested temperatures. This _should_ be enough to minimize/maximize power consumption, no? In my opinion, this should be a good enough start to e.g. maximize heating power from lunch till afternoon while there is enough power or minimize power in summer for hot water operation while there is peaks of other demand.

Maybe even the (limited, I know) demand control is good enough for that. Very nice that the parameter set is known to heishamon now. I wonder, if I should cancel my optional PCB/buffer sensor order as I think it is much more useful to do it with the optional PCB emulation :-)

**Comment by MiG-41** [comment]
Correct ,SG works in this way. But having Heishamon it is easier to set temperatures in direct way , not puting signals and let the HP to do the mathematic recalculation . 
Ofcourse writting a lot of changing temperatures can influence on eeprom , if you do it to often...

**Comment by NerdyProjects** [comment]
Well, you can set SG with the optional pcb emulation, so it stays all digital :-)

**Comment by mhulsman** [comment]
It might be possible to get full control over water temperatures without writes to non-volatile storage by emulating the extra outdoor air sensor using a digital potentiometer? I guess no one ever tried that... Temperature-resistance table is in the installation manual.  Decreasing the 'temperature' would then increase the water temperature and vice versa.   Only potential issue though would be if it affects anything else (e.g. defrost, fan speed, ...).

**Comment by IgorYbema** [comment]
That has been done by @MiG-41 I believe. But please join our slack channel to discuss this further. This is not a software issue. Can you close this one please?

**Comment by NerdyProjects** [comment]
Although this is not an issue, I think it is something users should be aware about. Would be sad to have the heatpump fail due to irresponsible writes by some home automation software... Where would it fit better? I guess by default only everything that happens through the optional PCB can be seen as "safe"...

**Comment by MiG-41** [comment]
Yes , i put seval solid resistors to set outside temperature lower , and tht is correct ,that compresor is able to modulate higher to produce more power ,and therefore higher water temperature. But i did it carfully observing parameters , doing it max for 1h , and not dare to leave it in "automation"...
Better to think about exchaning HP with higher power , if you need permanently higher water temp...

**Comment by CurlyMoo** [comment]
I don't quite see what controller values should be stored in an EEPROM or Flash. The statistics of the device itself maybe, and the settings are probably stored in an EEPROM or Flash, but why should the controlling parameters be stored there?

There is absolutely no use for it. Every decision of the heatpump is based on a sensor measurement. These sensor values can be measured in realtime when the device turns back on after being shutdown. The same counts for all decisions based on those measurements. So, i really don't think there is an issue here.

**Comment by MiG-41** [comment]
By Set Commands users can change parameters like:
-Max Water pump flow
-Parameters each of 4 Heating and Cooling Curves
- Mode 
- Temperatures for zones 
- temperature for DHW
- And generally all parameters with can be presset/changes.
Personally i hae automaions for two first parameters , with automation sets when some conitions apear.
Having in mind limit of operations for EEPROM , it is good to amount of writes  would be not higher then 50 per day ( HP for lifetime 20 years). 
That is why ,from one side good to be responsible and know ,that there is a limit in set commands , from other it woul be greatto find out how this parameters are being storaged ( becouse they are no changed after energy failure).
Maybe Panasonic have protection for it ,and there is nothing to worry , but how to be sure ?

**Comment by Celphor** [comment]
I once noticed a strange behavior, when operating cycles and hours went back to older values. I don't rememer what I've done, maybe a reset because of frequent cyling. So it seems not every set value is written to the eeprom immediately. Maybe only after a few minutes from RAM to EEPROM. Look at the graph 
![image](https://github.com/Egyras/HeishaMon/assets/22246844/6be7cb0a-521a-4da3-8bf9-4bd63d0518c9)

**Comment by MiG-41** [comment]
...or first sympthoms of broken EEPROM ...

**Comment by Celphor** [comment]
I don't think so, this happened 2 months ago and never showed up again

**Comment by Celphor** [comment]
Does anybody know the model of the used flash chip? On my indoor unit i can't locate one on the frontside. Don't know if the board is double sided. If the model is known the spec should provide info about number of writes per cell.

**Comment by MiG-41** [comment]
Had a picture of my PCB on back side ( yes it is doublesided) , main CPU and surrounded chip (could be EEPROM) is wihout markings , and also glued with some siliconlike thing.

**Comment by Celphor** [comment]
If it really fails: The boards are not that expensive, <400€. Maybe I should keep one in stock ^^

**Comment by edterbak** [comment]
I just read an issue report that my node red flow will in fact as a certainty kill the eeprom on the panasonics...   _(nice report)_

I have developed the node red flow, and in the beginning I probably flooded my pump with set commands. (Imagine 1 cmd per minute for weeks)

Is there a way to get some sort of reading on the health state of the EEPROM? 


Typically the node red flow produces the following amount of set commands per day: 
low: 0-10 
normal: 20-40
high: 80-150*
*The high scenario only applies when a user has enabled all my custom functions and have set it up that it reacts a bit nervous / jumpy.

FYI. 
I personally do not have an issue so far. I have no indication of a problem yet.
My pump is installed in jan-2021.
If I were to make an estimate on how many commands have been sent to my pump, I would guess 250k+ at least.

**Comment by mi-hol** [comment]
> I just read an issue report that my node red flow will in fact as a certainty kill the eeprom on the panasonics... _(nice report)_

@edterbak are you referring to https://github.com/edterbak/NodeRed_Heishamon_control/issues/169 ?

From my view this specific issue fails to provide any hard facts and just makes claims with no evidence!

**Comment by HighlyCompressedAir** [comment]
If every command is written to EEPROM immediately as the heat pump's behavior suggests (if you change a parameter and turn off the breaker, the change will be there after the power is back on), then it will break the chip eventually, it's just a matter of when. Most EEPROMs can take 100k to 1kk writes and these are hard facts.
So far nobody proved that Panasonic heat pumps work differently, therefore in my opinion we should assume the worst case scenario.
I think that number one priority for these projects should be discovering how it actually works. The fact that this issue is unresolved for years now seems dangerous to me, especially if users are unaware.

**Comment by edterbak** [comment]
> "The fact that this issue is unresolved for years now seems dangerous to me, especially if users are unaware."

Maybe reverse psychology is applicable here.
The longer this 'issue' keeps being unresolved, the more it seems to prove it is not a real issue.

If anyone has more data supporting the fact this is a real issue and we all agree on it that it is true... I will instantly take the node red flow offline.

**Comment by HighlyCompressedAir** [comment]
Obviously it's an issue that won't manifest itself for years until it's too late. I don't want you to take your project down, just warn users of possible consquences and try to minimize writes as much as possible with every feature until someone figures out how things work.
Panasonic users aren't the first who thought of this problem. Here's a thread from 2019 regarding Nibe heat pumps. https://www.energiesparhaus.at/forum-nibe-wp-wie-oft-kann-man-parameter-veraendern-flash-lebensdauer/55835_1
They actually got an answer from Nibe representative:
`The EEPROM settings are stored has, according to the datasheet, a limit of 1 million writes per position. That may of course sound a lot but if you write every second that means only 11.5 days until the EEPROM position dies. So to answer the question, when calculating with 15 years of life the maximum would be 182 writes per day per setting`
And Nibe officialy supports third party control via Modbus, Heishamon had to be reverse-engineered. Do you think that Panasonic engineered their pump to take 100+ commands a day when there's not even an interface for it? I doubt that.

**Comment by mi-hol** [comment]
> They actually got an answer from Nibe representative:

this is a real fact

> Do you think that Panasonic engineered their pump to take 100+ commands a day when there's not even an interface for it? I doubt that.

Panasonic is using readily available EEPROM components, therefore above conclusion is pure speculation and not relevant from my view!

**Comment by IgorYbema** [comment]
Please stop the discussion. The EEPROM issues could be a thing and as long as we don't know what the limit is, it is better not to overload with commands. 

If anyone wants to try which settings are written to EEPROM it is an easy test. Just send a command, then power cycle the heatpump 10 seconds later and check if the setting is still changed.

And if anyone wants to take a photo of the backside of the mainboard to see what MCU and EEPROM it is using we can take a rough guess.

**Comment by IgorYbema** [comment]
https://github.com/IgorYbema/HeishaMon/blob/main/README.md#eeprom-warning

**Comment by edterbak** [comment]
> Please stop the discussion. The EEPROM issues could be a thing and as long as we don't know what the limit is, it is better not to overload with commands.
> 
> If anyone wants to try which settings are written to EEPROM it is an easy test. Just send a command, then power cycle the heatpump 10 seconds later and check if the setting is still changed.
> 
> And if anyone wants to take a photo of the backside of the mainboard to see what MCU and EEPROM it is using we can take a rough guess.

What do you considder to be a power cycle?
off/on on the wallmounted controller? How much time between off/on?

I can test in upcoming week on a couple of settings...

**Comment by IgorYbema** [comment]
> > Please stop the discussion. The EEPROM issues could be a thing and as long as we don't know what the limit is, it is better not to overload with commands.
> > If anyone wants to try which settings are written to EEPROM it is an easy test. Just send a command, then power cycle the heatpump 10 seconds later and check if the setting is still changed.
> > And if anyone wants to take a photo of the backside of the mainboard to see what MCU and EEPROM it is using we can take a rough guess.
> 
> What do you considder to be a power cycle? off/on on the wallmounted controller? How much time between off/on?
> 
> I can test in upcoming week on a couple of settings...

This is also unknown :-)
But at least try a full power shutdown (breakers off).
Try SetQuietMode, SetDHWTemp, SetOperationMode first. I believe at least one of them should return to the set value after power cycle.

**Comment by mi-hol** [comment]
> Please stop the discussion.

May I suggest an alternative approach to turn this into a non-issue by knowing "how to replace a broken EEPROM"?

**Comment by HighlyCompressedAir** [comment]
> May I suggest an alternative approach to turn this into a non-issue by knowing "how to replace a broken EEPROM"?
It's not that simple, because EEPROM most likely stores the whole operating system. You would have to read it first when it still works properly and make a copy of it's contents, then buy the exact same memory chip model, flash it with previously saved data, desolder the broken module and solder the new one.

Afaik every parameter that can be set survives power outage (SetPump may be an exception, but I'm not sure), so only fake sensors make 0 writes (optional pcb emulation).

**Comment by mi-hol** [comment]
> It's not that simple, because EEPROM most likely stores the whole operating system. You would have to read it first when it still works properly and make a copy of it's contents, then buy the exact same memory chip model, flash it with previously saved data, desolder the broken module and solder the new one.

This outlines basically the process I had in mind.
Next step would be to sort out the details to make this an actionable plan.

1. is a working Panasonic board already available to someone? 
2. is manufacturer & part number of EEPROM readable on this board?
3. can EEPROM content be cloned by a tool (i.e. https://fiedka.app)

**Comment by geduxas** [comment]
If i remember correctly.. @MiG-41 i think have some PCB photos of back side.. or knows exactly CPU model.. 

PCB is under heavy layer of varnish..

**Comment by MiG-41** [comment]
Yes , had somwhere. No markings on chips , and covered with some layer of silicone ( like in automotive applications).

**Comment by HighlyCompressedAir** [comment]
What about the remote controller? It definitely has a memory of some kind (battery powered presumably) as it remembers date and time, weekly timer, holiday timer and the pump itself has no way to access those (Smart Cloud has it's own online weekly timer and you can enable holiday mode, but can't set it's date and time). And when you select "System check" there's a prompt saying "Retrieving data..." for a few seconds. Maybe it's because the controller has to read the logs off the pump's EEPROM and it takes some time, while all the other parameters can be seen immediately, because they're stored in the controller itself so there is no delay. If someone has access to two similar pumps they can swap controllers and see what happens to settings. Or see if it's possible to change a parameter through Heishamon with the controller disconnected (if error H76 won't happen immediately). Or disassemble the controller and look for a battery, remove it for some time and see what happens.

**Comment by mi-hol** [comment]
> If it really fails: The boards are not that expensive, <400€. Maybe I should keep one in stock ^^

@Celphor did you perhaps buy a spare?

**Comment by mi-hol** [comment]
> Yes , had somwhere.

@MiG-41 would you mind to post them here?

**Comment by NerdyProjects** [comment]
> > Please stop the discussion. The EEPROM issues could be a thing and as long as we don't know what the limit is, it is better not to overload with commands.
> > If anyone wants to try which settings are written to EEPROM it is an easy test. Just send a command, then power cycle the heatpump 10 seconds later and check if the setting is still changed.
> > And if anyone wants to take a photo of the backside of the mainboard to see what MCU and EEPROM it is using we can take a rough guess.
> 
> What do you considder to be a power cycle? off/on on the wallmounted controller? How much time between off/on?
> 
> I can test in upcoming week on a couple of settings...

It could totally be implemented "properly": Settings are kept in RAM and are only written to EEPROM when power is removed. If you as an engineer see any need to limit the number of EEPROM writes, you would implement it like this. You just need a power gone signal and 10-20ms of time remaining (e.g. through capacitors keeping the MCU and EEPROM alive).
What I want to say: There is not many reliable ways to test this out.
One could be doing writes we expect to hit the EEPROM millions of times to see what happens.
Another one could be wiring the EEPROM up to some circuit and watching writes while changing settings.

**Comment by geduxas** [comment]
> What about the remote controller? It definitely has a memory of some kind (battery powered presumably) as it remembers date and time, weekly timer, holiday timer and the pump itself has no way to access those (Smart Cloud has it's own online weekly timer and you can enable holiday mode, but can't set it's date and time). And when you select "System check" there's a prompt saying "Retrieving data..." for a few seconds. Maybe it's because the controller has to read the logs off the pump's EEPROM and it takes some time, while all the other parameters can be seen immediately, because they're stored in the controller itself so there is no delay. If someone has access to two similar pumps they can swap controllers and see what happens to settings. Or see if it's possible to change a parameter through Heishamon with the controller disconnected (if error H76 won't happen immediately). Or disassemble the controller and look for a battery, remove it for some time and see what happens.

Yes, remote controler works as another gateway, it retrieves stored data from heatpump. Also for "Scheduler calendar" cloud and remote controller have it's own logic by which send setting to pump. There is only possibility to turn on/off schedule indicator, to let user know that pump is operating by scheduled task's.

**Comment by mi-hol** [comment]
> It could totally be implemented "properly": Settings are kept in RAM and are only written to EEPROM when power is removed.

I'm also assuming that Panasonic did implement it properly, reasoning is:  "avoid cost for warranty claims due to EEPROM failures". Large companies usually control warranty costs via technical design requirements!

**Comment by edterbak** [comment]
Finally had time to do some testing. This is the result

![image](https://github.com/user-attachments/assets/14b09946-442e-4033-8e0c-d31c5fc9eb96)

Power on/off is physically switching the breaker to the heatpump. 
Below that is the result after 5 minutes of waiting to be sure heishamon has received the latest values from the HP and relaying it.

**Comment by IgorYbema** [comment]
So yeah, these will have been written to eeprom somehow. Could be smart (only writing when power is down, using some rest over condensator power) but probably not.
Should I builtin a limit of about 100 commands per day (which will be way enough for normal practice and will probably never cause any eeprom issue)? And ofcourse an option to change/disable this limit.

**Comment by HighlyCompressedAir** [comment]
> So yeah, these will have been written to eeprom somehow. Could be smart (only writing when power is down, using some rest over condensator power) but probably not. Should I builtin a limit of about 100 commands per day (which will be way enough for normal practice and will probably never cause any eeprom issue)? And ofcourse an option to change/disable this limit.

I think a warning is enough.
But I remembered something, maybe you can explain it. I have set Pool Temp to 27 a few days ago when I tested optional pcb commands. In the mean time I powered off my pump a few times and the value is still 27. When I connect just the CZ-TAW1 (Service Cloud), it reads -78. And then when I disconnect it and connect Heishamon again, the reading goes back to 27 which suggests that it is stored somewhere in Heishamon's memory. How is that possible? After an hour without power?
In fact it seems that all optional pcb commands survive power cycle. I did SetCompressorState to 0 at some point and forgot about it. The next day I was surprised that the pump didn't work and it took me a while to understand why. SetSmartGridMode does the same thing.

**Comment by geduxas** [comment]
@HighlyCompressedAir it's depends how you set commands to heishamon, if it's over mqtt it could be that it has retained flag (which stores value in mqtt server) 
Also heishamon stores it while it's running.. if you somehow not disconnected it from power supply, it could be left in memory

**Comment by geduxas** [comment]
> So yeah, these will have been written to eeprom somehow. Could be smart (only writing when power is down, using some rest over condensator power) but probably not. Should I builtin a limit of about 100 commands per day (which will be way enough for normal practice and will probably never cause any eeprom issue)? And ofcourse an option to change/disable this limit.

How about other communication methods? It has knx and Modbus interface, and didn't see anywhere about limit's in documentation, or naturally from them will not be any flood?

**Comment by edterbak** [comment]
Yeah, review the method how I did this might be wise. 
Is the result trustworthy.

I do see retain flag when I open MQTT explorer on these values. So I dont know what happens when power is restored to the pump. Does Heishamon do anything at that moment, or the broker.. Truly I dont know.

**Comment by HighlyCompressedAir** [comment]
With mqtt server powered off it's the same thing. I just switched the breaker to power off my pump, waited 5 minutes and powered it up again - Pool Temp is still 27. Heishamon doesn't have external power connected so it has to hold charge somehow.

**Comment by geduxas** [comment]
> With mqtt server powered off it's the same thing. I just switched the breaker to power off my pump, waited 5 minutes and powered it up again - Pool Temp is still 27. Heishamon doesn't have external power connected so it has to hold charge somehow.

Indeed optional PCB stores it's data once in 5min. I have missed that :)

**Comment by edterbak** [comment]
> So yeah, these will have been written to eeprom somehow. Could be smart (only writing when power is down, using some rest over condensator power) but probably not. Should I builtin a limit of about 100 commands per day (which will be way enough for normal practice and will probably never cause any eeprom issue)? And ofcourse an option to change/disable this limit.

In the node red dashboard, I have a setting like this:
![image](https://github.com/user-attachments/assets/16b0dc2f-9f41-4543-8d1e-c0e0cfaa312d)

In the code, I have the default limit to 500 a day. 
This is only reached in case of an programming error. looping stuff. Then the failsafe kicks in.

Maybe you can use this as inspiration (iginoring the actual values used in the screenshot)

**Comment by Celphor** [comment]
> > If it really fails: The boards are not that expensive, <400€. Maybe I should keep one in stock ^^
> 
> @Celphor did you perhaps buy a spare?

No. Not yet. Everything fine so far

**Comment by geduxas** [comment]
Ik we have one user who have cascade controller with Modbus, and he claims that cascade controller updates/changes registers every 20-30 sec. So if it works in official setup, maybe there is not so much problems?

**Comment by edterbak** [comment]
> Ik we have one user who have cascade controller with Modbus, and he claims that cascade controller updates/changes registers every 20-30 sec. So if it works in official setup, maybe there is not so much problems?

I hope this is true. That would take away our worry and we can release any restrictions. :) 
For now we dont know for sure yet. So caution should apply of course.

**Comment by geduxas** [comment]
https://github.com/Egyras/HeishaMon/discussions/565#discussioncomment-11062501
