### ISSUE TITLE
Need help with CN-NMODE in F series

### ISSUE THREAD

**Issue by slqa** [heishamon/HeishaMon#229]
Hello,

I commented on other projects related to F series heatpumps, but maybe here I will find some information which will be helpful for me.
I tried to connect HeishaMon to my F series heatpump. Obviously I failed, I omitted information that it is for H series. 
But I found out that in CN-NMODE in F series there is ASCII stream with status information. Also there is possibility to request internal address value, when send 2 bytes ASCII coded address.
I'm wondering if anyone tried or know what can be done via CN-NMODE in F series. Tx/Rx lines are shorted with not populated CN-CNT, like in H series. Maybe someone knows for which purpose NMODE connector exists, maybe that will make any clue what more can be done.

F series ASCII stream
![image](https://user-images.githubusercontent.com/5516543/137374442-ea6affbe-ea12-4472-8ec4-b68a3f495efa.png)

[My orginal comment on other project related to F series](https://github.com/v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy/issues/3#issuecomment-943596031)

**Comment by IgorYbema** [comment]
Take a look at https://github.com/v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy

**Comment by IgorYbema** [comment]
I don't think you get anyone here to help on that. We all have H and J series.
I hope that other repo will help you but I think there are just not enough owners for the G and F series

**Comment by Frogeye88** [comment]
Hi slqa,

Have you made any progress. I have an F generation Aquarea and was hoping to gain a bit more control of it. At the moment my only 'smart' improvement is using a switchbot to turn it off and on! It would great to be able to switch through the 'mode' settings (I use mine for heat and DHW (tank)).

I've often wondered about the intesishome route but there is so little information about it.

**Comment by isobolewski** [comment]
Hello, I also habe F generation unit T-CAP IDU: WH-SXC09F3E8. I so much would wish do get the unit to Wifi and read out some values. Is there anywere a chance?

**Comment by elvisquaglia** [comment]
> Ciao,
> 
> Ho commentato altri progetti relativi alle pompe di calore della serie F, ma forse qui troverò qualche informazione che mi sarà utile. Ho provato a collegare HeishaMon alla mia pompa di calore della serie F. Ovviamente ho fallito, ho omesso l'informazione che è per la serie H. Ma ho scoperto che in CN-NMODE nella serie F c'è un flusso ASCII con informazioni sullo stato. C'è anche la possibilità di richiedere il valore dell'indirizzo interno, quando si inviano 2 byte di indirizzo codificato ASCII. Mi chiedo se qualcuno abbia provato o sappia cosa si può fare tramite CN-NMODE nella serie F. Le linee Tx/Rx sono in cortocircuito con CN-CNT non popolato, come nella serie H. Forse qualcuno sa per quale scopo esiste il connettore NMODE, forse questo darà qualche indizio su cosa si può fare di più.
> 
> Flusso ASCII serie F ![image](https://user-images.githubusercontent.com/5516543/137374442-ea6affbe-ea12-4472-8ec4-b68a3f495efa.png)
> 
> [Il mio commento originale su un altro progetto correlato alla serie F](https://github.com/v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy/issues/3#issuecomment-943596031)

Hi, have you found any solution for your F series pump, I have a G and I think I'm in the same situation

**Comment by slqa** [comment]
Hi,
I made my own project for ESPHome https://github.com/slqa/aquarea_esphome
 based on other approaches like this https://github.com/v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy
Unfortunately, there isn't any other simpler options for older devices like F/G series.

**Comment by elvisquaglia** [comment]
Hi, but this code works on the series G?Elvis QuagliaIl giorno 12 lug 2025, alle ore 13:10, slqa ***@***.***> ha scritto:﻿slqa left a comment (Egyras/HeishaMon#229)
Hi,
I made my own project for ESPHome https://github.com/slqa/aquarea_esphome
based on other approaches like this https://github.com/v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy
Unfortunately, there isn't any other simpler options for older devices like F/G series.

**Comment by slqa** [comment]
Hi,
I have F series pump, so I can confirm working on that one. I think G series can be controlled with approach on which I based my project, so it should also work. So, you will have to confirm if this is true.
