### ISSUE TITLE
Set week timer?

### ISSUE THREAD

**Issue by NerdyProjects** [heishamon/HeishaMon#231]
Hi there :-)

Can anybody offer more serial packet dumps to figure out how to set the weekly timer or silent timer? I don't own a cloud module but apparently it is possible there?

I also wonder if anybody ever tried looking at the communication interface between the heatpump and the remote control?

**Comment by MiG-41** [comment]
No , it wasn't possible to set weekly or silent timer on HP via cloud module. Instead this CZ-TAW1 have it's own timer , with you can edit via cloud , and when the time came, CZ-TAW1 just set that function. So this cloud timer is not visible on HP display.

And communication beetwen HP controller and HP it self probably not give any advantage ....
