### ISSUE TITLE
Possibility to read energy monitor values?

### ISSUE THREAD

**Issue by Riemen** [heishamon/HeishaMon#240]
Is there any possibility to read the values from energy monitor in Aquarea menu?
I would like to log the values for energy consumption, heat output and cop.

**Comment by MiG-41** [comment]
Not possible. HP is providing only actual powers ( not energys)  for consumption , heat/cool/dhw production.Base on this steering controler calculating them self energies and calculating COP.Actual powers (providing by HP) are also not accurate , so calculating from it energies are also not so good.
