### ISSUE TITLE
Read params without MQTT

### ISSUE THREAD

**Issue by Aea263** [heishamon/HeishaMon#242]
Hi, sorry about that question, but I´m newbe using HeishaMon, and I will like to integrate with my existing domotic system (Loxone).
I have clearly read and undestand I can send commands via http interface, dosen´t look much complicated, but what about read params in the same way I can´t find the way.

 Thanks in advance

**Comment by IgorYbema** [comment]
Without MQTT you can use the http://heishamon.local/json url to receive the current values.
