### ISSUE TITLE
HTTP REST API sometimes not responding

### ISSUE THREAD

**Issue by Aea263** [heishamon/HeishaMon#243]
Just started HeishaMon a couple Weeks Ago, I noticed some issues on HTTP REST API, sometimes the http command request didin´t work I check the console but just shows rx commands, is there any way to troubleshoot the HTTP REST API method?.

Thanks in advance

**Comment by IgorYbema** [comment]
Your automation should have a logic inside to check if a new value (with setcommand) has been acknowledge by checking the received values a few seconds later and try again if it didn't change.
Using the rest api is less preferred as the webserver on the heishamon is not always responding properly. Mqtt will guarantee delivery of a request. But also then your automation should check if a command is processed and resend the command if not.
