### ISSUE TITLE
Outlet Targer Temperature

### ISSUE THREAD

**Issue by pawelkli** [heishamon/HeishaMon#249]
Hi, 
Is it possible to add an Outlet Target Temperature setting?

**Comment by IgorYbema** [comment]
You mean to set TOP7 - Main_Target_Temp ?

This is the result of the settings of the heat curve or direct mode and the heat shift. These are all settings which you can change https://github.com/IgorYbema/HeishaMon/blob/main/MQTT-Topics.md#command-topics

**Comment by pawelkli** [comment]
All is now clear. I am using an HP Aquarea with a CZ-TAW1. I got here from a project based on HeishaMon - GoHeishaMon. They point to a list of topics compatible with both projects, but not everything is implemented in GoHeishaMon.
Thank You for your help.
