### ISSUE TITLE
HeishaMon 2.0 losing WiFi connection regularly

### ISSUE THREAD

**Issue by ogbrugge** [heishamon/HeishaMon#252]
My HeishaMon running 2.0 is regularly losing connection to my WiFi network, roughly two to three times per week, I have a Unify WiFi access point very close to the HeishaMon so it cannot be the signal strength being too weak.  Is there any way to debug the reason why HeishaMon is not realizing the connection is gone? Sometimes it spontaneously reboots, i can see that by the up time, is this to reconnect to the network?

**Comment by IgorYbema** [comment]
Could you try this test build for v3.0 which also adds some wifi improvements?https://github.com/IgorYbema/HeishaMon/suites/6553213424/artifacts/244882468

**Comment by ogbrugge** [comment]
I installed it and will let you know if this is more stable. Thank you for the quick response!

**Comment by ogbrugge** [comment]
So far so good, no connection losses, no spontaneous Heishamon reboots. I think this is fixing my problem, will keep an eye on for a while longer,

**Comment by markuspulch** [comment]
Hi, I have the same issue but it looks the the build is not available anymore? ;-(

**Comment by HighlyCompressedAir** [comment]
Fixed in #260 .
This issue can be closed.
