### ISSUE TITLE
Indication on actual operation (not operation mode)

### ISSUE THREAD

**Issue by Donpepe23** [heishamon/HeishaMon#254]
Hi,

on the remote there is a small arrow, indicating the actual operation mode.  Is there a topic available?  

Thanks

**Comment by IgorYbema** [comment]
No I checked again today. Someone else asked it also but there is no byte changing when the heatpump is operation (expect to the ones that we knew about, like water flow and temps). I would guess the small arrow is just showing when the water flow not zero.

**Comment by Donpepe23** [comment]
HI,

good hint... The small arrow is indeed just the indication of "Three valve status + water flow not zero".

Thanks
