### ISSUE TITLE
REST API cant set 2 commands at one time

### ISSUE THREAD

**Issue by Bogeyof** [heishamon/HeishaMon#257]
In Documentation, there is written the following:
`HTTP REST API: http://x.x.x.x/command?[topic]=[value]&[topic]=[value] (e.g.: http://x.x.x.x/command?SetQuietMode=3&SetZ1HeatRequestTemperature=21_`

If I try this like "http://192.168.xxx.xxx/command?SetDHWTemp=49&SetQuietMode=3", I get two answers from Webinterface:
```
set DHW temperature to 49
set Quiet mode to 3
```

But only the first parameter would be set after this command, the second would never change...
I tried it with many combinations of SetParams.

**Comment by IgorYbema** [comment]
which version heishamon are you using?
could you try this test build for v3.0? https://github.com/IgorYbema/HeishaMon/suites/6553213424/artifacts/244882468

**Comment by Bogeyof** [comment]
I will try it and report later...

I'm using 2.0a for now

**Comment by Bogeyof** [comment]
I tried Firmware v3.0, still the same behavior, second param would not be set. 
Can´t use Firmware v3.0, cause JSON-Output is messed up. Many Params are doubled, for example TOP12 "Operations_counter" and many more. So my reading routine failed...
Where can I get v2.0a for Download again. Could only find v2.0 or v2.1 and greater?
For now I´m using v2.0, don´t know what are the differences to v2.0a?

**Comment by IgorYbema** [comment]
2.0a is only a temp fix for correcting the 'error' counter. You can use v2.0 for now.
Thanks for the feedback about the json output. Didn't see that before. I'll fix that right away

**Comment by IgorYbema** [comment]
Also, while testing your report it seems to work for me:
panasonic_heat_pump/log Tue Jul 12 16:03:55 2022 (132049): set DHW temperature to 49
panasonic_heat_pump/log Tue Jul 12 16:03:55 2022 (132050): Already sending data. Buffering this send request
panasonic_heat_pump/log Tue Jul 12 16:03:55 2022 (132055): set Quiet mode to 1
panasonic_heat_pump/log Tue Jul 12 16:03:55 2022 (132060): Already sending data. Buffering this send request
...
panasonic_heat_pump/log Tue Jul 12 16:03:55 2022 (132199): Sending command from buffer
...
panasonic_heat_pump/log Tue Jul 12 16:03:56 2022 (132697): Sending command from buffer
...
panasonic_heat_pump/log Tue Jul 12 16:03:56 2022 (133188): received TOP9 DHW_Target_Temp: 49
...
panasonic_heat_pump/log Tue Jul 12 16:03:57 2022 (133688): received TOP18 Quiet_Mode_Level: 1

This is with v3.0

**Comment by IgorYbema** [comment]
A fixed v3.0 with good json https://github.com/IgorYbema/HeishaMon/suites/7324789941/artifacts/296361221

**Comment by Bogeyof** [comment]
Thanks, tried v3.0 again and JSON is good, my reading routine is working again.
Setting of 2 Params still not working for me, second param is never set. I´m using "http://192.168.xxx.xxx/command?SetDHWTemp=49&SetQuietMode=2". DHW Temp changes, Quiet Mode doesn´t change. Still got Output in Browser for both settings, but second setting doesn´t change in Heishamon after sending HTTP-Request.
How can I get the log like you posted. Is it possible I have problems cause I´m not using MQTT (also didn´t specify a Server for MQTT)?

**Comment by IgorYbema** [comment]
No, MQTT should be seperated from that issue. But yes the log I created is from the mqtt post.
However same log is also on the web interface - console tab. Can you check there?

**Comment by Bogeyof** [comment]
Sorry, for me on the console tab there is nothing, only a black area. Tried to enable hexdump log or MQTT log, but always only black area. MQTT log isn´t shown, may because if have no MQTT? Hexdump log also no output on console tab...

**Comment by IgorYbema** [comment]
No that is independent. The console log should be visible. Weird. Maybe browser issue? Which browser are you using?
It is a websocket connection from the browser to heishamon which is displaying the logs.

**Comment by Bogeyof** [comment]
Tested a minute ago with Chrome, Edge and Firefox, black area, no data...

**Comment by Bogeyof** [comment]
Heishamon hangs in the basement, another WLAN is active there and routed via a port so that I can access the web interface. Possibly the problem is to be found here...

**Comment by IgorYbema** [comment]
websocket it on same port as http (port 80) but if you are forwarding some other port (like 8080 or something) that could be the reason indeed

**Comment by IgorYbema** [comment]
not the reason for this bug report, but for the console tab being empty (black)

**Comment by Bogeyof** [comment]
I`m routing Port 80 (to 9021). I try in basement in other WLAN now...

**Comment by Bogeyof** [comment]
OK, in basement with my Smartphone, I get messages on console tab:
Tue Jul 12 17:13:46 2022 (71266): New webserver client: 192.168.16.113:44418
Tue Jul 12 17:13:46 2022 (71274): set DHW temperature to 48
Tue Jul 12 17:13:46 2022 (71275): sent bytes: 111 including checksum value: 226 
Tue Jul 12 17:13:46 2022 (71277): set Quiet mode to 1
Tue Jul 12 17:13:46 2022 (71281): Already sending data. Buffering this send request
Tue Jul 12 17:13:46 2022 (71332): Closing webserver client: 192.168.16.113:44418
Tue Jul 12 17:13:46 2022 (71714): Received 203 bytes data
Tue Jul 12 17:13:46 2022 (71714): Checksum and header received ok!
Tue Jul 12 17:13:46 2022 (71717): received TOP6 Main_Outlet_Temp: 32
Tue Jul 12 17:13:46 2022 (71727): received TOP51 Inside_Pipe_Temp: 27
Tue Jul 12 17:13:46 2022 (71729): received TOP56 Z1_Temp: 32
Tue Jul 12 17:13:47 2022 (71740): Sending command from buffer
Tue Jul 12 17:13:47 2022 (71741): sent bytes: 111 including checksum value: 130 
Tue Jul 12 17:13:49 2022 (73746): Previous read data attempt failed due to timeout!
Tue Jul 12 

May be cause I read Heishamon from PHP-Skript every minute, Client will always close before sendig of data is ok.

**Comment by IgorYbema** [comment]
No I am more looking at this
Tue Jul 12 17:13:49 2022 (73746): Previous read data attempt failed due to timeout
Seems some reading issue. But need more log after that.

**Comment by IgorYbema** [comment]
And try to set a different value than currently set so heishamon logs the change

**Comment by Bogeyof** [comment]
This time no param was changed:

Tue Jul 12 17:39:20 2022 (977090): Closing webserver client: 192.168.77.20:62884
Tue Jul 12 17:39:41 2022 (998083): New webserver client: 192.168.16.113:45424
Tue Jul 12 17:39:41 2022 (998107): set DHW temperature to 47
Tue Jul 12 17:39:41 2022 (998108): sent bytes: 111 including checksum value: 227 
Tue Jul 12 17:39:41 2022 (998110): set Quiet mode to 3
Tue Jul 12 17:39:41 2022 (998114): Already sending data. Buffering this send request
Tue Jul 12 17:39:41 2022 (998135): Received 203 bytes data
Tue Jul 12 17:39:41 2022 (998135): Checksum and header received ok!
Tue Jul 12 17:39:41 2022 (998145): received TOP55 Ipm_Temp: 26
Tue Jul 12 17:39:41 2022 (998154): Sending command from buffer
Tue Jul 12 17:39:41 2022 (998216): sent bytes: 111 including checksum value: 114 
Tue Jul 12 17:39:41 2022 (998233): Closing webserver client: 192.168.16.113:45424
Tue Jul 12 17:39:41 2022 (998680): New webserver client: 192.168.16.113:45422
Tue Jul 12 17:39:43 2022 (1000219): Previous read data attempt failed due to timeout!
Tue Jul 12 17:39:43 2022 (1000219): Received 0 bytes data
Tue Jul 12 17:39:50 2022 (1007127): New webserver client: 192.168.77.20:62900
Tue Jul 12 17:39:51 2022 (1008607): Closing webserver client: 192.168.77.20:62900
Tue Jul 12 17:40:03 2022 (1020029): Lost MQTT connection!
Tue Jul 12 17:40:03 2022 (1020029): Reconnecting to mqtt server ...
Tue Jul 12 17:40:03 2022 (1020032): Heishamon stats: Uptime: 0 days 0 hours 17 minutes 0 seconds ## Free memory: 74% ## Heap fragmentation: 10% ## Max free block: 26944 bytes ## Free heap: 29784 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 90.91%
Tue Jul 12 17:40:03 2022 (1020055): Requesting new panasonic data
Tue Jul 12 17:40:03 2022 (1020059): sent bytes: 111 including checksum value: 18 
Tue Jul 12 17:40:03 2022 (1020490): Received 203 bytes data
Tue Jul 12 17:40:03 2022 (1020490): Checksum and header received ok!
Tue Jul 12 17:40:11 2022 (1028681): Timeout webserver client: 192.168.16.113:45422
Tue Jul 12 17:40:11 2022 (1028682): Closing webserver client: 192.168.16.113:45422
Tue Jul 12 17:40:12 2022 (1029659): New webserver client: 192.168.77.223:49702
Tue Jul 12 17:40:14 2022 (1031403): Closing webserver client: 192.168.77.223:49702
Tue Jul 12 17:40:21 2022 (1038643): New webserver client: 192.168.77.20:62917
Tue Jul 12 17:40:23 2022 (1040157): Closing webserver client: 192.168.77.20:62917

**Comment by IgorYbema** [comment]
Thanks. Are you sure the DHW=47 and quiet=3 where new values (they are different than the current values at the time)?
If values are the same they are not displayed as changed.

**Comment by Bogeyof** [comment]
> Thanks. Are you sure the DHW=47 and quiet=3 where new values (they are different than the current values at the time)? If values are the same they are not displayed as changed.

Yes, value before was 48 and quiet mode 1.

Now I tried again with Computer off (it was also connected to heishamon, may be the cause for closing connectings very fast), tried again with Smartphone in basement, this time values are both changed. Values before was 48 and 0. Sending 2 combinations, first 48 / 1 and  second 47 / 1.  Values after second sending are 47 / 1:

Tue Jul 12 17:51:16 2022 (1693913): New webserver client: 192.168.16.113:45760
Tue Jul 12 17:51:17 2022 (1694337): Closing webserver client: 192.168.16.113:45760
Tue Jul 12 17:51:18 2022 (1695122): Closing webserver client: (IP unset):0
Tue Jul 12 17:51:27 2022 (1704070): New webserver client: 192.168.16.113:45766
Tue Jul 12 17:51:27 2022 (1704079): set DHW temperature to 48
Tue Jul 12 17:51:27 2022 (1704080): sent bytes: 111 including checksum value: 226 
Tue Jul 12 17:51:27 2022 (1704082): set Quiet mode to 1
Tue Jul 12 17:51:27 2022 (1704086): Already sending data. Buffering this send request
Tue Jul 12 17:51:28 2022 (1705857): Received 203 bytes data
Tue Jul 12 17:51:28 2022 (1705857): Checksum and header received ok!
Tue Jul 12 17:51:28 2022 (1705868): received TOP64 High_Pressure: 14.4
Tue Jul 12 17:51:28 2022 (1705879): Sending command from buffer
Tue Jul 12 17:51:28 2022 (1705879): sent bytes: 111 including checksum value: 130 
Tue Jul 12 17:51:28 2022 (1705910): Closing webserver client: 192.168.16.113:45766
Tue Jul 12 17:51:29 2022 (1706334): Received 203 bytes data
Tue Jul 12 17:51:29 2022 (1706334): Checksum and header received ok!
Tue Jul 12 17:51:48 2022 (1725066): New webserver client: 192.168.16.113:45772
Tue Jul 12 17:51:48 2022 (1725076): set DHW temperature to 47
Tue Jul 12 17:51:48 2022 (1725077): sent bytes: 111 including checksum value: 227 
Tue Jul 12 17:51:48 2022 (1725079): set Quiet mode to 2
Tue Jul 12 17:51:48 2022 (1725083): Already sending data. Buffering this send request
Tue Jul 12 17:51:48 2022 (1725123): Closing webserver client: 192.168.16.113:45772
Tue Jul 12 17:51:48 2022 (1725556): Received 203 bytes data
Tue Jul 12 17:51:48 2022 (1725556): Checksum and header received ok!
Tue Jul 12 17:51:48 2022 (1725561): received TOP18 Quiet_Mode_Level: 1
Tue Jul 12 17:51:48 2022 (1725577): Sending command from buffer
Tue Jul 12 17:51:48 2022 (1725578): sent bytes: 111 including checksum value: 122 
Tue Jul 12 17:51:50 2022 (1727580): Previous read data attempt failed due to timeout!
Tue Jul 12 17:51:50 2022 (1727581): Received 0 bytes data
Tue Jul 12 17:51:51 2022 (1728757): Lost MQTT connection!
Tue Jul 12 17:51:51 2022 (1728757): Reconnecting to mqtt server ...
Tue Jul 12 17:51:51 2022 (1728760): Heishamon stats: Uptime: 0 days 0 hours 28 minutes 48 seconds ## Free memory: 37% ## Heap fragmentation: 13% ## Max free block: 12984 bytes ## Free heap: 14824 bytes ## Wifi: 58% (RSSI: -71) ## Mqtt reconnects: 0 ## Correct data: 87.76%
Tue Jul 12 17:51:51 2022 (1728783): Requesting new panasonic data
Tue Jul 12 17:51:51 2022 (1728787): sent bytes: 111 including checksum value: 18 
Tue Jul 12 17:51:52 2022 (1729263): Received 203 bytes data
Tue Jul 12 17:51:52 2022 (1729264): Checksum and header received ok!
Tue Jul 12 17:51:52 2022 (1729267): received TOP9 DHW_Target_Temp: 47
Tue Jul 12 17:51:52 2022 (1729279): received TOP64 High_Pressure: 14.6

**Comment by IgorYbema** [comment]
Hmm I notice that except to the set command there are no regular checks for the new values, between:
Tue Jul 12 17:51:29 2022 (1706334): Checksum and header received ok!
Tue Jul 12 17:51:48 2022 (1725066): New webserver client: 192.168.16.113:45772

Normally each 5 secs it will request new values (settings: How often new values are collected from heatpump - default 5 sec)). Did you change that maybe?

After a set command the next read will not display the change directly. It needs another request to see the changed value. And that is why you only see it after the next change.  And therefore there is a normal 5 sec refresh of the data like this:
Tue Jul 12 18:19:44 2022 (8280534): Requesting new panasonic data

**Comment by Bogeyof** [comment]
You´re right, I changed it to 30 secs, cause my PHP-Skript read only once per minute. I changed it back to 5 secs.
But it has no positive effect. First param is changed, second not (even after 5 Minutes not, it´s not seen after next refresh, it´s never changed):

This time (with 5 secs), tried to set values 49 / 3. Before was 48 / 0. After sending 49 / 0 (after 5 minutes)...

Tue Jul 12 20:29:11 2022 (1597853): Lost MQTT connection!
Tue Jul 12 20:29:11 2022 (1597855): Heishamon stats: Uptime: 0 days 0 hours 26 minutes 37 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29160 bytes ## Wifi: 54% (RSSI: -73) ## Mqtt reconnects: 0 ## Correct data: 92.93%
Tue Jul 12 20:29:11 2022 (1597873): Requesting new panasonic data
Tue Jul 12 20:29:11 2022 (1597877): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:11 2022 (1598342): New webserver client: 192.168.77.223:32816
Tue Jul 12 20:29:11 2022 (1598344): Received 203 bytes data
Tue Jul 12 20:29:11 2022 (1598345): Checksum and header received ok!
Tue Jul 12 20:29:13 2022 (1600105): Closing webserver client: 192.168.77.223:32816
Tue Jul 12 20:29:16 2022 (1602854): Lost MQTT connection!
Tue Jul 12 20:29:16 2022 (1602856): Heishamon stats: Uptime: 0 days 0 hours 26 minutes 42 seconds ## Free memory: 73% ## Heap fragmentation: 12% ## Max free block: 25592 bytes ## Free heap: 29136 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 93.00%
Tue Jul 12 20:29:16 2022 (1602874): Requesting new panasonic data
Tue Jul 12 20:29:16 2022 (1602878): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:16 2022 (1603317): Received 203 bytes data
Tue Jul 12 20:29:16 2022 (1603318): Checksum and header received ok!
Tue Jul 12 20:29:21 2022 (1607855): Lost MQTT connection!
Tue Jul 12 20:29:21 2022 (1607857): Heishamon stats: Uptime: 0 days 0 hours 26 minutes 47 seconds ## Free memory: 73% ## Heap fragmentation: 12% ## Max free block: 25592 bytes ## Free heap: 29152 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 93.07%
Tue Jul 12 20:29:21 2022 (1607875): Requesting new panasonic data
Tue Jul 12 20:29:21 2022 (1607879): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:21 2022 (1608294): Received 203 bytes data
Tue Jul 12 20:29:21 2022 (1608294): Checksum and header received ok!
Tue Jul 12 20:29:24 2022 (1611374): New webserver client: 192.168.16.113:46232
Tue Jul 12 20:29:24 2022 (1611382): set DHW temperature to 49
Tue Jul 12 20:29:24 2022 (1611382): sent bytes: 111 including checksum value: 225 
Tue Jul 12 20:29:24 2022 (1611385): set Quiet mode to 3
Tue Jul 12 20:29:24 2022 (1611389): Already sending data. Buffering this send request
Tue Jul 12 20:29:24 2022 (1611424): Closing webserver client: 192.168.16.113:46232
Tue Jul 12 20:29:25 2022 (1611806): Received 203 bytes data
Tue Jul 12 20:29:25 2022 (1611807): Checksum and header received ok!
Tue Jul 12 20:29:25 2022 (1611825): Sending command from buffer
Tue Jul 12 20:29:25 2022 (1611826): sent bytes: 111 including checksum value: 114 
Tue Jul 12 20:29:26 2022 (1612856): Lost MQTT connection!
Tue Jul 12 20:29:26 2022 (1612858): Heishamon stats: Uptime: 0 days 0 hours 26 minutes 52 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29160 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 93.20%
Tue Jul 12 20:29:26 2022 (1612876): Requesting new panasonic data
Tue Jul 12 20:29:26 2022 (1612880): Already sending data. Buffering this send request
Tue Jul 12 20:29:27 2022 (1613829): Previous read data attempt failed due to timeout!
Tue Jul 12 20:29:27 2022 (1613829): Received 0 bytes data
Tue Jul 12 20:29:27 2022 (1613831): Sending command from buffer
Tue Jul 12 20:29:27 2022 (1613837): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:27 2022 (1614246): Received 203 bytes data
Tue Jul 12 20:29:27 2022 (1614246): Checksum and header received ok!
Tue Jul 12 20:29:27 2022 (1614249): received TOP9 DHW_Target_Temp: 49
Tue Jul 12 20:29:31 2022 (1617857): Lost MQTT connection!
Tue Jul 12 20:29:31 2022 (1617859): Heishamon stats: Uptime: 0 days 0 hours 26 minutes 57 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29216 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 92.38%
Tue Jul 12 20:29:31 2022 (1617877): Requesting new panasonic data
Tue Jul 12 20:29:31 2022 (1617881): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:31 2022 (1618344): Received 203 bytes data
Tue Jul 12 20:29:31 2022 (1618345): Checksum and header received ok!
Tue Jul 12 20:29:36 2022 (1622791): New webserver client: 192.168.77.20:60333
Tue Jul 12 20:29:36 2022 (1622879): Lost MQTT connection!
Tue Jul 12 20:29:36 2022 (1622880): Reconnecting to mqtt server ...
Tue Jul 12 20:29:36 2022 (1622882): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 2 seconds ## Free memory: 60% ## Heap fragmentation: 3% ## Max free block: 23648 bytes ## Free heap: 24200 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 92.45%
Tue Jul 12 20:29:36 2022 (1622905): Requesting new panasonic data
Tue Jul 12 20:29:36 2022 (1622909): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:36 2022 (1623373): Received 203 bytes data
Tue Jul 12 20:29:36 2022 (1623374): Checksum and header received ok!
Tue Jul 12 20:29:37 2022 (1624172): Closing webserver client: 192.168.77.20:60333
Tue Jul 12 20:29:41 2022 (1627880): Lost MQTT connection!
Tue Jul 12 20:29:41 2022 (1627882): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 7 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29328 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 92.52%
Tue Jul 12 20:29:41 2022 (1627900): Requesting new panasonic data
Tue Jul 12 20:29:41 2022 (1627904): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:41 2022 (1628296): Received 203 bytes data
Tue Jul 12 20:29:41 2022 (1628297): Checksum and header received ok!
Tue Jul 12 20:29:46 2022 (1632881): Lost MQTT connection!
Tue Jul 12 20:29:46 2022 (1632883): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 12 seconds ## Free memory: 74% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29496 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 92.59%
Tue Jul 12 20:29:46 2022 (1632901): Requesting new panasonic data
Tue Jul 12 20:29:46 2022 (1632905): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:46 2022 (1633370): Received 203 bytes data
Tue Jul 12 20:29:46 2022 (1633371): Checksum and header received ok!
Tue Jul 12 20:29:51 2022 (1637882): Lost MQTT connection!
Tue Jul 12 20:29:51 2022 (1637884): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 17 seconds ## Free memory: 74% ## Heap fragmentation: 14% ## Max free block: 25592 bytes ## Free heap: 29520 bytes ## Wifi: 58% (RSSI: -71) ## Mqtt reconnects: 0 ## Correct data: 92.66%
Tue Jul 12 20:29:51 2022 (1637902): Requesting new panasonic data
Tue Jul 12 20:29:51 2022 (1637906): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:51 2022 (1638347): Received 203 bytes data
Tue Jul 12 20:29:51 2022 (1638348): Checksum and header received ok!
Tue Jul 12 20:29:56 2022 (1642883): Lost MQTT connection!
Tue Jul 12 20:29:56 2022 (1642885): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 22 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29408 bytes ## Wifi: 58% (RSSI: -71) ## Mqtt reconnects: 0 ## Correct data: 92.73%
Tue Jul 12 20:29:56 2022 (1642903): Requesting new panasonic data
Tue Jul 12 20:29:56 2022 (1642907): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:29:56 2022 (1643323): Received 203 bytes data
Tue Jul 12 20:29:56 2022 (1643324): Checksum and header received ok!
Tue Jul 12 20:30:01 2022 (1647884): Lost MQTT connection!
Tue Jul 12 20:30:01 2022 (1647886): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 27 seconds ## Free memory: 74% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29496 bytes ## Wifi: 58% (RSSI: -71) ## Mqtt reconnects: 0 ## Correct data: 92.79%
Tue Jul 12 20:30:01 2022 (1647904): Requesting new panasonic data
Tue Jul 12 20:30:01 2022 (1647908): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:30:01 2022 (1648300): Received 203 bytes data
Tue Jul 12 20:30:01 2022 (1648300): Checksum and header received ok!
Tue Jul 12 20:30:06 2022 (1652885): Lost MQTT connection!
Tue Jul 12 20:30:06 2022 (1652885): Reconnecting to mqtt server ...
Tue Jul 12 20:30:06 2022 (1652888): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 32 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29408 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 92.86%
Tue Jul 12 20:30:06 2022 (1652911): Requesting new panasonic data
Tue Jul 12 20:30:06 2022 (1652915): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:30:06 2022 (1653373): Received 203 bytes data
Tue Jul 12 20:30:06 2022 (1653374): Checksum and header received ok!
Tue Jul 12 20:30:07 2022 (1654215): New webserver client: 192.168.77.20:60349
Tue Jul 12 20:30:09 2022 (1655730): Closing webserver client: 192.168.77.20:60349
Tue Jul 12 20:30:11 2022 (1657886): Lost MQTT connection!
Tue Jul 12 20:30:11 2022 (1657888): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 37 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29328 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 92.92%
Tue Jul 12 20:30:11 2022 (1657906): Requesting new panasonic data
Tue Jul 12 20:30:11 2022 (1657910): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:30:11 2022 (1658350): Received 203 bytes data
Tue Jul 12 20:30:11 2022 (1658351): Checksum and header received ok!
Tue Jul 12 20:30:13 2022 (1660300): New webserver client: 192.168.77.223:33008
Tue Jul 12 20:30:15 2022 (1662094): Closing webserver client: (IP unset):0
Tue Jul 12 20:30:16 2022 (1662887): Lost MQTT connection!
Tue Jul 12 20:30:16 2022 (1662889): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 42 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29328 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 92.98%
Tue Jul 12 20:30:16 2022 (1662907): Requesting new panasonic data
Tue Jul 12 20:30:16 2022 (1662911): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:30:16 2022 (1663326): Received 203 bytes data
Tue Jul 12 20:30:16 2022 (1663327): Checksum and header received ok!
Tue Jul 12 20:30:21 2022 (1667888): Lost MQTT connection!
Tue Jul 12 20:30:21 2022 (1667891): Heishamon stats: Uptime: 0 days 0 hours 27 minutes 47 seconds ## Free memory: 73% ## Heap fragmentation: 13% ## Max free block: 25592 bytes ## Free heap: 29328 bytes ## Wifi: 56% (RSSI: -72) ## Mqtt reconnects: 0 ## Correct data: 93.04%
Tue Jul 12 20:30:21 2022 (1667908): Requesting new panasonic data
Tue Jul 12 20:30:21 2022 (1667913): sent bytes: 111 including checksum value: 18 
Tue Jul 12 20:30:21 2022 (1668303): Received 203 bytes data
Tue Jul 12 20:30:21 2022 (1668304): Checksum and header received ok!

**Comment by Bogeyof** [comment]
I would say thank you for your commitment, but I think it´s also ok for me to send settings one by one. If sending multiple settings is a problem (may be just for me), I change my skripts to send them one by one. It´s not a big deal. 

Let's call it a day... Many thanks!

**Comment by IgorYbema** [comment]
Ok. I see that the 2nd set was failing. It didn't receive an acknowledge.
Not sure why. I do see a low wifi connection and that is often a cause of some errors (your correct data is a bit low 93%). Also maybe it is not liking the missing mqtt also (it keeps trying to connecting to nothing :)).
But normally (with good connection) it should work.

Best to implement a set and check routine in your scripts. Because data can be missed. So if you set DHW=49, wait for example 30 secs, and then check if the DHW is indeed 49. If not, set again. Alsof for other values.
