### ISSUE TITLE
no values

### ISSUE THREAD

**Issue by nevusZ** [heishamon/HeishaMon#262]
Hello,
heishamon does not show any values anymore.
It was working when I firstly installed the device.
I tried to restart the heishamon and also tried to unplug/replug the cable from heishamon but it did no help.
Any idea why I cannot see any values?
Should i completely interrupt power of the heatpump? 
at the moment version 2.0a is installed, is an upgrade to version 3 a good idea?
thank you

**Comment by IgorYbema** [comment]
You could try v3 but I don't think it helps to resolve your problem.
Is your wifi connection too low? (at least 70% is preferred). With a low wifi the heishamon takes too much time to process wifi connection and has no time to do the heatpump connection.
Or did you put the heishamon on listen only mode by accident? This is only used if you have a cz-taw1 running parallel.

**Comment by nevusZ** [comment]
Hy,
unchecked "listen only mode" and values are here now! THANK you

**Comment by IgorYbema** [comment]
Great! Can you close this issue?
