### ISSUE TITLE
Cannot import Json in Node Red

### ISSUE THREAD

**Issue by MikeyMan83** [heishamon/HeishaMon#264]
Hi!

Trying to import the json into NodeRed on my Pi for Domoticz, i get the following error:
![image](https://user-images.githubusercontent.com/6270724/186608818-41a64b0a-f1c8-4111-8cce-4b7fee09492c.png)

I have installed influxdb as per the readme as well. Any thoughts?

**Comment by IgorYbema** [comment]
You need to install the influx components into nodered also

**Comment by MikeyMan83** [comment]
I did, although readme says its optional:

```
Prerequisite:

Domoticz with mqtt setup
node-red with mosquitto (optionally with https://flows.nodered.org/node/node-red-contrib-influxdb installed)
Working PCB with Heishamon firmware installed
```
Followed the link and executed the following command:
`sudo npm install node-red-contrib-influxdb`

result is:
![image](https://user-images.githubusercontent.com/6270724/186611492-a82b76f2-0773-48e7-b9e0-8aeea8aa1be4.png)



also added panasonic db:

![image](https://user-images.githubusercontent.com/6270724/186611329-234ed938-fd61-48f1-8cb2-243da4c7bbde.png)

**Comment by IgorYbema** [comment]
Do you see the influx components in the left menu bar in nodered? Maybe they changed name a bit with newer versions

**Comment by MikeyMan83** [comment]
i see these:

![image](https://user-images.githubusercontent.com/6270724/186621208-95095aa7-66be-411d-841a-7170a355e3c1.png)

**Comment by IgorYbema** [comment]
Not sure what is wrong. Think something with new version. Can you check in nodered forums?

**Comment by MikeyMan83** [comment]
> Not sure what is wrong. Think something with new version. Can you check in nodered

Really dont know what to ask for, havent found any examples of this specific error tbh

**Comment by MikeyMan83** [comment]
Did get this fixed through help on nodered forum.

Something was wrong with the install. Reinstalled without sudo. 

now getting another error though...
![image](https://user-images.githubusercontent.com/6270724/186739923-4a7295c7-653c-4a18-9432-60072d5f8805.png)

Got the feeling someting is still not in order.

![image](https://user-images.githubusercontent.com/6270724/186739817-18bbeaf8-245b-419e-99ca-3580f67581ee.png)

**Comment by IgorYbema** [comment]
This flow is really old. Needs some updates but I don't remember who created it :)

**Comment by MikeyMan83** [comment]
Oh ok... that doesn't help...

Its an issue with the json it seems, although similar flows give the same error:

![image](https://user-images.githubusercontent.com/6270724/186744392-410309fd-0d16-48f7-847b-0cdfa60a626d.png)

**Comment by MikeyMan83** [comment]
@IgorYbema any way you could have a look maybe? I'm not good with code :(
