### ISSUE TITLE
change of mqtt sensors in homeassistant 2022.12.0

### ISSUE THREAD

**Issue by HerbyR56** [heishamon/HeishaMon#269]
I get a warning in homeassistant that manual configured mqtt sensors have a changed format. 
See https://www.home-assistant.io/integrations/sensor.mqtt/#new_format.
**old:**
 sensor:
  - platform: mqtt 

**new:**
mqtt:
  sensor:

I started to change the heishamon.yaml, but I'm not successfull with it. I got the error the the mqtt platforn cannot get merged. Can you support me in changing that yaml file, so it's running with the new versions of homeassistant?

**Comment by geduxas** [comment]
Update your yaml, check in repository, couple days it have been updated

**Comment by HerbyR56** [comment]
oh yes, I see you have already updated the yaml file, I will check it in my installation.

**Comment by HerbyR56** [comment]
It works, I have only added the Topic 36 and Topic 93, which I found additional interesting
