### ISSUE TITLE
Feature request: Provide MQTT command for Set_Heat_State

### ISSUE THREAD

**Issue by str3000** [heishamon/HeishaMon#270]
Hello,
I'm using SetForceDHW and it works well. I use it together with the sg-ready signals, because I have a solar roof.
The command SetForceHeater is missing.

Now the winter season is coming and I want to use the overage power from the solar panels.
I see that a parameter exist with the name:  "main/Force_Heater_State"

Is there any possibility to set heater force also ?

**Comment by MiG-41** [comment]
Heater mode is somehow used as emergency mode ,when compressor fail ( and there is also option in HP to set it in this mode automatically).
This Mode can be nly turn on ,when HP is off , and when you turn on HP it disapear.
Till now no one ask to use HP in Heater mode...

**Comment by str3000** [comment]
Your right,
my mistake. I will manually control the Heat mode. controlling DHW works fine with sg-ready.
But I can‘t find a way to switch Heat Pump for Heat/Room on.
I try a lot of parameter today, but no one starts heat pump.
I test with sg-ready, max power 90 min, bigger base temp
Any Idea?
Also I missing a flag if heat pump is running or not.
only indirect over power consumption.

**Comment by MiG-41** [comment]
Ok , so you have CZ-NS4P , and you are using two Digital Imputs ?
Or you are doing this via Heishamon and Optional PCB Emulation ?
Anyway , HP starts heat ,when there is some requirements meet. One of them is ,that target temperature have to be higher then actual inlet temperature , and (especially at low temperatures on heatflor ) it is hard to set , becouse this difference have to be 3 or 4 degrees. Setting SG changes this target temperatures by multipling setted value.   
When HP is not starting , first thing what you do is comparing target with inlet :)

**Comment by str3000** [comment]
Hello yes,
I have installed the option board.
good tip with the inlet temp, I will check it.
sg signals are hardware wires.
(in future i will add power control wires 0-10V)

perhaps  Heating_Off_Outdoor_Temp
may be a problem if its sunny.

possible parameter to test:
- inlet /target
- SetPowerfulMode
- SetZ1HeatRequestTemperature
