### ISSUE TITLE
V3 serial interface issues

### ISSUE THREAD

**Issue by geduxas** [heishamon/HeishaMon#271]
I have noticed strange issue with V3. 
Sometimes it's seams Panasonic is locking out from serial communication. I have 2 random issues for now, and both are after rebooting heishamon.
I have V3 PCB, , i think i am using heishamon from v1, and didn't have any issues with it. Couple days ago tried S0 settings, and rebooted heishamon from menu, after that communication with heat pump gone, from console log i got only records about reading timeout, after that tried reboot couple times, also tried factory reset and downgrade firmware (v2, v1) nothing helped. After i came home and power cycled whole heat pump unit, communication have been back. After that tried to reboot heishamon couple of times, and couldn't reproduce.. but yesterday just by accident pushed reboot button in menu, and again,  got read timeout.. 
I have 12kW T-CAP h series model, with additional extension card.

**Comment by IgorYbema** [comment]
Do you have CZ-TAW1 in parallel (so heishamon should be in listen only mode)?
Or did you by accident turn on the optional pcb emulation mode? (as you have the extra board already you should not do this)

**Comment by geduxas** [comment]
No I don't, didn't touch emulation, and Don't have cz-taw1. Panasonic just stopped responding after restarting heishamon.. i have also tried physically disconnect heishamon while that happened..

**Comment by IgorYbema** [comment]
Heatpump still works and the panasonic controller also? Or do they stop also? This would be a new one for me then.

**Comment by geduxas** [comment]
Everything seams works fine, truly didn't noticed that, latest issue i noticed after 9h, and dhw didn't cool down..

**Comment by geduxas** [comment]
Oh yes! LCD kept responsive, i switch unit off and then i have disconnect circuit breaker

**Comment by IgorYbema** [comment]
So everything on Panasonic works fine but heishamon not and you need to turn off and on the Panasonic to fix heishamon again. Weird.

**Comment by geduxas** [comment]
It's happened again! I tried reboot 3 times, nothing happened, and in forth time i went in to settings menu, saved configuration, and after that hit reboot.

![Screenshot_2022-09-11-19-40-37-70_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/18700450/189539180-426fb73a-748c-43a9-a446-4ab6c946f57f.jpg)

**Comment by IgorYbema** [comment]
Can't understand why. If a hard reset of the heatpump is necessary to fix this it looks like an issue on the heatpump side. But proper debugging is hard for this

**Comment by geduxas** [comment]
I am running heishamon >2y, didn't have any issues till this thursday. 

It's seams that Panasonic lookups serial interface on reboot.. and yes only hard reset of pump solves problem

**Comment by IgorYbema** [comment]
Older heishamons can have easier comms problems than the most recent design (electrical design difference on the board). Maybe you are on an edge case and due to other external reason (extra noise?) it is now only visible.
If you can reproduce it often and it really bothers you, I can send you a new one and check if it works better with the new design. At least if you got the heishamon from me (the tindie shop), then what was your order number?

**Comment by geduxas** [comment]
Yes, bought cable + board. Rebooted once again without changing anything, and it's lost comuncation again..

**Comment by geduxas** [comment]
Found order no in email

Tindie Order [#207935]
Aug. 5, 2020, 1:37 p.m.

Also i think I'll try downloading to v2 and try

**Comment by IgorYbema** [comment]
Ok just let me know if you want me to send you a new one to test

**Comment by geduxas** [comment]
Downgraded to v2, after factory reset and connect to wifi phone finds strange AP.. and it's dissapperes then i disconnect heishamon.. hashemon seams works fine.. do i need somhow special clean procedures of esp?

![Screenshot_2022-09-11-20-52-15-86_41a74ddf68be21faad2fbbb691b15143](https://user-images.githubusercontent.com/18700450/189541987-cda36662-ed76-43ee-85af-ff4c303616cc.jpg)

**Comment by IgorYbema** [comment]
Do you have special wifi characters in your ssid or password? Seeing this with others also. A upgrade to V3 solves it. But try factory reset please. Double click on reset with 0.5 sec pause until blue led goes in steady on/off. Then reset again to start

**Comment by geduxas** [comment]
Nothing special..  ok I'll stick to v2 for couple days, now reboot'ed 4 times no issues with serial.

**Comment by MiG-41** [comment]
> I have 12kW T-CAP h series model, with additional extension card.

I belive her is the key , that there is CZ-NS4P in beetwen HP and Heishamon.
@geduxas ,by accident did you have enabled "Emulate optional PCB" ?

Probably it is hard to power cycle only the NS4P to see, if that brings up connection...

**Comment by geduxas** [comment]
No I didn't enable emulation. With V2 seams no issues after reboot, will continue to test.

**Comment by geduxas** [comment]
@IgorYbema still no issues with V2... could it be related to V3? or it could be board issues?

**Comment by mabek** [comment]
I also have heavy issues with V3 but its hard to specify. 
Overall the UI seems slow. Sometimes values do not update at all. Without factory reset no values were shown. So I think I will go back to V2 as well.

**Comment by geduxas** [comment]
> I also have heavy issues with V3 but its hard to specify. Overall the UI seems slow. Sometimes values do not update at all. Without factory reset no values were shown. So I think I will go back to V2 as well.

on my case interface works ok, just after reboot panasonic lock out from serial communication.. 

maybe you have Wifi issues? do you get good reception?

**Comment by mabek** [comment]
> > I also have heavy issues with V3 but its hard to specify. Overall the UI seems slow. Sometimes values do not update at all. Without factory reset no values were shown. So I think I will go back to V2 as well.
> 
> on my case interface works ok, just after reboot panasonic lock out from serial communication..
> 
> maybe you have Wifi issues? do you get good reception?

Wifi is at 100%. Can you describe what you mean with "reboot panasonic lock out from serial communication" ?

**Comment by geduxas** [comment]
> > > I also have heavy issues with V3 but its hard to specify. Overall the UI seems slow. Sometimes values do not update at all. Without factory reset no values were shown. So I think I will go back to V2 as well.
> > 
> > 
> > on my case interface works ok, just after reboot panasonic lock out from serial communication..
> > maybe you have Wifi issues? do you get good reception?
> 
> Wifi is at 100%. Can you describe what you mean with "reboot panasonic lock out from serial communication" ?

After rebooting heishamon, Panasonic heatpump stops responding to request. Disconnect heishamon Don't help.. i needed to powercycle whole heatpump unit..

**Comment by mabek** [comment]
> > > > I also have heavy issues with V3 but its hard to specify. Overall the UI seems slow. Sometimes values do not update at all. Without factory reset no values were shown. So I think I will go back to V2 as well.
> > > 
> > > 
> > > on my case interface works ok, just after reboot panasonic lock out from serial communication..
> > > maybe you have Wifi issues? do you get good reception?
> > 
> > 
> > Wifi is at 100%. Can you describe what you mean with "reboot panasonic lock out from serial communication" ?
> 
> After rebooting heishamon, Panasonic heatpump stops responding to request. Disconnect heishamon Don't help.. i needed to powercycle whole heatpump unit..

Thank you! After turning the power off and on again now it is as follows:

MQTT Topics working again except Heat_Energy_Production which is now always 0
Webinterface does not show any values on the main page. 1-Wire and s0 works
Webinterface still 2-3x slower than with v2

**Comment by mabek** [comment]
I went back to V2 and now all my Issues are gone. Hopefully someone finds a fix for a V3.1

**Comment by drschrick12** [comment]
Dears, I’ve exactly the same issue.
My board is v3 PCB and only firmware v2 is function correctly.

In firmware v3 the webinterface is very laggy and slow and over mqtt it shows online and short time later offline and then again online.

Tindie order #192596 from May 2nd, 2020.

Thank you.

**Comment by geduxas** [comment]
> Dears, I’ve exactly the same issue. My board is v3 PCB and only firmware v2 is function correctly.
> 
> In firmware v3 the webinterface is very laggy and slow and over mqtt it shows online and short time later offline and then again online.
> 
> Tindie order #192596 from May 2nd, 2020.
> 
> Thank you.

How strong is your wifi? What numbers do you see in heishamon?

**Comment by drschrick12** [comment]
My wifi is between 94-86% and firmware v2 runs perfect.
<img width="341" alt="Bildschirm­foto 2022-12-04 um 08 50 54" src="https://user-images.githubusercontent.com/103568498/205480133-b14f50f3-5882-45d7-8aa5-5cf5726903a4.png">

With Firmware v3 is laggy and I don´t know why

**Comment by geduxas** [comment]
I am here again.. everything seams to work great for couple of months. Today after couple reboots heishamon stucked again. 

Mon Dec 12 10:54:22 2022 (1428540): Heishamon stats: Uptime: 0 days 0 hours 23 minutes 48 seconds ## Free memory: 70% ## Heap fragmentation: 23% ## Max free block: 21112 bytes ## Free heap: 28016 bytes ## Wifi: 92% (RSSI: -54) ## Mqtt reconnects: 1 ## Correct data: 0.00%
Mon Dec 12 10:54:22 2022 (1428544): Requesting new panasonic data
Mon Dec 12 10:54:22 2022 (1428544): sent bytes: 111 including checksum value: 18 
Mon Dec 12 10:54:24 2022 (1430547): Previous read data attempt failed due to timeout!
Mon Dec 12 10:54:24 2022 (1430547): Received 0 bytes data
