### ISSUE TITLE
Set command for TOP106 Pump_Flowrate_Mode

### ISSUE THREAD

**Issue by SuperPino64** [heishamon/HeishaMon#278]
Hi, is there a set command for TOP106 Pump_Flowrate_Mode?
I can't find it on the list.

**Comment by IgorYbema** [comment]
There isn't a set command yet as there isn't anyone who asked for it :) It is not something you would like to set from automation I think. But if you really want it (I can't test it, don't have J series) please test if it works.
There is a SendRawValue option which you can use to change every setting you like. For TOP106 you need to switch bit 3 and bit 4  from (binary) 01 to (binary) 10 and vice versa on byte address 29.

There is a linux command you can use. Change the 30th (byte 29) value from \x10 to \x20 and it should change it and vice versa.

`echo -ne "\xf1\x6c\x01\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" | mosquitto_pub -t "panasonic_heat_pump/SendRawValue" -s`

**Comment by MiG-41** [comment]
@boutermw ,can you explain why you need this SetCommand ?
For me such mode is set once , and no need to change remontly , especially when the HP is running.... Or am i wrong ?
It is possible to add as many setcommands as possible , but they have to be usefull  ,not just to be becouse you can.... (hope you know what i mean). I.e. you don't need a SetCommand with sets configuration with DHW on  or off. DHW either exitst and you turn it on on configuration once , or not exist and also once is off....

**Comment by bluberly** [comment]
Would it technically be possible to change the pump flow rate while the heatpump is running? On the remote control it only is possible when the heatpump is off. Yes, it would be very helpful to have the ability to change it, especially in the first time after installation: control the noise different flow rates cause in the water system in the house, observe impact on efficiency.

OT: Can the heat curves be changed? How did Panasonic implement the week timers? It's so annoying they cannot be managed remotely...
Is there a mailing list to discuss such topics? Or is the issue tracker the right way?

**Comment by IgorYbema** [comment]
Yes you can change it while running but it seems not to work always.
Heat curves can be changed using the setcurves (json payload) command, see readme in github. In the readme (top) you can find a link to the slack chat channel for discussions.

**Comment by hacki11** [comment]
I came around also asking for this feature.
When outside temperature is getting higher (> 10°C) and the modulation gets down to 19Hz flow will also get down to 10l/min which is too less to get the heat out of the heat pump. My idea is to configure the flow mode to maximum for temperatures over 10°C dynamically. Currently I use SetPump = 1 but idk if it will make a difference. 
Edit: Using SetPump, it is not possible to check wether it is active or not because one can not distinguish between the heatpump is maxing the pump because of internal rule or one set it from outside. In both cases max_duty will be the current duty. While using the flow mode setting it can be clearly distinguished what mode is active.

**Comment by MiG-41** [comment]
Unfortunalty HP adjust flow to its on forumla....
You can try to decrease delta , that is also one of factor.

Adusting Maximum flow speed via SetMaxPumpDuty (or in menu) will set only maximum , and HP still can have lower values.
And what is for you active ? When compressor is running , or when water pump is running ? ( Can be situation like this as well ,that compressor not run , but water pump runs , and also Heaters are on).

**Comment by hacki11** [comment]
With active I mean, after setting SetPump to 1 (forcing to run at maxpumpduty) I can not afterwards read out if SetPump was set to 1 or 0 as there is no state available to read that out. This will make external control difficult. 
What i want to achieve is having delta T Mode in Case of t<10°C and fix speed at t>=10°C. I want the HP to run in longer intervals but only one or two a day and the low flow rate will cause a stop as the lower Modulation is too high starting from this temperature.

You are right, decreasing the delta should cause the same result. I will definitely try that.

**Comment by MiG-41** [comment]
Please don't use SetPump when HP works !
This function is rather to check ,if water pump work ( same puropse ,like in installer menu). 

You can check how SetPump works , when you turn off HP ( no green LED) , and then SetPump=1 , o to controller and see what is on display !
SetPump  is somehow service feature , and i'm surprised ,that HP allows to use it turing their normal work....
@IgorYbema do you remember whatfor this SetPump is implemented ? Somehow can be used not in proper way , lkie here...

**Comment by hacki11** [comment]
Oh, why is that? I was using it quite a while now during operation, ups.
I used it in case the heat pump didn't turn up the pump to a higher level during the start at higher outside temps. This leads to shutdowns 3 minutes after the start. Turning up the pump for a few minutes with SetPump did the trick.

**Comment by MiG-41** [comment]
To be honset , don't know ,if in this way you can drive flow manualy , or if HP ,its alghoritms will try to change flow anyway...

**Comment by MiG-41** [comment]
Anyway , in your automation you can compare Pump_Duty TOP93 with Max_Pump_Duty TOP95.... if TOP93 is lower then TOP95 that means ,that SetPump for sure not work...

**Comment by hacki11** [comment]
Yeah, I thought so, too but you can't. You can not distinguish between the case where you SetPump to 1 and the case where the HP is using it at max. In both cases pump_duty is max_duty.

Yes you can see if SetPump = 0 only if it is currently not at max. But I need the other cases, too.

You can drive the flow that way, the HP will not override the setting.

**Comment by geduxas** [comment]
HP drives pump to keep ∆t. Yes in warm times it's pain in ... To keep pump working in efficient way... I spent whole autumn trying to graph and analyse what could i change.. but without success.. if you m find best recipe for that please share :)

**Comment by MiG-41** [comment]
@hacki11 ,perhaps @IgorYbema could add a TOP for you , but in meantime you have panasonic_heat_pump/raw/data topic in mqtt , from witch you could try to get out bit 4 and 5 from byte 4 ,and you have SetPump state....

**Comment by bluberly** [comment]
Hmm, my Jeisha does not reduce pump flow rate at high outside temperatures. Outlet temperature in my config is d-t controlled. My pump flow at 2400rpm is around 19.11 l/min.

What is extremely annoying for me is though I meanwhile have delta-t set to 1° for heating (was 2° and 3° before) after the heatpump turned off it doesn't turn on even when outlet/inlet temperatures is 4.5°-5° below target outlet temperature, even after many hours? Is that something I can influence?

**Comment by hacki11** [comment]
With delta-t @ 1K i doubt you will see a ramp down of the pump, for that you need to increase dT to 3K or 4K
Mine is ramping down from 16l/min (at max) to 9,8l/min (at min) with dT 5K.

This is the condition to turn it on again. It will be calculated based on the inlet temperature at the time when the heatpump turned off. Some people also say it is not -3K but -4 or -5K. Depending on the required heat, it could be that it will never start again. If you have a inlet temp of 25°C and you need to wait until it gets 21°C it would take pretty long i think. For such cases there are some custom solutions to do a little kickstart with heishamon rules.
![image](https://user-images.githubusercontent.com/15319906/228043390-7abe99dd-0319-4a3e-b852-bc647933745c.png)

@MiG-41 I will try decreasing dT as i already made the experience that then it will not ramp it down like @bluberly also mentioned. That should work and it is also what i want to achieve. Get more heat inside the system (lower dT) but keep the outlet temperature the same. Let's see how my hydraulics will do.

**Comment by MiG-41** [comment]
> @hacki11 ,perhaps @IgorYbema could add a TOP for you , but in meantime you have panasonic_heat_pump/raw/data topic in mqtt , from witch you could try to get out bit 4 and 5 from byte 4 ,and you have SetPump state....
 

Probably such topic exist in Service cloud , and it is called "SHP control" 
Can someone check , if entering to this menu trigger this graph ? 

And maybe somone know full nampe for shortcut SHP ?
