### ISSUE TITLE
Quick Question: Firmware update 2.0 -> 3.0 - Settings kept?

### ISSUE THREAD

**Issue by Donpepe23** [heishamon/HeishaMon#283]
Hi,

Have some issues with heishamon not / very slowy responding for a couple fo minutes / hours. It just happens from time to time and alos MQTT comannds not working anymore.   Wifi is stable (78%),  Data recieved correct around 95%.  I thought it might be a good idea to update from 2.0 to 3.0, but I am not at home at the moment... only VPN connection. 

Will Heishamon keep the settings after the update (wifi etc)? Or do I need to start the whole process from the scratch? 

Thanks

**Comment by geduxas** [comment]
I have updated, nothing lost.. also downgraded.

**Comment by Donpepe23** [comment]
Hi,

worked... perfect... 

So far no problems with "no/slow response" from heishamon. 

THX
