### ISSUE TITLE
Heatshift doesn't work with external thermostat

### ISSUE THREAD

**Issue by dudu2082** [heishamon/HeishaMon#287]
Hi guys. In last year I use heatshift if neccesery when HP was set by external temperature curves. 
In this year i decide to try external thermostat to control HP + those curves. So if thermostat is on then  HP control heating by heating curves. 
But now I can't use heatshift (-5 to +5 C) to correct this curves. 
I can  set curves by sending json format command to change curves in mqtt.
Can this one could be fix to use heatshift with external thermostat connected to HP?

**Comment by IgorYbema** [comment]
It doesn't work due to the heatpump not supporting it. You can see the same behaviour when you try to shit using the Panasonic controller

**Comment by dudu2082** [comment]
> It doesn't work due to the heatpump not supporting it. You can see the same behaviour when you try to shit using the Panasonic controller

On HP controller also I could't change it. So you 
have a right. I thought that could be done by HeishaMon in some "magic" way.

**Comment by IgorYbema** [comment]
You can ofcourse change the setpoint and create some kind of shift that way.

**Comment by MiG-41** [comment]
@dudu2082 ,  You can send your "shifted" curve via SetCurves command , and HP will imidietly react on it ( also during work).

**Comment by HighlyCompressedAir** [comment]
Unsupported by the heat pump, can't be implemented. Issue can be closed.
