### ISSUE TITLE
Can't get s0 to work

### ISSUE THREAD

**Issue by traptoo** [heishamon/HeishaMon#288]
I have two Heishamon devices installed on my system. An energy meter OR-WE-521 is connected to each device.

Unfortunately, I do not get any values displayed in Heishamon:

![image](https://user-images.githubusercontent.com/39379197/202673686-3ce3799e-ad5f-4ae1-a3c5-1f24c2ff49da.png)

The configuration in the settings looks like this:

![image](https://user-images.githubusercontent.com/39379197/202674273-7d9aef70-3078-47a9-b146-fe714567bdbf.png)

I have no experience with the s0 interface so far and maybe I have a general error in my thinking. Is it possible that a voltage source has to be connected in between?

**Comment by IgorYbema** [comment]
These default settings look ok for this module. Try to swap the cables left
and right

**Comment by traptoo** [comment]
That seems to be the right way. Console shows:

![image](https://user-images.githubusercontent.com/39379197/202690621-3ad8ad55-23fc-4ed9-b77d-d58fd3f3e314.png)

Do i have to wait for some time? Because there are yet no values in heishamon:

![image](https://user-images.githubusercontent.com/39379197/202690821-c67443f8-1be4-4ac3-b577-b066af95b8ec.png)

**Comment by IgorYbema** [comment]
You see that there are only bad pulses. The quality is not good enough or the pulse width is longer. Try to set max pulse higher (for example 200ms)

**Comment by traptoo** [comment]
Increasing the max pulse to 200ms leads to more bad pulses:

![image](https://user-images.githubusercontent.com/39379197/202704159-0475ee2e-8ad7-40ee-b256-e6600e577568.png)

**Comment by IgorYbema** [comment]
And making the minimum lower?
Clearly the quality is not good. What cables are you using for the connection?

**Comment by traptoo** [comment]
Also doesn't work :(

Cable is a H03 VVH-2F with a length of ~2.5m.

![image](https://user-images.githubusercontent.com/39379197/202716232-0db29902-a10b-47d8-9604-22b3f7d6c0d7.png)

**Comment by IgorYbema** [comment]
what happens if you just short the gnd and s0_1 (and gnd and s0_2) for short times? That should count as pulses also
