### ISSUE TITLE
Unusual state changes between on and offline

### ISSUE THREAD

**Issue by Messiam** [heishamon/HeishaMon#289]
Hello,
I'm currently checking my initial setup which is quite default. 

And I see some changes of "panasonic_heat_pump/LWT" which might be unusual.
It toggles between online and offline.
Is this normal? 

22.11.2022 21:56:05 
Offline
22.11.2022 21:55:57(-8.22 seconds) 
Online
22.11.2022 21:55:41(-15.77 seconds) 
Offline
22.11.2022 21:55:27(-14 seconds) 
Online
22.11.2022 21:55:27(-0.22 seconds) 
Online
22.11.2022 21:55:11(-15.78 seconds) 
Offline
22.11.2022 21:55:01(-9.76 seconds) 
Online
22.11.2022 21:54:57(-4.47 seconds) 
Online
22.11.2022 21:54:35(-21.78 seconds) 
Offline
22.11.2022 21:54:27(-8.22 seconds) 
Online
22.11.2022 21:54:17(-9.79 seconds) 
Offline
22.11.2022 21:54:06(-10.74 seconds) 
Online

**Comment by IgorYbema** [comment]
My first guess would be your wifi is not strong enough. Should be 70% for minimal good setup.

**Comment by Messiam** [comment]
Might be, Wifi signal is ~56 - 58%. The wifi hotspots are not very close. 

What is the LWT topic actually? 
The documentation just mentions "Online/Offline (automatically returns to Offline if connection with the HeishaMon lost)".

Is it the connection from Heishamon to Wifi or to the heatpump?

**Comment by IgorYbema** [comment]
It is a signal in mqtt to show the state of connection from heishamon to mqtt

**Comment by Messiam** [comment]
Ok. Thank you for explanation. 

I don't understand how Heishamon can set it to "offline" when there is no connection ;-) But this is probably the last state before update to mqtt is sent. Right?

**Comment by IgorYbema** [comment]
No the mqtt server sets this state as it has lost connection

**Comment by Messiam** [comment]
Ok, I need to learn about some mqtt basics I think. Thank you!

**Comment by IgorYbema** [comment]
https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/
