### ISSUE TITLE
Q: Fractional temperatures for inlet and outlet temperature?

### ISSUE THREAD

**Issue by bluberly** [heishamon/HeishaMon#290]
When enabling monitoring on the Panasonic Service Cloud, the heatpump's inlet and outlet temperatures are displayed as fractional degrees with a resolution of 0.25°C. The downloadable CSV files also has the fractional temperatures

Has someone tried to decrypt the data stream from the heatpump and tried to find out if the fractional temperatures can be provided as well in Heishamon?

**Comment by IgorYbema** [comment]
Hi,
Fractional data is calculated by the service cloud as a function of time. The data is send from the panasonic only in integers just like heishamon is receiving it.

**Comment by bluberly** [comment]
Thank you! So a fake accuracy :-) Closing the issue.

**Comment by geduxas** [comment]
> 

Here is for comparasion panasonic temperature vs dallas 1wire read out.. 

![image](https://user-images.githubusercontent.com/18700450/203774345-9bc4d18f-d129-479b-b79c-475768ece761.png)

i think thous temperature instabilities will be rounded in panasonic cloud..

**Comment by IgorYbema** [comment]
this is indeed a nice example. There where you see the integer change from 36 to 37 a few times per minute the service cloud calculates a fractional value.
