### ISSUE TITLE
Implementation request for byte 118 decoding (inlet and outlet quarter water temperature)

### ISSUE THREAD

**Issue by berhan77** [heishamon/HeishaMon#293]
Would someone please be so kind and implement the decoding of byte 118 in heishamon.

Byte 118 decrypt:
Inlet Water Temperature [°C]
1st, 2nd & 3rd bit
.00 b001
.25 b010
.50 b011
.75 b100

Outlet Water Temperature [°C]
4th, 5th & 6th bit
.00 b001
.25 b010
.50 b011
.75 b100

Best regards

**Comment by michalwoz** [comment]
Which models which generations supports that resolution?

**Comment by berhan77** [comment]
My model of heat pump is the splitunit WH-SDC0709J3E5 WH-UD07JE5 but I think all H and J series units have this resolution like using CZ-TAW1 module.

**Comment by IgorYbema** [comment]
Hi,
If this is true, thanks for finding this.
Until now we thought CZ-TAW1 didn't have this data and that the service center of panasonic is doing time calculation for the fractionals. Read also here: https://github.com/Egyras/HeishaMon/issues/290

It still doesn't explain the fast flipping of top5 and top6 during the rise of fall of the temperature when it is in between two intergers. See the graph in the mentioned issue.  But I'll investigate

Also, doesn't all temps in the service center have franctional values? This should mean that other fractionals should be in the data also.

And looking further now, byte 118 doesn't look logical from the location of the byte for this information.

**Comment by IgorYbema** [comment]
I created a branch of the code to test this. You can download the binary from here: https://github.com/IgorYbema/HeishaMon/actions/runs/3562932211

It is based on v3.0 and will only change the top5 and top6 to include this byte 118 info.

**Comment by IgorYbema** [comment]
Could be right:
![image](https://user-images.githubusercontent.com/20365971/204234515-67767308-6ab6-409e-b970-3485bafc5294.png)
At around 9:15 I installed the beta code and you see the fractional information added. It matches the flow of the dallas temp sensors correctly.
@berhan77  how did you find this? Can you also find the fractionals for other temp values?

**Comment by berhan77** [comment]
> It still doesn't explain the fast flipping of top5 and top6 during the rise of fall of the temperature when it is in between two intergers. See the graph in the mentioned issue. But I'll investigate

This is probably due to the resolution of the ADC, some temperatures are not displayed. For example, the values ​​24, 24.25, 24.75, 25, 25.5, 25.75, 26, 26.5, 26.75, 27.25 are displayed in the Aquarea Service Cloud, the values ​​24.50, 25.25, 26.25, 27 are missing. I installed a thermal activation of building structures with very stable water temperatures and very precise external sensors, so I can understand the behavior of byte 118 very well.

I installed the alpha firmware, it works and correlates with the external sensors, thanks.
![image](https://user-images.githubusercontent.com/96003729/204235764-e75f80c4-b72c-4f0e-bf5a-5740c3810624.png)

**Comment by berhan77** [comment]
> @berhan77 how did you find this? Can you also find the fractionals for other temp values?

My heat pump works with a very low dT, but the power control still works with slight temperature jumps. So, I recorded the hexdump over a longer period and compared it with temperature changes. Only byte 118 changed. Decoding was then relatively easy.

**Comment by SuperPino64** [comment]
Thanks for this information! When do you think this will be merged in the main release?

**Comment by IgorYbema** [comment]
@boutermw see above, you can now use that test build

Main release will not happen soon I think. Need some more practical changes for me to have a reason for release a v3.1

**Comment by SuperPino64** [comment]
Thank you, I will use that test build.

**Comment by geduxas** [comment]
@IgorYbema, @boutermw do you have any tools for raw data monitoring or comparison?

**Comment by SuperPino64** [comment]
I've updated successfully to this test version, thanks. No I don't have those, but if it's not that difficult I'm willing to help out.

**Comment by berhan77** [comment]
> @IgorYbema, @boutermw do you have any tools for raw data monitoring or comparison?

I used Notepad++ and a small batch script for Windows.

:loop
echo %date%_%time% >> file.txt
curl http://192.168.0.240/debug >> file.txt
timeout /t 10
goto loop

**Comment by IgorYbema** [comment]
If you want to help, start reading https://github.com/IgorYbema/HeishaMon/blob/main/ProtocolByteDecrypt.md
Where the byte values aren't known yet we could have some help.

We believe that towards byte 117 there are only settings and from byte 118 and further there are the values. So you see that for example byte 119 and byte 120 are providing information which we still don't know what they do.

**Comment by MiG-41** [comment]
Yes, and also these bytes ,with were considered as 0 , in new versions Panasonic can implement something. I.e. there are some new data for gen. J ,not availble for order gen.H.

Good find @berhan77

**Comment by IgorYbema** [comment]
Hmm.. not sure if it is correct. For outlet I don't see any weird values but for inlet I see this:
![image](https://user-images.githubusercontent.com/20365971/204265261-8661ef03-f57d-47f5-b21a-4975e5ddd812.png)
It jumps from 26.75 to 26.25 and back a few times. Should be 26.50 then. Maybe we are close but doesn't look correct to me

**Comment by MiG-41** [comment]
Maybe wroga coded ,instead 0,25 you adding 0,75 ?

**Comment by IgorYbema** [comment]
> Maybe wroga coded ,instead 0,25 you adding 0,75 ?

No checked that

**Comment by MiG-41** [comment]
Maybe there is some mix ... 0.75 with 0.5 , or 0.25 with 0.5....
Try to cool down sensor and Look how it went thru up and dowm chang

**Comment by IgorYbema** [comment]
Yes, need to check.
Anyway, typical panasonic to use a 3 bits to represent 4 cases (.00, 0.25, 0.50 and 0.75) . Could be 2 bits :)

**Comment by SuperPino64** [comment]
Here some data since update:
[image](https://ibb.co/StJGWK4)

**Comment by berhan77** [comment]
No, it's the ADC, the accuracy (maybe 10bit) ist to low.

One more note, byte 175 correlates with the defrost status

**Comment by MiG-41** [comment]
Defrost status we have already in byte 111,  how this 175 behaves ?

**Comment by SuperPino64** [comment]
I also have 1-wire sensors on inlet and outlet for comparison:
[image](https://ibb.co/Lvs5NQ9)
here another when running water pump in service mode (last 5 minutes):
[image](https://ibb.co/1M2pm0f)

**Comment by berhan77** [comment]
> Defrost status we have already in byte 111, how this 175 behaves ?

It looks like a counter (from HEX 79 - 38)

**Comment by IgorYbema** [comment]
> Defrost status we have already in byte 111, how this 175 behaves ?

Could be this timer:
![image](https://user-images.githubusercontent.com/20365971/204269530-cd16672d-8616-4410-98a6-1598be971d33.png)

So when the timer hits HEX38 the defrost starts.

**Comment by IgorYbema** [comment]
But for this fractionals. Can someone now compare the values in this alpha release with the values in panasonic service center?

**Comment by berhan77** [comment]
It's the same in the cloud, I only get the following values ​​in the panasonic service center in the past with my heat pump.

19.25, 19.75, 20, 20.25, 20.75, 21, 21.5, 21.75, 22.25, 22.5, 22.75, 23, 23.25, 23.5, 23.75, 24, 24.25, 24.75, 25, 25.5, 25.75, 26, 26.5, 26.75, 27.25, 27.5, 28, 28.25, 28.75, 29, 29.5, 29.75, 30.25, 30.5, 31, 31.5, 31.75, 32.25, 32.5, 33, 33.25, 33.75, 34.25, 34.5, 35, 35.25, 35.75, 36.25, 36.5, 37, 37.5, 37.75, 38.25, 38.75, 39.25, 39.5, 40, 40.5, 41, 41.5, 41.75, 42.25, 42.75, 43.25, 43.75, 44.25, 44.75, 45.25, 45.75, 46.25, 46.75, 47.25, 47.75, 48.25, 48.75, 49.25, 49.75, 50.25, 51, 51.5, 52, 52.5, 53.25, 53.75, 54.5, 55, 55.5, 56.25
So far, the data looks very good.
![image](https://user-images.githubusercontent.com/96003729/204283159-da29d991-5917-4cba-a76e-f549cc7b20aa.png)

**Comment by IgorYbema** [comment]
Thanks. So also in service center it sometimes jumps 0.50 instead of only steps of 0.25. Than this looks ok now and you can close this issue. It will be added in main branch later.
I'm logging byte 175 for the defrost for another change later.

**Comment by MiG-41** [comment]
> It's the same in the cloud, I only get the following values ​​in the panasonic service center in the past with my heat pump.
> 
> 19.25, 19.75, 20, 20.25, 20.75, 21, 21.5, 21.75, 22.25, 22.5, 22.75, 23, 23.25, 23.5, 23.75, 24, 24.25, 24.75, 25, 25.5, 25.75, 26, 26.5, 26.75, 27.25, 27.5, 28, 28.25, 28.75, 29, 29.5, 29.75, 30.25, 30.5, 31, 31.5, 31.75, 32.25, 32.5, 33, 33.25, 33.75, 34.25, 34.5, 35, 35.25, 35.75, 36.25, 36.5, 37, 37.5, 37.75, 38.25, 38.75, 39.25, 39.5, 40, 40.5, 41, 41.5, 41.75, 42.25, 42.75, 43.25, 43.75, 44.25, 44.75, 45.25, 45.75, 46.25, 46.75, 47.25, 47.75, 48.25, 48.75, 49.25, 49.75, 50.25, 51, 51.5, 52, 52.5, 53.25, 53.75, 54.5, 55, 55.5, 56.25 So far, the data looks very good. ![image](https://user-images.githubusercontent.com/96003729/204283159-da29d991-5917-4cba-a76e-f549cc7b20aa.png)

I also cn confirm ,that from Heishamon i also not seen values like 27,75 28,5 29,25  .....
So if it is corresponding with service cloud then it is ok. ( i don't have service cloud to confirm it).

**Comment by bluberly** [comment]
Downloaded and installed the Alpha build and confirm it works and returns plausible values. Have kit WH-UD07JE5+WH-ADC0309J3E5C. Thanks a lot!

**Comment by SuperPino64** [comment]
Same here no problems on a WH-MDC07J3E5. Thank you.
