### ISSUE TITLE
HP not compatilbe

### ISSUE THREAD

**Issue by bigba7** [heishamon/HeishaMon#295]
Hi,

I bought new HeishaMon and connected it to my Wifi With no problem.
When I go to HeishaMon web server I don't see any information from my HP.
My model : 12kW mono block WH-MXC12J9E8
I connected HeishaMon , replaced my working CZ-TAW1
![hp_heisha](https://user-images.githubusercontent.com/29359606/205994897-f47ebfba-a3a9-43af-8dcd-d6a200ea0ea0.jpg)

Is there any chance to connect my HP?

**Comment by IgorYbema** [comment]
It should work. Can you post the console logging?

**Comment by bigba7** [comment]
Sure :-)
![hp_heisha2](https://user-images.githubusercontent.com/29359606/205995997-9d2eddb4-c5d5-4937-9f96-d8c21ecbe40d.jpg)

**Comment by IgorYbema** [comment]
Did you enable listen only mode? That works only/is only to be used if you still have the CZ-TAW1 connected

**Comment by bigba7** [comment]
I did it just for test when i notice that is not working.

**Comment by bigba7** [comment]
It works !!!
I disabled "listen only mode".
Thank you

**Comment by IgorYbema** [comment]
👍 and now close the issue 🙂

**Comment by bigba7** [comment]
I have another problem but not sure it is wright place here to look for solution of it.
I cant connect HeishaMon with my Homeassistant via MQTT
