### ISSUE TITLE
No rules function after reboot

### ISSUE THREAD

**Issue by JockelBln** [heishamon/HeishaMon#297]
It sometimes happens to me that HaishaMon apparently performs a reboot on its own. It works fine for a while and then suddenly the uptime in the web interface is reset again.
If that happens, no more rules will be executed afterwards.
The same thing happens when I manually reboot and then close the web interface before the reboot is complete.
The WiFi connection is very good and the data from the heat pump is also received without error.
![Unbenannt](https://user-images.githubusercontent.com/56645688/206144812-afbdb4d8-10a2-485c-958d-94a8c74c87c7.PNG)

I can not explain these independent reboots. So why aren't the rules restarted?
My HeishaMon is v4.6 and the firmware is version: 3.0.

Sorry English is not my first language, this is a google translation.

EDIT: The problem with a manual reboot cannot be reliably reproduced.

**Comment by geduxas** [comment]
If somehow a new valid ruleset crashes the HeishaMon, it will be automatically disabled the next reboot allowing you to make changes. This prevents the HeishaMon getting into a boot loop.

**Comment by JockelBln** [comment]
Thanks!
How can I identify which part of the rules caused the crash?
All entries are still visible under the menu item Rules and after pressing save they run again.
