### ISSUE TITLE
TOP111 and TOP112 reversed?

### ISSUE THREAD

**Issue by Bogeyof** [heishamon/HeishaMon#305]
I changed Z1 to Roomtemp. But it shows Z2 as Roomtemp and Z1 as Watertemp
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/33836983/210327987-2513360e-d6e3-47e0-86d3-698a978e5c81.png">

**Comment by IgorYbema** [comment]
You are right, seems to be wrong. I'll change that

**Comment by Bogeyof** [comment]
With latest Commit issue solved. Thanks!
