### ISSUE TITLE
Set S0 values

### ISSUE THREAD

**Issue by losiu900** [heishamon/HeishaMon#306]
Hi is it possible to change the value of S0 port?

**Comment by geduxas** [comment]
Heishamon will restore it's value from mqtt server.. so it's possible to change it

**Comment by losiu900** [comment]
So if I understand correctly, I need to power off Heishamon, update the value in mqtt serwer and power on heiosha?

**Comment by geduxas** [comment]
Yes it should get values from mqtt and use it
