### ISSUE TITLE
TOP 99 buffer control

### ISSUE THREAD

**Issue by Grufti68** [heishamon/HeishaMon#316]
Hello,

is there a possibility to control the TOP99 buffer?

**Comment by IgorYbema** [comment]
Not yet. Do you have a good use case for it?

**Comment by Grufti68** [comment]
I have a buffer memory with my Panasonic. if I start hot water production with the buffer deactivated, my heating pumps switch off. but if I activate the buffer then the pumps continue to run. I want to control it via IO-Broker

**Comment by MiG-41** [comment]
Buffer memory is simply buffer for extand water capacity ? (since memory is the word i don't understand in this context...)
Hot water production - DHW ,has nothing to deal with buffer , 3-way valve "connect" Heat Pump directly with DHW tank and therefore it is heating without buffer. Is your system coniguration is really ok ? Maybe you can pass some scheme of it ...

**Comment by geduxas** [comment]
@MiG-41  i think he talks about buffer tank and pumps after buffer tank with extension board.. or maybe 2 zones. Yes if buffer tank is enabled in DHW heating, zone pumps will run.. but without buffer tank i think they are stoped. 
@Grufti68  why you need to disable buffer tank?

**Comment by MiG-41** [comment]
No , they are  not stopped.  I have such system with 2 zones , without buffer (phisicaly ,and disabled in HP ) , and two zones works (and zone pumps run).

**Comment by geduxas** [comment]
> No , they are not stopped. I have such system with 2 zones , without buffer (phisicaly ,and disabled in HP ) , and two zones works (and zone pumps run).

oh, i have also 2 zones with extension board and buffer tank, didn't test that setup disabling buffer tank, just thought that should be normal.. becouse if you close 3 valve, and you lose water circulation source for thouse pumps.. so it would be logicaly to turn off.. it could be still running but you will need to close 3 way valve for zones.. otherwise pumps will left without circulating water?

**Comment by MiG-41** [comment]
@geduxas , can we go to slack , just to not talk in this thread ?
First , i need to understand , if for you 3valve is the  mixing valve on zones , or 3way valve for DHW ?:)

**Comment by Grufti68** [comment]
i have send a massage in slack

**Comment by Grufti68** [comment]
@geduxas
 i have a buffer for 2 zones and i have a water tank.
I use the SG-Ready for the PV surplus.

Normally I work without a buffer but when the SG-Ready is active I want to activate the buffer to save more energy

sorry for my english i use a translator

**Comment by IgorYbema** [comment]
Ok I understand. Let me see if I can add that

**Comment by Grufti68** [comment]
Thx

**Comment by IgorYbema** [comment]
I have created a test build for you:
https://github.com/IgorYbema/HeishaMon/actions/runs/4137527245
Check the build binary and install it.

In https://github.com/IgorYbema/HeishaMon/blob/main/MQTT-Topics.md at SET28 you can see how to use it.

Please let me know if this works for you

**Comment by Grufti68** [comment]
WOW that was fast, yes it works. Thanks a lot for your help

**Comment by Grufti68** [comment]
Hello, I have the following problem.
Buffer memory programming is built in, but I always get an error message about Node Red when I start up. What could be the problem?
[https://panasonic-wemos.slack.com/files/U04NNEYPW2Z/F04Q95RFHMY/image.png](url)

**Comment by IgorYbema** [comment]
I'm not sure, but why are you using port 8003? Is it forwarded in an upstream router or something like that? Can be that that doesn't work properly

**Comment by Grufti68** [comment]
It is connected to a range extender, I can reach heishamon via the port, it also works for all commands but not for buffer

**Comment by Grufti68** [comment]
but it makes no difference whether I am directly connected and run the command or not. the console doesn't work for me either

**Comment by IgorYbema** [comment]
Ok so, the new command doesn't seem to work. Also if you are sending the command manually (send the url)?

**Comment by IgorYbema** [comment]
I see that it also say 'external pad heater'. I think I forgot to change something :)

**Comment by Grufti68** [comment]
if I send the command as a url via the browser, it works. Do I need a break between recommendations? I send 5-7 commands at a time

**Comment by IgorYbema** [comment]
Can you try? Not sure but indeed it works here also manually (even it says wrong text)

**Comment by Grufti68** [comment]
it works via url but via node red I get an error message (see above)

**Comment by IgorYbema** [comment]
I'll try with node-red also.

**Comment by Grufti68** [comment]
I suspect that it just has to do with the wrong feedback

**Comment by geduxas** [comment]
> I suspect that it just has to do with the wrong feedback

In slack you told that you send multiple set commands one after another.. is it related to this wrong feedback? Or you have same error after setting only this one?

**Comment by Grufti68** [comment]
I also have this error when I only send the command one at a time

**Comment by IgorYbema** [comment]
I am builing a changed version here (with the correct response): https://github.com/IgorYbema/HeishaMon/actions/runs/4215449652

**Comment by Grufti68** [comment]
It works with Node Red, Blockly and url so far. The status message via url is also correct. I will test it further and will report if it doesn't work. I also have Correcr receives data 100% for the first time. Thank you
