### ISSUE TITLE
What is the meaning of Heater_Start_Delta, Heater_Stop_Delta, Heater_Delay_Time?

### ISSUE THREAD

**Issue by JohannesKlug** [heishamon/HeishaMon#319]
I'd like to understand how TOP95, TOP96, TOP957 (Heater_Delay_Time, Heater_Start_Delta, Heater_Stop_Delta) are used by the heat pump. Is there any further documentation on these variables?

**Comment by IgorYbema** [comment]
You can find it in the J-series manuals. It only works for the J-series.

**Comment by HighlyCompressedAir** [comment]
This issue can be closed.
