### ISSUE TITLE
MQTT commands Heishamon.yaml HA

### ISSUE THREAD

**Issue by TenonH** [heishamon/HeishaMon#327]
Hi,
I detected that part of the topic disappeared in version 1.4.0 relative to version 1.2.0. What was the reason, not that I am missing something, although the establishment of heatshift is incomprehensible to me, but I am curious why.
Version 1.2.0 #TOP22 - DHW heating delta is
Version 1.4.0 #TOP22 - DHW heating delta is not there

**Comment by geduxas** [comment]
I have switched to integration mode in early stage.. so in my old yaml there is no #TOP22 ether.. it's maigt just disappeared while someone transfered config to new HA implementation.. or it could be that's there never been.. could it be that you have added to your config?

**Comment by TenonH** [comment]
Hmm, maybe :)I don't remember exactly because I did it 1.5 years ago. the list of all TOPIC is in the link below:
[https://github.com/Egyras/HeishaMon/blob/master/MQTT-Topics.md](url)
My point was why some TOPICs are not there, I was afraid that they might cause unstable heatpumps:)
