### ISSUE TITLE
Integration of esp-knx-ip possible?

### ISSUE THREAD

**Issue by MAButz** [heishamon/HeishaMon#328]
Hi,
in tasmotoa is esp-knx-ip integrated -> https://github.com/envy/esp-knx-ip

I would like to try this, unfortunately my c++ knowledge is not very good.

Is there any general interest? And could someone support with this?

Greetings
Marc

**Comment by MiG-41** [comment]
Ok , but in HP there is not any knx .... 

There is some module to have KNX with Aquarea , bu whatfor , if you can connect esp8266 diretly,

**Comment by geduxas** [comment]
https://www.intesis.com/products/ac-interfaces/knx-gateways/panasonic-knx-air-to-water-pa-aw2-knx-1?ordercode=INKNXPAN001A000

**Comment by MAButz** [comment]
Thank you!
i know this module, i want to use mqtt and knx, that was my idea.

**Comment by MiG-41** [comment]
So if ou use mqtt ,Heishamon is good for that , you don't need knx in beetween.

**Comment by MAButz** [comment]
ok, now i use for the moment node-red and send the required values from heishaMon to knx.
Thanks.
