### ISSUE TITLE
Problems with Heisha monitor console

### ISSUE THREAD

**Issue by MAButz** [heishamon/HeishaMon#331]
Hi,
i want to use the Heisha monitor console.
On the local network (open with the direct IP) it works, but over nginx (Reverse-Proxy) over https it do not working.
It seems to be use websocket, at this point (in HeishaMon/HeishaMon/htmlcode.h)

> static const char websocketJS[] PROGMEM =
  "<script>"
  "  var bConnected = false;"
  "  function startWebsockets() {"
  "    if(typeof MozWebSocket != \"undefined\") {"
  "      oWebsocket = new MozWebSocket(\"ws://\" + location.host + \":80\");"
  "    } else if(typeof WebSocket != \"undefined\") {"
  "      /* The characters after the trailing slash are needed for a wierd IE 10 bug */"
  "      oWebsocket = new WebSocket(\"ws://\" + location.host + \":80/ws\");"
  "    }"
  ""
  "    if(oWebsocket) {"
  "      oWebsocket.onopen = function(evt) {"
  "        bConnected = true;"
  "      };"
  ""
  "      oWebsocket.onclose = function(evt) {"
  "        console.log('onclose: ' + evt);"
  "      };"
  ""
  "      oWebsocket.onerror = function(evt) {"
  "        console.log('onerror: ' + evt);"
  "      };"
  ""
  "      oWebsocket.onmessage = function(evt) {"
  "        let obj = document.getElementById(\"cli\");"
  "        let chk = document.getElementById(\"autoscroll\");"
  "        obj.value += evt.data + \"\\n\";"
  "        if(chk.checked) {"
  "          obj.scrollTop = obj.scrollHeight;"
  "        }"
  "      }"
  "    }"
  "  }"
  "</script>";

And i think this should be replaced 

> oWebsocket = new WebSocket(\"ws://\" + location.host + \":80/ws\");"

in 

> oWebsocket = new WebSocket(((window.location.protocol === "https:") ? "wss://" : "ws://") + window.location.host + "/ws");

i think the MozWebSocket is old?  And all newer (Firefox Versions) should use WebSocket...?

This is not tested yet, is only suggestion from me.

**Comment by CurlyMoo** [comment]
I would welcome the test
