### ISSUE TITLE
WP niet  type herkend

### ISSUE THREAD

**Issue by Pietjebel10** [heishamon/HeishaMon#333]
Mijn WP wordt niet herkend, vorige week net binnengekomen, Type WH-MDC09J3E5 Monoblock
Code niet op de lijst van de Heishamon, graag je advies.

C2 D3 0C 35 65 B2 D3 0B 96 65 
![Screenshot 2023-03-08 110204](https://user-images.githubusercontent.com/95292153/223698085-a2fb2075-309b-48bb-a7ab-d4619452a071.jpg)

**Comment by IgorYbema** [comment]
already in  https://github.com/IgorYbema/HeishaMon/blob/main/HeatPumpType.md
need to add in code yet

**Comment by sabom2d** [comment]
I have exaclty the same issue with my MD9 J,
any news regarding that issue?
I use firmware Version 3.1
