### ISSUE TITLE
IOBroker MQTT datapoints totally weird

### ISSUE THREAD

**Issue by Tom54497** [heishamon/HeishaMon#334]
![Screenshot (119)](https://user-images.githubusercontent.com/40543008/224020006-934250a7-6bac-4176-a3c3-66b45c3deadb.png)

Running the latest IOBroker version with latest MQTT adapter the transmitted datapoints from Heishamon show up like in the attached picture. IOBroker ist still working with it but how to fix this?

**Comment by Tom54497** [comment]
Anybody an idea?

**Comment by geduxas** [comment]
Once i hade similar issues with very old mqtt server... But you telling that have latest. Could you clarify which version do you have? And which vendor?

**Comment by Tom54497** [comment]
It is the MQTT broker/client adapter for IOBroker V 4.1.1

**Comment by Tom54497** [comment]
Still having that trouble. Cleared all wrong datapoints and after a while they appear again. Might be an Mqtt Adapter issue. No one an idea?

**Comment by geduxas** [comment]
Did you test your mqtt server? Did you connect to it with mqtt explorer? Same results?

**Comment by Tom54497** [comment]
If I setup a new instance all datapoints are quiet normal. After a while ... might be after a restart of mqtt adapter but that is only an asumption .... new datapoints will be created additionally to the old and correct structure.

Will try mqtt Explorer

**Comment by geduxas** [comment]
I think yours mqtt server going insane after all. Which MQTT server version do you run?

**Comment by Tom54497** [comment]
It is the latest stable version of mqtt adapter for iobroker

**Comment by geduxas** [comment]
I am not familiar with iobroker, could me point out to resources? Would like to check it.

**Comment by Tom54497** [comment]
https://github.com/ioBroker/ioBroker.mqtt

**Comment by geduxas** [comment]
> https://github.com/ioBroker/ioBroker.mqtt

Based on mqtt js 4.3.7 2y old build. 
Is it possible to run external mqtt server?
