### ISSUE TITLE
Can you add WH-MXC09J3E5 TCAP 9kW Monoblock single phase

### ISSUE THREAD

**Issue by DCL777** [heishamon/HeishaMon#337]
[WH-MXC09J3E5_Specification_Sheet_8426.pdf](https://github.com/Egyras/HeishaMon/files/11010462/WH-MXC09J3E5_Specification_Sheet_8426.pdf)

Can you add: WH-MXC09J3E5 ? see attached specs

UID:  32 D4 0B 99 77 62 90 0B 01 78  see image

![image](https://user-images.githubusercontent.com/55956951/226161312-e3ad2eff-5ca5-4b61-8e7b-b202cf10454c.png)

Thanks

**Comment by IgorYbema** [comment]
Yes I will. Thanks!

**Comment by HighlyCompressedAir** [comment]
It was added, this issue can be closed.
