### ISSUE TITLE
Add C2 D3 0C 35 65 B2 D3 0B 96 65 as 	WH-MDC09J3E5

### ISSUE THREAD

**Issue by timovd** [heishamon/HeishaMon#338]
https://github.com/Egyras/HeishaMon/blob/09e9ae8c0c347881b6de55ffd096fc68f025c78d/HeishaMon/decode.h#L92

C2 D3 **0B** 35 65 B2 D3 0B 96 65 is defined as WH-MDC09J3E5
C2 D3 **0C** 35 65 B2 D3 0B 96 65 is also a WH-MDC09J3E5 (without prefix or extension)

TOP92 is currently sending 255/unknown

**Comment by geduxas** [comment]
> https://github.com/Egyras/HeishaMon/blob/09e9ae8c0c347881b6de55ffd096fc68f025c78d/HeishaMon/decode.h#L92
> 
> C2 D3 **0B** 35 65 B2 D3 0B 96 65 is defined as WH-MDC09J3E5 C2 D3 **0C** 35 65 B2 D3 0B 96 65 is also a WH-MDC09J3E5 (without prefix or extension)
> 
> TOP92 is currently sending 255/unknown


In panasonic debug menu those bytes are split in seperate groups.. it maigh be that it could have different purposes.. or maybe different versions.. 

in panasonic menu it would be in this group:

 C2 D3 | **0C** 35 65 |  B2 D3 | 0B 96 65 |

And read from revers side with minus 1 byte
C2 D3 = 0xD3C1
0C 35 65 = 0x65350B
B2 D3 = 0xD3B1
0B 96 65 = 0x65960C

It's requires more investigations, and more data do get what's it means.. it could be internal/external PCB versions, or firmware versions..

**Comment by timovd** [comment]
Other (Dutch) user also mentioned the same issue: https://github.com/Egyras/HeishaMon/issues/333

**Comment by MiG-41** [comment]
There are already WH-MDC05J3E5 and WH-MDC07J3E5 with the same situation

**Comment by IgorYbema** [comment]
already in  https://github.com/IgorYbema/HeishaMon/blob/main/HeatPumpType.md
need to add in code yet

**Comment by MiG-41** [comment]
BTW @IgorYbema  , are you sure WH-SXC12H6E5 what you just now added is 3phase ? E5 points for singlaphase....

**Comment by IgorYbema** [comment]
@MiG-41 that is indeed weird.. panasonic says 1-phase/3-phase

**Comment by IgorYbema** [comment]
service manual clearly states 1-phase.. so i'll change that

**Comment by MiG-41** [comment]
> service manual clearly states 1-phase.. so i'll change that

Do you have service manual for it ? 
Maybe 6kW heaters are divided in two sections ( 3kW +3KW) so you could conect it to 2 phases , and 3rd phase is outher /compressor unit....

**Comment by ClassicGOD** [comment]
Having similar issue with WH-SXC09H3E8 + WH-UX09HE8 kit. 

Returns:
E2 CF 0D 85 05 12 D0 **0E** 94 05
instead of expected:
E2 CF 0D 85 05 12 D0 0C 94 05

Probably a new revision as it was purchased recently.

**Comment by IgorYbema** [comment]
I added it to my documentation and it will be added to the code on next release

**Comment by HighlyCompressedAir** [comment]
It was added, this issue can be closed.
