### ISSUE TITLE
MD5 checksum incorrect for 3.1

### ISSUE THREAD

**Issue by kenzodeluxe** [heishamon/HeishaMon#340]
When validating the checksum for the latest binary, I see that the checksum I generate is different from what's expected:
```
# md5sum HeishaMon.ino.d1-v3.1.bin 
8058603bbe6029f088e643eaa8549b66  HeishaMon.ino.d1-v3.1.bin
# cat HeishaMon.ino.d1-v3.1.md5 
407c4c45cea30193b450ddfaf4f44ed4
```
However, it matches fine for 3.0:
```
# md5sum HeishaMon.ino.d1-v3.0.bin 
872192efa66c91946e0295d5f8140fc5  HeishaMon.ino.d1-v3.0.bin
# cat HeishaMon.ino.d1-v3.0.md5 
872192efa66c91946e0295d5f8140fc5
```
Seems like the binary that was uploaded is incorrect.

**Comment by geduxas** [comment]
it's seams your binary is broken, 

$ md5sum HeishaMon.ino.d1-v3.1.bin
407c4c45cea30193b450ddfaf4f44ed4  HeishaMon.ino.d1-v3.1.bin

**Comment by kenzodeluxe** [comment]
I thought I had downloaded it multiple times ...sorry for the noise! :)
