### ISSUE TITLE
BUG: floor function in rules not accepted/working

### ISSUE THREAD

**Issue by blb4github** [heishamon/HeishaMon#341]
I want to use the floor function in rules. If I try to save the web page doesn't refresh. If i reload the page the rules are not changed. 

Firmware version: Alpha-38949f5 & Alpha-e6cd2d7

the rule I try to set:
$HRT = floor(@Main_Outlet_Temp - 1);	

What works now as work-around:

$HRT = round(@Main_Outlet_Temp - 1);	
if (@Main_Outlet_Temp - $HRT) < 1 then	
	$HRT = $HRT - 1;
end

**Comment by IgorYbema** [comment]
@CurlyMoo

**Comment by CurlyMoo** [comment]
What does the console output say when saving the rule?

**Comment by blb4github** [comment]
the console output freezes (stops)

**Comment by CurlyMoo** [comment]
Fix in https://github.com/IgorYbema/HeishaMon/pull/120

**Comment by CurlyMoo** [comment]
@Egyras @blb4github This one can be closed.

**Comment by blb4github** [comment]
Thanks for solving this issue!
