### ISSUE TITLE
Request for a new mqtt command e.g. "SetHeatingOffOutdoorTemp" to change TOP77

### ISSUE THREAD

**Issue by JockelBln** [heishamon/HeishaMon#351]
Is it possible to add a new topic to change the switch-off temperature in summer?
So it would be easier to put the heat pump in "summer mode". For example, you could simply set Heating_Off_Outdoor_Temp to 5° and the heat pump would then not start at night when the outside temperature is a bit lower.
At the moment you would have to create an extra switch-off timer in this case, or manually change Heating_Off_Outdoor_Temp in the installer menu.
Thank you for reading.

**Comment by MiG-41** [comment]
You can change mode to DHW Only , and HP won't turn on ....

**Comment by JockelBln** [comment]
Unfortunately this is not practical for me. I only need one DHW timer a day for one hour at noon.
The HP should remain in HEAT mode for the rest of the day so that it does not reheat the water.

**Comment by MiG-41** [comment]
Why remain in Heat mode? Turn off/on on DHW time...It can be don albo with HP Schedule....

**Comment by JockelBln** [comment]
Then I have to constantly adjust the timers for summer and winter.
However, the HP should run largely independently without manual intervention on site. Only two timers are programmed: 12:30 DHW+HEAT and 14:00 HEAT.
In summer I would then like to remotely suppress heating at cooler temperatures by lowering Heating_Off_Outdoor_Temp.
I can't change the timers without being there.

If it's not possible to implement a mqtt command for changing Heating_Off_Outdoor_Temp then that's ok auck. It was just a question.
Maybe @Egyras or @IgorYbema can say something about it...

Anyway, thanks for the support and working on the tool!

**Comment by geduxas** [comment]
Heishamon is gateway for heatpump to communicate with outside.. if it's not possible to accomplish in heatpump it will not be possible in Heishamon also.. also timer function, is only available in HP controller, so remote controller by it's timer tells to HP when stop. 

Also Heishamon is capable of scripting.. so i think you could try to implement it from there.. but as you have already using mqtt it's seams you already have some external controller.. so switch all logic there :)

**Comment by JockelBln** [comment]
Sorry, I think we're talking past each other. My english is just google speech ;-)
I just wanted to suggest whether it is possible to create a new command topic (e.g. SetHeatingOffOutdoorTemp) in the firmware in order to change "TOP77 Heating_Off_Outdoor_Temp". Similar to e.g. SetZ1HeatRequestTemperature etc.
It's not about timers.

**Comment by geduxas** [comment]
Ok, now sounds better :D indeed there is no set command.. yes it could be possible to implement.. also it's possible to change that value with RAW format.. how often it's need to be changed? For most it's set and forget.

**Comment by mieschc** [comment]
I would like such a command too. Disadvantage of the Panasonic is, that she ist using only the current Outdoor Temp. and not a average temp from last 2-3 days. With this command it would be possible to adjust the Summer limit temp based on an average Outdoor Temp.

**Comment by JockelBln** [comment]
> yes it could be possible to implement.. 

That would be great.
> how often it's need to be changed? For most it's set and forget.

At least twice a year, but certainly more often in spring and autumn.
The advantage would also be that you do not have to be on site at the remote control.

**Comment by geduxas** [comment]
@mieschc i think you get it wrong.. that command is only to set value, but it will not monitor and change it automaticaly.. you still need to change it from outer source.. also average temperature will not make any sense i think.

@JockelBln I think I could do that, will push changes to @IgorYbema repo, and after he will be ready to release it will merge here.

**Comment by mieschc** [comment]
@geduxas it is not uncommon that heating controllers are using a mixture of current Outdoor Temp and average temp of last day(s) for Summer limit. This prevents starting of the Heater if temps are falling below the value for just couple of hours (e.g. Rain shower or at night).

If the command topic would be implemented I can use it in my Automation (node Red) to prevent such Starts.

Good News that it might be possible!

**Comment by JockelBln** [comment]
@geduxas Thank you for your effort, that would help me a lot 👍

**Comment by geduxas** [comment]
@mieschc it was always possible, you can send RAW send command and set desired value to heatpump even without named topic. Yes it's not so easy but it's possible. Also here is screenshot from service manual 

![Screenshot_2023-05-12-00-29-08-04_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/Egyras/HeishaMon/assets/18700450/47432062-f420-47dc-a6ef-473dd6c8e7ab)

It will allow beter understand how heating on/off is working in heatpump side

**Comment by geduxas** [comment]
@mieschc, @JockelBln before it appears in release, you can try alpha build 

https://github.com/IgorYbema/HeishaMon/suites/12847956160/artifacts/692494233

**Comment by JockelBln** [comment]
I tested it right away - it works perfectly.
Thank you for that, you are my hero 👍

**Comment by mieschc** [comment]
Unfo I cannot test it at the moment. I am abroad and have only limited access to my Installation. Will try it when I am back at home.

**Comment by mieschc** [comment]
Tested it too now. Working fine. Thank you @geduxas

**Comment by bigdragan** [comment]
Hallo, ich habe genau das Gleiche zur gleicher Zeit, nur in IOBroker Forum, gefragt.
https://forum.iobroker.net/topic/65229/heishamon-set-heating_off_outdoor_temp?_=1689097346298
Was für ein Zufall.

Ich habe die Alpha-Version gerade getestet, funktioniert 100%ig.
Vielen Dank für eure Arbeit.
Sehr guter Job!

**Comment by orhan77971** [comment]
Link to alpha is offline :-(

**Comment by JockelBln** [comment]
Try this link:
https://github.com/IgorYbema/HeishaMon/actions/runs/5796752737

**Comment by JockelBln** [comment]
The set command is already included in release 3.2

Thanks to all
