### ISSUE TITLE
Using HeishaMon without any home automation

### ISSUE THREAD

**Issue by HighlyCompressedAir** [heishamon/HeishaMon#353]
Hi, I don't have any home automation setup and I'd like to use HeishaMon to control my HP by itself using rules functionality and I have a few questions:
1. Does HeishaMon support automatic summer/winter time change? HP controller doesn't and it's annoying.
2. Is it possible to use actual time in rules? I'd like to create a schedule to heat water during cheap electricity hours because of reason nr 1. Also the HP controller doesn't keep the time very well and it becomes more and more inaccurate overtime.
3. Does HeishaMon PCB keeps it's logs anywhere? I assume they just exist in memory and get wiped out after power loss? How big these logs can get? I'd like to download them on my PC and turn the data into nice graphs just like Panasonic Service Cloud does. Readme mentions this url - http://heishamon.local/json Can you show me a screenshot so I can see how does it actually look like?

Thank you.

**Comment by geduxas** [comment]
Logs, and settings can be obtained via MQTT server, also for graphs you could use Graphana.

**Comment by HighlyCompressedAir** [comment]
Ok, I see that I can create a free account on grafana.com. Can heishamon send data there directly though? Without influxdb, prometheus and so on?

**Comment by geduxas** [comment]
> Ok, I see that I can create a free account on grafana.com. Can heishamon send data there directly though? Without influxdb, prometheus and so on?

I think you could fetch data from Heishamon. But you will need to open access from internet, which will not sound safety at all.. and pushing to anything else except mqtt is not possible for now.

**Comment by MiG-41** [comment]
You could try  another @Egyras  project: https://github.com/Egyras/Panasonic_GUI

**Comment by HighlyCompressedAir** [comment]
> You could try another @Egyras project: https://github.com/Egyras/Panasonic_GUI

Does it generate graphs though? I didn't mention that I don't have heishamon yet, I'm thinking about buying it once I figure out how it actually works and unfortunately there's not much info about all that stuff. For example this Panasonic GUI has an icon that looks like a graph, but there's no screenshot showing what this tab looks like, so I don't know what it does.

I have an openwrt router which I guess could act as mqtt broker. Would I be able to make it work with grafana then?

**Comment by Egyras** [comment]
> You could try another @Egyras project: https://github.com/Egyras/Panasonic_GUI

This was just final work for my python 1st level trainings. If I have more time during winter period I will re-write it to be compatible on phones.

**Comment by Egyras** [comment]
> > You could try another @Egyras project: https://github.com/Egyras/Panasonic_GUI
> 
> Does it generate graphs though? I didn't mention that I don't have heishamon yet, I'm thinking about buying it once I figure out how it actually works and unfortunately there's not much info about all that stuff. For example this Panasonic GUI has an icon that looks like a graph, but there's no screenshot showing what this tab looks like, so I don't know what it does.
> 
> I have an openwrt router which I guess could act as mqtt broker. Would I be able to make it work with grafana then?

It doesnt show any nice graphs, just limited control options and all output of values what heishamon shows ;)

**Comment by mi-hol** [comment]
> This was just final work for my python 1st level trainings. If I have more time during winter period I will re-write it to be compatible on phones.

Maybe this info and a screenshot could be added to ReadMe ?

**Comment by Egyras** [comment]
Will do :)
