### ISSUE TITLE
Two Heishamon losing MQTT connection every 10 seconds

### ISSUE THREAD

**Issue by ttplayer** [heishamon/HeishaMon#354]
Since today I have a two heat pumps connected to my Homeassistant (core mosqito) installation via two Heishamons.
Previously only one was connected for weeks with no problems.
In the "Console" of each HeishaMon I see now many MQTT reconnects, maybe every 10 seconds.
It seems that the two interfere with each other

**Comment by geduxas** [comment]
Have you change mqtt topic name for another?

**Comment by ttplayer** [comment]
yes!
![2023-05-19_174803](https://github.com/Egyras/HeishaMon/assets/13061527/297cea17-c6bb-41e1-9356-0dd3a6c23327)

**Comment by IgorYbema** [comment]
also hostname should be different... mqtt server needs each client to have different hostname

**Comment by ttplayer** [comment]
Aaarggggh. ........That's the solution.
Different Hostname and base-topic.

Thank you Igor

**Comment by geduxas** [comment]
> Aaarggggh. ........That's the solution. Different Hostname and base-topic.
> 
> Thank you Igor

Please close issue if it's resolved. Thank you.

**Comment by ttplayer** [comment]
Solved
