### ISSUE TITLE
Request for help, syncing "WattHourTotal"

### ISSUE THREAD

**Issue by ttplayer** [heishamon/HeishaMon#355]
My two Heishamon are working now to my satisfaction.
Now I'm trying to sync "watthourtotal" with no effort.

I'm using MQTT-Explorer, but I think i don't use the corect command syntax -(.

Tried many times this one, while rebooting the Heishamon, but didn't get it.

**panasonic_heat_pump1/s0/WatthourTotal/1=20100**

![2023-05-22_160136](https://github.com/Egyras/HeishaMon/assets/13061527/4559cd4b-c360-46ae-a59a-911cc7e5ccbb)

Thanks in advance

**Comment by MiG-41** [comment]
In MQTT Explorer topic should be: "panasonic_heat_pump/s0/WattHourTotal/1" ( not "panasonic_heat_pump/s0/WattHourTotal/1=20100")
Value "20100" you should put below this dot with "raw" , you have black marker there. And then press publish.

**Comment by ttplayer** [comment]
Unbelievable .........you save my day
![2023-05-22_173833](https://github.com/Egyras/HeishaMon/assets/13061527/73707493-bdbb-4d10-aea1-2eee416f7e65)

**Comment by ttplayer** [comment]
An with your help i've figured out the same procedure with homeassistant / core mosquitto

**Comment by ttplayer** [comment]
![2023-05-22_174616](https://github.com/Egyras/HeishaMon/assets/13061527/0800d51d-1c56-4e5b-bc70-c16b1599b6f5)
