### ISSUE TITLE
Heishamon automatic Reebot possible?

### ISSUE THREAD

**Issue by ttplayer** [heishamon/HeishaMon#358]
Didn't find a solution. Is there a possibility, to force an automatic reboot of the Heishamon, maybe once a week?

**Comment by geduxas** [comment]
Why reboot?

**Comment by ttplayer** [comment]
I've two Heishamons connected with my mqtt-broker, one of them over a vpn-tunnel, while he is on an other location.
This one looses the connection sporadically.
Then it can only be connected again after a reboot.
