### ISSUE TITLE
Implement cooling mode

### ISSUE THREAD

**Issue by bla123454321** [heishamon/HeishaMon#359]
Hi,
as the temperatures are getting higher I for the first time thought about using the cooling mode of my Panasonic MXC09H3E8. When I head a look at the heishamon.yaml file for home assistant I saw that the cooling mode is not implemented. Is there a special reason why only mode '0' (Heat), '3' (DHW) and '4' (Heat+DHW) is implemented?
Can I just add the other modes ('1' (Cool), '5' (Cool+DHW)) to the heishamon.yaml file and try it out or is there anything which blocks cooling when using heishamon?

**Comment by geduxas** [comment]
Yes you can, it's just not completed yaml. Also you can try heishamon integration module through HACS.

**Comment by bla123454321** [comment]
> Yes you can, it's just not completed yaml. Also you can try heishamon integration module through HACS.

Well, but I guess the heishamon.yaml in the integration module in HACS is the same, correct?

**Comment by geduxas** [comment]
No, with integration module you don't need yaml at all. And also there is no problem to use both.
