### ISSUE TITLE
New byte sequence for WH-SXC09H3E8

### ISSUE THREAD

**Issue by MEKadan** [heishamon/HeishaMon#361]
According to the HeatPumpType listings code for mentioned model is E2 CF 0D 85 05 12 D0 0C 94 05

My new unit, manufactured in the beginning of year 2023, introduces itself with: E2 CF 0D 85 05 12 D0 0E 94 05

**Comment by MiG-41** [comment]
Can you add this in this table ? : https://github.com/Egyras/HeishaMon/blob/master/HeatPumpType.md

There are identified "new version" of Gen J monoblocks , but difference is on other byte....

**Comment by MEKadan** [comment]
You mean I should add it in table? Have we permission to do that?

Another remark: This is not J series monoblock, but Aquarea T-CAP H series (as I understand?) split with WH-SXC09H3E8 as the indoor unit and WH-UX09HE8 as the outdoor unit.

https://www.aircon.panasonic.eu/MT_en/model/kit-wxc09h3e8-wh-sxc09h3e8-wh-ux09he8/

**Comment by geduxas** [comment]
GitHub is open for all to contribute, so feel free to modify as you wish :)

And yes, panasonic sold as seperate devices, but they can come as kit too. Also that "product" identifier is not well decoded, so we are thinking that those byte's are represent exact model.. but it also could have extra data.. your code are a little bit different.. so it could be new pcb revision.. or it could be release date .. so more information you could bring, better will be for future understanding.

**Comment by MEKadan** [comment]
> GitHub is open for all to contribute, so feel free to modify as you wish :)
> 
> And yes, panasonic sold as seperate devices, but they can come as kit too. Also that "product" identifier is not well decoded, so we are thinking that those byte's are represent exact model.. but it also could have extra data.. your code are a little bit different.. so it could be new pcb revision.. or it could be release date .. so more information you could bring, better will be for future understanding.

I do not quite know how to do this... If anyone capable of doing so would like to add the following:

E2 CF 0D 85 05 12 D0 0E 94 05
IDU: WH-SXC09H3E8
ODU: WH-UX09HE8
KIT: KIT-WXC09H3E8 (This I'm not sure of; system was sold to me listing only IDU & ODU. There is a similar kit already listed with type number KIT-WXC09H9E8, which has the same IDU & ODU numbers for units. For that already existing KIT-WXC09H9E8 I could find only few references mainly from Polish sites. For my KIT-WXC09H3E8 the reference base was much larger).
9kW, 3ph, T-CAP

**Comment by MiG-41** [comment]
3 after H means power of installed electrical heaters so 3kW ( 1kW per phase) or 9kW (3kW per phase) ,and it is identical to IDU , so KIT should be ok.

**Comment by MEKadan** [comment]
> 3 after H means power of installed electrical heaters so 3kW ( 1kW per phase) or 9kW (3kW per phase) ,and it is identical to IDU , so KIT should be ok.

That's what I thought it is, but was not sure.... However, I've got 3x3kW in my boiler, so I do not need these in heat pump

**Comment by MEKadan** [comment]
> > GitHub is open for all to contribute, so feel free to modify as you wish :)
> > And yes, panasonic sold as seperate devices, but they can come as kit too. Also that "product" identifier is not well decoded, so we are thinking that those byte's are represent exact model.. but it also could have extra data.. your code are a little bit different.. so it could be new pcb revision.. or it could be release date .. so more information you could bring, better will be for future understanding.
> 
> I do not quite know how to do this... If anyone capable of doing so would like to add the following:
> 
> E2 CF 0D 85 05 12 D0 0E 94 05 IDU: WH-SXC09H3E8 ODU: WH-UX09HE8 KIT: KIT-WXC09H3E8 (This I'm not sure of; system was sold to me listing only IDU & ODU. There is a similar kit already listed with type number KIT-WXC09H9E8, which has the same IDU & ODU numbers for units. For that already existing KIT-WXC09H9E8 I could find only few references mainly from Polish sites. For my KIT-WXC09H3E8 the reference base was much larger). 9kW, 3ph, T-CAP

Hmmm... As it is not in the current list, would someone give a quick briefing, how to update the list myself? 

Especially I do not know, how to start editing it. Trying it results in "You need to fork this repository to propose changes." Is this how the process goes? What then etc. etc...

**Comment by geduxas** [comment]
Fork repository, edit code to add missing record, push commit to your repository, and send pull request to master repository.

**Comment by MEKadan** [comment]
> Fork repository, edit code to add missing record, push commit to your repository, and send pull request to master repository.

OK, done. I hope I got it right...

**Comment by MEKadan** [comment]
Fork pulled... Integration still showing "Unknown model for HeishaMon". Probably because the byte sequence is missing from decode.h, I don't know if from anywhere else.

Also I do not know, when they even should be there :)

**Comment by HighlyCompressedAir** [comment]
It was added, this issue can be closed.
