### ISSUE TITLE
DHW re-heat start & DHW delta

### ISSUE THREAD

**Issue by MEKadan** [heishamon/HeishaMon#362]
This is most likely not HeishaMon issue, but in case anyone happens to know the logic behind the following in my WH-SXC09H3E8.

According to the manuals (which are lousy, btw) the DHW start should occur when DHW Temp < (DHW target temp value + DHW Heat Delta)  and where DWH Heat Delta  is a negative value.

This should give e.g. for DHW target temp 55 and delta being -5 a starting temp of 50. However, the pump seems to start at 45, regardless of what I put to DHW target. Tried only values > 50 this far. Starting temp is in all of those cases 45 degrees.

Is there some setting overriding this or what?

**Comment by geduxas** [comment]
Yes,delta and minus 1 more, so it should start in 49. Also it's depends to timers.. also it's depends if smart dhw is enabled or not.

**Comment by MEKadan** [comment]
> Yes,delta and minus 1 more, so it should start in 49. Also it's depends to timers.. also it's depends if smart dhw is enabled or not.


OK... This is  KIT-WXC09H3E8 (WH-SXC09H3E8 + WH-UX09HE8). I recall not seeing anything about SmartDHW in the manuals, nor I have set any timers? Still it starts at 45 deg, no matter what >50 values I put as the DHW target temp?

**Comment by jllussa** [comment]
This is a setting on the user menu (Function setup). 
You could choose two settings smart or standard.
This setting is after sterilization.

**Comment by MiG-41** [comment]
> This is a setting on the user menu (Function setup). You could choose two settings smart or standard. This setting is after sterilization.

This setting is valid fo generation J (and probably for newer ) , in H not exist.

Here can be also other problem. My HP is not able to reach 55 deg in DHW ( just test it ) , it stopped on 51 deg ( before compressor made 2 times on -off) . Means water outlet reach 57 deg an more , and DHW was not able to take out the produced heat ( even my DHW have a surface of  pipe 3,4m2 ).  
I usually set DHW temperature to 47 deg and it is enough. 
Question , why you using so high temperature , since it is not economic ...

**Comment by geduxas** [comment]
@MiG-41 i have H series 12kw t-cap. And i can confirm that mine has smart dhw option. Strange that dhw goes till that temperature.. i didn't test with mine, but 51° is enough and for me and didn't adjust that.. and reheat for me will begin ant 37°

**Comment by MiG-41** [comment]
I have H series 12kW t-cap , and i can confirm ,that mine don't have smart dhw option... So looks like it is not a J function only , t is a case o manufacture date. Is yours also E2 CF 0D 86 05 12 D0 0C 95 05 code ?

**Comment by geduxas** [comment]
Yes E2 CF 0C 74 09 12 D0 0D 95 05, i have added 13 record from my heatpump :)

**Comment by MiG-41** [comment]
No , you didn't  ,E2 CF 0D 86 05 12 D0 0C 95 05 position was mine.

**Comment by geduxas** [comment]
> 

Perhaps we both done something in same way :D #185 
It could be interesting to digg more about those difference's. I have quickly walked through Panasonic's, service manual updates, and truly didn't found anywhere from which version they had realeased with smart dhw function..

**Comment by MiG-41** [comment]
Now i see difference, yours is All-In-One ( mine is regular split) and i talked about position 5.... So Smart DHW is option for HP with DHW inside - All-In-One. 
Option with is for J is DHW capacity -  Standard/Variable

**Comment by MEKadan** [comment]
> > This is a setting on the user menu (Function setup). You could choose two settings smart or standard. This setting is after sterilization.
> 
> This setting is valid fo generation J (and probably for newer ) , in H not exist.
> 
> Here can be also other problem. My HP is not able to reach 55 deg in DHW ( just test it ) , it stopped on 51 deg ( before compressor made 2 times on -off) . Means water outlet reach 57 deg an more , and DHW was not able to take out the produced heat ( even my DHW have a surface of pipe 3,4m2 ). I usually set DHW temperature to 47 deg and it is enough. Question , why you using so high temperature , since it is not economic ...

My Aquarea reaches easily 55 and even 58. Not tested higher temps, though.

In my setup Aquarea does not have it's own tank as in all-in-ones, but there is a 500 litre thermal storage tank connected to it: https://jaspi.fi/en/product/gtv-hybrid-500-thermal-storage-tank/

I have tested these higher temps mostly to find out, what it is capable of... This is Finland we are talking about, and with old radiator house the circulating temp need to to go up to almost 60 as its can get to -30 outside during winter. -30 or below not likely anymore in southwest region and due warming by climate change. Last winter I recall there was something -28 or so at lowest. Aquarea should operate in as low as -28 deg after which there are 3-phase resistors of 9kW installed in tank. Even those are probably not enough when it gets very cold, so there is firewood -heated sauna providing extra heat... Later I'm going to connect a water circulation between sauna heater and thermal storage. I have plenty of firewood.

I just got the system installed, and I'm not that familiar with this yet. It is true, that for DHW these temps are a bit high, but I don't want to check full heating capacity in the middle of the summer, so I have tinkered with DHW instead.

Anyway, there seems to be a default value 65 deg for the sterilization set, so it should be reached as well?

What comes to this DHW start = (DHW target + DHW delta), I have asked this from Panasonic service also. They confirmed, that that is the correct equation and logic there, but why my DHW heating starts at 45 they have not answered yet. From my general experience that means they don't know the answer and know they are either trying to find the answer from factory or just let it be hoping that I just get tired of asking. Which I probably don't :)

**Comment by MEKadan** [comment]
> This is a setting on the user menu (Function setup).
> You could choose two settings smart or standard.
> This setting is after sterilization.

Checked, and mine does not have this

**Comment by geduxas** [comment]
In this scenario only smart dhw is fit to this situation.

![Screenshot_2023-07-07-15-30-54-10_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/Egyras/HeishaMon/assets/18700450/da5a923c-b651-4879-9fa1-a887e13d8a65)

Only in smart DHW it will reheat in DHW_set-delta -3°

Also there is timer floors for reheating DHW.. could it possible that you cool DHW too fast while testing it? 

And for 65° sterilization i think it will reach only with resistor help. 

P.s. i am referring to all in one service manual.. it could be that other model's have different behavior

**Comment by MEKadan** [comment]
> Only in smart DHW it will reheat in DHW_set-delta -3°
> 
> Also there is timer floors for reheating DHW.. could it possible that you cool DHW too fast while testing it?
> 
> And for 65° sterilization i think it will reach only with resistor help.
> 
> P.s. i am referring to all in one service manual.. it could be that other model's have different behavior

I do not think this fits to my case:
- No Smart DHW
- Not all-in-one which fundamentally has e.g. it's own water tank. My heat pump relies completely on exterrnal reservoir
- No timers set/ in use because no Smart DHW. Even week timers not set yet.
- Big tank, so I do not think cooling is too fast, especially in midsummer and in some days almost no warm water usage at all.  Re-eheating of typically 45min takes place in 12-18 hour intervals, depending on water usage


However, this:
![image](https://github.com/Egyras/HeishaMon/assets/66167932/88beedaa-bda7-42d2-84ae-7322a9baa2ac)
might be the case, without extra 3 deg dropping. This would , based on what @geduxas said above ("delta and minus 1 more,"), lead to 45 degrees.

However, I cannot find this kind of sentence from my manuals?

**Comment by geduxas** [comment]
@MEKadan if your dhw set point is 55, and delta is 5, so heatpump should reheat in 49°, but you have told that it reheats in 45°.. so it's strange that it don't fit any of options. What i told about timers, there is floor time for reheating, it should give some time to heat places instead of reheating DHW. So if temperature in dhw drops faster than next reheating time, it could be that case.. but usually it's about hour..

Are all mesures are from heatpump?

**Comment by MiG-41** [comment]
Same situation apear , set tank temp to 55 ,started work at 46 deg, compressor stopped once at 51 deg , turned on and did some work around 3 min , but the temperature didn't increase , and it stopped together with water pump , and didn't turn on external heater, so exacly -5 delta. from 46.  After a while temp in DHW increased to 53 deg ( hot watter come to the top).

So please check , if in your HP compresor don't stop at 50 deg , and this 55 deg you receive after some time.

**Comment by MEKadan** [comment]
> @MEKadan if your dhw set point is 55, and delta is 5, so heatpump should reheat in 49°, but you have told that it reheats in 45°.. so it's strange that it don't fit any of options. What i told about timers, there is floor time for reheating, it should give some time to heat places instead of reheating DHW. So if temperature in dhw drops faster than next reheating time, it could be that case.. but usually it's about hour..
> 
> Are all mesures are from heatpump?


- "if your dhw set point is 55, and delta is 5, so heatpump should reheat in 49°"  - Agree
- " you have told that it reheats in 45°"  - Correct
- "there is floor time for reheating, it should give some time to heat places instead of reheating DHW. So if temperature in dhw drops faster than next reheating time, it could be that case.. but usually it's about hour.."   - Mine is at default value, which is 1 hour
- "Are all mesaures are from heatpump?" - They are mainly from  Home Assistant integration by kamaradclimber, which reads them from HeishaMon. They show the same values that can be also seen by heat pump's own display. What is actually inside tank, I do not know, there is no thermometer in tank.


- "so it's strange that it don't fit any of options" - Totally agree.  If I would have to form one, it would be: Re-heat starting temp = Set temp or 51 deg, which is lower + DHW Delta minus 1 additional deg,

- One of the strange things is that the manuals for this seem to be hard to find. Via googling I have got various manuals which seem to be talking about this device. The Service Manual I managed to find from some Hungarian site and that seems to be from year 2016 (Where do you guys get these???)

**Comment by MEKadan** [comment]
> Same situation apear , set tank temp to 55 ,started work at 46 deg, compressor stopped once at 51 deg , turned on and did some work around 3 min , but the temperature didn't increase , and it stopped together with water pump , and didn't turn on external heater, so exacly -5 delta. from 46. After a while temp in DHW increased to 53 deg ( hot watter come to the top).
> 
> So please check , if in your HP compresor don't stop at 50 deg , and this 55 deg you receive after some time.

At this weather, (abt. 20 deg) when it starts from 45 deg, it runs continuously for somewhat 45 minutes and then stops reaching the set temp
