### ISSUE TITLE
setting absolute heat request temp

### ISSUE THREAD

**Issue by Tom54497** [heishamon/HeishaMon#363]
The topics comment says "If you operate your heatpump with direct temperature setup: topics ending xxxRequestTemperature will set the absolute target temperature"

But how to set the absolute heat request temperature? What does the xxx mean? Is there any example for a proper command line?

Goal is to give the heatpump an external temperature without transmitting json heatcurves.

**Comment by geduxas** [comment]
While using direct temperature, you give heat pump outlet temperature.. and heatpump will hold that.. so with command you send temperature to pump.

**Comment by geduxas** [comment]
All samples and detail information [MQTT-Topics.md](https://github.com/Egyras/HeishaMon/blob/master/MQTT-Topics.md)

**Comment by Tom54497** [comment]
Thx, but link is missleading. I only need an example for a set topic with xxxRequestTemperature!

**Comment by Tom54497** [comment]
Sorry, didn't realize that SetZ1HeatRequestTemperature has two funktions. Shifting heat value between -5 and 5 as well as setting direct heat request temp if value is above 20!

**Comment by geduxas** [comment]
@Tom54497  it's not! It's depends what type of heat control is set in pump.. if it's compensation curve, then you have range -5 - +5, if it's direct then you have direct temperature set
