### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by beninhos** [heishamon/HeishaMon#364]
Hey, not sure where to ask this. So i landed here.  I'm about to start a buy for the Bi-Bloc K Generation from panasonic. Would i be able to use your software for his new K generation too? 

Much appreciated :)

**Comment by MiG-41** [comment]
Since K generation use the same CZ-TAW1 Smart Cloud like previous H and J gen. , it should works , but this have to be confimed by K user....

**Comment by beninhos** [comment]
Seems logical, thanks. I hear the L versions are already shipping.

**Comment by MiG-41** [comment]
Waiting fo confirmation also from L users :)

**Comment by HighlyCompressedAir** [comment]
K and L are supported, this issue can be closed.
