### ISSUE TITLE
Previous read data attempt failed due to timeout!

### ISSUE THREAD

**Issue by emign** [heishamon/HeishaMon#369]
Hi,
I was having this issue with my super old selfmade Heishamon (the release where we had to manually solder a resistor across the pcb hat from about 2020). To solve this, I ordered a brand new Heishamon PCB about 4 weeks ago (July 11) together with a brand new cable :

_HeishaMon communication PCB
HeishaMon PCB version: HeishaMon normal PCB
Optional cable to connect to heatpump: 1 meter CN-NMODE cable_ 

It worked at first but now, I have the same error:

```
Previous read data attempt failed due to timeout!
Received 0 bytes data
Heishamon stats: Uptime: 0 days 0 hours 5 minutes 3 seconds ## Free memory: 73% 26464 bytes ## Wifi: 94% ## Mqtt reconnects: 5 ## Correct data: 0.00%
Requesting new panasonic data
sent bytes: 111 including checksum value: 18 
data: 71 6C 01 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
data: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
data: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
data: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Previous read data attempt failed due to timeout!
Received 0 bytes data
```

and all values are empty:

<img width="666" alt="image" src="https://github.com/Egyras/HeishaMon/assets/5278352/284fd0ef-bc98-4df7-a384-463b35f1c74a">

<img width="626" alt="image" src="https://github.com/Egyras/HeishaMon/assets/5278352/46d1c26e-cd46-470b-85ab-1763f05a038b">

Can anybody help?

**Comment by geduxas** [comment]
Where have you connected your device (share photo)? And what heatpump model do you have?

**Comment by IgorYbema** [comment]
Indeed we need some photos. Only thing I notice from this info is the high mqtt reset count (already 5 in 5 minutes). But I don't believe this is too much right now.
A possible reason is electrical interference. I don't see you have the S0 enabled but to you have S0 kWh meter connected? Some kWh meter introduce so much interference that it blocks the serial connection from getting valid info. Grounding the Heishamon S0 GND port directly to the case of the heatpump will then improve it.

**Comment by emign** [comment]
Thank you for your fast answers. The mqtt reconnect count went up quite a bit in the meantime:

<img width="684" alt="image" src="https://github.com/Egyras/HeishaMon/assets/5278352/c049518a-c2fd-4e6d-9cf6-3704c5fc4cb2">

I added the fotos:

<img width="980" alt="image" src="https://github.com/Egyras/HeishaMon/assets/5278352/745838ed-5ba8-49ff-9a8d-0c4f2687945d">

<img width="910" alt="image" src="https://github.com/Egyras/HeishaMon/assets/5278352/7ccac70e-7a5c-4da9-8310-f2ff5ef8aeb7">

It is the WH‑MDC05H3E5 model.
The values are filling now after downgrading to 2.0 and powercycling the heatpump. But I cannot upgrade to 3.1 anymore

**Comment by geduxas** [comment]
@IgorYbema it's look's similar to my case, after upgrading, heatpump randomly lock's out, and need's hard reset heatpump itself.. also noticed that after 3.0 upgrade..

**Comment by geduxas** [comment]
To clarify,  my heatpump lock's only during update..

**Comment by IgorYbema** [comment]
New to me. However during update it can spit out some bad data on the serial connection. Maybe that triggers a lock up in some situations.
Do you have that many mqtt reconnects in 2.0.also? Maybe it still is CPU overload due to bad network

**Comment by emign** [comment]
That's on 2.0
I updated to 3.1 again and it seems to go there again:

<img width="371" alt="image" src="https://github.com/Egyras/HeishaMon/assets/5278352/afe67e79-bf2c-4bdd-9b07-7f5f63f6a048">

**Comment by geduxas** [comment]
@emign it could be same case as mine.. pump hangs only during update process.. and pump needs to power cycle to work it after.. if you get in same situation, please come back with comments!

**Comment by artlov** [comment]
I had same "read data attempt failed due to timeout" issue after firmware upgrading 3.1 -> 3.2. Downgrade didn't help. Power cycle of pump restored functionality. I stayed on 3.1 at the moment.

**Comment by IgorYbema** [comment]
@artlov Thanks for letting us know. Do you have the cz-ns4p (optional pcb for extra zones) installed?

**Comment by artlov** [comment]
Yes, I have optional pcb installed, because of two zones are in use. My indoor unit model is WH-ADC0916H9E8, if it make sense.

**Comment by IgorYbema** [comment]
Ok it seems indeed that 3.2 fails on that. Can you try 3.2.2?

https://github.com/IgorYbema/HeishaMon/blob/main/binaries/HeishaMon.ino.d1-v3.2.2.bin

**Comment by artlov** [comment]
3.2.2 seems fine. At least pump didn't lock up after upgrade.

**Comment by thomersch** [comment]
For me, it turned out that my Heishamon oxidised a bit and after treating it with contact cleaner, it started receiving data again. Maybe the same is the case for someone else.
