### ISSUE TITLE
Feature request: Update node-red integration to heishamon 3.2

### ISSUE THREAD

**Issue by andreaskeutner** [heishamon/HeishaMon#387]
Update the node-red to heishamon 3.2, please

**Comment by HighlyCompressedAir** [comment]
Still outdated, I believe git submodule update is required.

**Comment by geduxas** [comment]
> Still outdated, I believe git submodule update is required.

Please shide some light to this issue, i am bit confused, what about node-red?

**Comment by geduxas** [comment]
> > Still outdated, I believe git submodule update is required.
> 
> Please shide some light to this issue, i am bit confused, what about node-red?

Oh i see now, it's about integration directory..
Yes.. it's difficult, integration used to store some samples and configuration to most popular smart home systems, truly when and how apered node-red submodule i don't know, but it not supposed to be there  :) it's different project which run by @edterbak which works tight with heishamon.. so all question should be asked there. Same as with @kamaradclimber who made integration to HomeAssistant.. before we used yaml configuration for that.. 

Yes i think all of this missing proper documentation

**Comment by edterbak** [comment]
What is this about? 
I dont understand what is outdated.
Something with heishamon.yaml? 
Or the node red flow from me?
?

**Comment by HighlyCompressedAir** [comment]
This repository uses Github submodule for your integration and those don't update automatically. Because of that it now points to an ancient version of your repo. Go to Heishamon/Integrations and you'll see what's wrong. That's something @Egyras has to fix.
