### ISSUE TITLE
Feature request: send firmware version via MQTT

### ISSUE THREAD

**Issue by kamaradclimber** [heishamon/HeishaMon#388]
In order to support https://github.com/kamaradclimber/heishamon-homeassistant/issues/133, it would be very convenient to get the version of the firmware via MQTT messages.

Do you think it would be possible?

**Comment by geduxas** [comment]
I think it will be available in next release. It will apere in MQTT Stats topic as json value;
```"version":3.2```
also for dirty build from githyb page it will will be as Alpha with github HEAD ID.
```"static const char *heishamon_version = \"Alpha-$(git rev-parse --short HEAD)\";"```

**Comment by kamaradclimber** [comment]
Thanks a lot!
https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.3.0 contains usage of this field (when it will be ready)

**Comment by kamaradclimber** [comment]
3.2.3 contains the patch and it works, thanks!
