### ISSUE TITLE
timer with value greater than 999s does not work

### ISSUE THREAD

**Issue by salami738** [heishamon/HeishaMon#405]
Hi, thanks for heishamon, it is very useful!

I found a bug in the rules implementation:

Does **not work** (cannot be saved in the gui)
```
on System#Boot then
  setTimer(1, 1000);
end

on timer=1 then
  #test = 1;
end
```

**Works**
```
on System#Boot then
  setTimer(1, 999);
end

on timer=1 then
  #test = 1;
end
```

I think there is a overflow for values > 999s

**Comment by blb4github** [comment]
I believe it's something else, I have timer of 7200 seconds which works as expected.
setTimer(9,7200);

**Comment by salami738** [comment]
It works now. Ticket can be closed.
