### ISSUE TITLE
Question: Using external data sources in rules

### ISSUE THREAD

**Issue by vzamanillo** [heishamon/HeishaMon#408]
Hi!!

It is possible to use external data sources into rules to initialize variables? I mean, e.g, reading a JSON file.

It is possible to make a http request? I was checking the (awesome) CurlyMoo's rules project but I think it is not possible, just for confirm.

I know we can do this using third party software (HA + NodeRed, others...) but I would like to make it without.

**Comment by CurlyMoo** [comment]
Nope, not possible at the moment. I also first want to have the current library update merged.

https://github.com/IgorYbema/HeishaMon/pull/121
