### ISSUE TITLE
Issues when room thermostat mode is selected in device

### ISSUE THREAD

**Issue by kgiedrius** [heishamon/HeishaMon#412]
When room thermostat is used (not outdoor temperature curve) - Home assistant climate thermostat range is wrong. -5 .. +5, but it should be 5 .. 30
When + or - is clicked - thermostat resets to +5  and heatpump stops heating :)

<img width="801" alt="image" src="https://github.com/Egyras/HeishaMon/assets/15670549/9c2adeb1-4996-43db-a92b-41255a40010a">

**Comment by geduxas** [comment]
Do you use integration or manual mqtt setup?

**Comment by kgiedrius** [comment]
I use integration, and this thermostat is good (-5 .. +5) when outdoor curve is used for heating, but then room thermostat - not ok.

**Comment by geduxas** [comment]
Ok so issues should rised in integration repository, this is only for gateway. 

https://github.com/kamaradclimber/heishamon-homeassistant

Please close it here.
