### ISSUE TITLE
New heat pump multi split model

### ISSUE THREAD

**Issue by pvvn3d** [heishamon/HeishaMon#413]
Hello,
Im using Heishamon with EcoFlex model. Its 8kW all in one model + duct type air conditioner. Outdoor unit is a multisplit one (CU-2WZ71YBE5).

All works great.  Model for Heisha is unknown and also i dont see data from duct unit.
I suspect we can read that data from duct unit because in service cloud i can see it.

So, if i get small help how to check/read this data i can do that for Heisha project upgrade.

**Comment by MiG-41** [comment]
First , could you Togle hexdump log , and pass from Console all lines with hex values , with are comming just after "Received 203 bytes data" ?

**Comment by IgorYbema** [comment]
And please share the data which is working now. Please also show http://heishamon.local/debug hexdump

**Comment by pvvn3d** [comment]
Ok, here is the hexdump:
`data: 71 C8 01 10 56 55 52 49 00 A5 00 01 00 00 00 00 00 00 00 00 59 15 11 55 96 15 55 55 55 99 02 00                   
 data: 00 00 00 00 00 00 7B 80 80 80 B4 71 71 FF 99 00 00 00 00 00 00 00 00 00 00 00 80 85 5B 8A 85 85                    
  data: D0 7B 78 1F 7E 1F 1F 79 79 8D 8D A7 9B 71 8F B7 A3 7B 8F 94 84 7B 8F 8A 94 9E 8F 8A 94 9E 85 8F                    
  data: 8A 15 79 7A BC 3D 7E 7C 0B 7C 7E A8 00 00 55 75 55 21 A9 15 59 05 1B 12 66 09 00 00 00 00 00 00                    
  data: 00 E2 D4 0D 53 88 02 D5 0C 59 88 97 00 AE 86 97 97 32 32 9A AC 32 32 32 7B 9A 97 8D 96 96 86 85                    
  data: 80 80 8A 30 01 01 01 01 01 B9 08 29 5B 01 01 79 79 01 01 45 11 00 01 0D 00 46 00 00 0B 00 00 09                    
  data: 01 01 01 01 01 01 01 02 00 00 11`

And here is a data from heisha monitor:


<html>
<body>


TOP0 | Heatpump_State | 1 | On
-- | -- | -- | --
TOP1 | Pump_Flow | 9.44 | l/min
TOP2 | Force_DHW_State | 0 | Disabled
TOP3 | Quiet_Mode_Schedule | 0 | Disabled
TOP4 | Operating_Mode_State | 0 | Heat
TOP5 | Main_Inlet_Temp | 23.50 | °C
TOP6 | Main_Outlet_Temp | 24 | °C
TOP7 | Main_Target_Temp | 31 | °C
TOP8 | Compressor_Freq | 25 | Hz
TOP9 | DHW_Target_Temp | 52 | °C
TOP10 | DHW_Temp | 46 | °C
TOP11 | Operations_Hours | 3328 | hours
TOP12 | Operations_Counter | 4421 | count
TOP13 | Main_Schedule_State | 0 | Disabled
TOP14 | Outside_Temp | 6 | °C
TOP15 | Heat_Energy_Production | 200 | Watt
TOP16 | Heat_Energy_Consumption | 600 | Watt
TOP17 | Powerful_Mode_Time | 0 | Off
TOP18 | Quiet_Mode_Level | 0 | Off
TOP19 | Holiday_Mode_State | 0 | Off
TOP20 | ThreeWay_Valve_State | 0 | Room
TOP21 | Outside_Pipe_Temp | 4 | °C
TOP22 | DHW_Heat_Delta | -6 | K
TOP23 | Heat_Delta | 4 | K
TOP24 | Cool_Delta | 5 | K
TOP25 | DHW_Holiday_Shift_Temp | -15 | K
TOP26 | Defrosting_State | 0 | Disabled
TOP27 | Z1_Heat_Request_Temp | 0 | °C
TOP28 | Z1_Cool_Request_Temp | 0 | °C
TOP29 | Z1_Heat_Curve_Target_High_Temp | 39 | °C
TOP30 | Z1_Heat_Curve_Target_Low_Temp | 27 | °C
TOP31 | Z1_Heat_Curve_Outside_High_Temp | 15 | °C
TOP32 | Z1_Heat_Curve_Outside_Low_Temp | -15 | °C
TOP33 | Room_Thermostat_Temp | 22 | °C
TOP34 | Z2_Heat_Request_Temp | 0 | °C
TOP35 | Z2_Cool_Request_Temp | 0 | °C
TOP36 | Z1_Water_Temp | -78 | °C
TOP37 | Z2_Water_Temp | -78 | °C
TOP38 | Cool_Energy_Production | 0 | Watt
TOP39 | Cool_Energy_Consumption | 0 | Watt
TOP40 | DHW_Energy_Production | 0 | Watt
TOP41 | DHW_Energy_Consumption | 0 | Watt
TOP42 | Z1_Water_Target_Temp | 31 | °C
TOP43 | Z2_Water_Target_Temp | 44 | °C
TOP44 | Error | No error | Error
TOP45 | Room_Holiday_Shift_Temp | -15 | K
TOP46 | Buffer_Temp | -78 | °C
TOP47 | Solar_Temp | -78 | °C
TOP48 | Pool_Temp | -78 | °C
TOP49 | Main_Hex_Outlet_Temp | 25 | °C
TOP50 | Discharge_Temp | 24 | °C
TOP51 | Inside_Pipe_Temp | 24 | °C
TOP52 | Defrost_Temp | 4 | °C
TOP53 | Eva_Outlet_Temp | 0 | °C
TOP54 | Bypass_Outlet_Temp | 0 | °C
TOP55 | Ipm_Temp | 10 | °C
TOP56 | Z1_Temp | 24 | °C
TOP57 | Z2_Temp | -128 | °C
TOP58 | DHW_Heater_State | 0 | Blocked
TOP59 | Room_Heater_State | 0 | Blocked
TOP60 | Internal_Heater_State | 0 | Inactive
TOP61 | External_Heater_State | 0 | Inactive
TOP62 | Fan1_Motor_Speed | 430 | r/min
TOP63 | Fan2_Motor_Speed | 0 | r/min
TOP64 | High_Pressure | 18.0 | Kgf/cm2
TOP65 | Pump_Speed | 2100 | r/min
TOP66 | Low_Pressure | 0 | Kgf/cm2
TOP67 | Compressor_Current | 3.6 | Ampere
TOP68 | Force_Heater_State | 0 | Inactive
TOP69 | Sterilization_State | 0 | Inactive
TOP70 | Sterilization_Temp | 60 | °C
TOP71 | Sterilization_Max_Time | 60 | Minutes
TOP72 | Z1_Cool_Curve_Target_High_Temp | 15 | °C
TOP73 | Z1_Cool_Curve_Target_Low_Temp | 10 | °C
TOP74 | Z1_Cool_Curve_Outside_High_Temp | 30 | °C
TOP75 | Z1_Cool_Curve_Outside_Low_Temp | 20 | °C
TOP76 | Heating_Mode | 0 | Comp. Curve
TOP77 | Heating_Off_Outdoor_Temp | 20 | °C
TOP78 | Heater_On_Outdoor_Temp | -5 | °C
TOP79 | Heat_To_Cool_Temp | 15 | °C
TOP80 | Cool_To_Heat_Temp | 10 | °C
TOP81 | Cooling_Mode | 0 | Comp. Curve
TOP82 | Z2_Heat_Curve_Target_High_Temp | 55 | °C
TOP83 | Z2_Heat_Curve_Target_Low_Temp | 35 | °C
TOP84 | Z2_Heat_Curve_Outside_High_Temp | 15 | °C
TOP85 | Z2_Heat_Curve_Outside_Low_Temp | -5 | °C
TOP86 | Z2_Cool_Curve_Target_High_Temp | 15 | °C
TOP87 | Z2_Cool_Curve_Target_Low_Temp | 10 | °C
TOP88 | Z2_Cool_Curve_Outside_High_Temp | 30 | °C
TOP89 | Z2_Cool_Curve_Outside_Low_Temp | 20 | °C
TOP90 | Room_Heater_Operations_Hours | 69 | hours
TOP91 | DHW_Heater_Operations_Hours | 10 | hours
TOP92 | Heat_Pump_Model | 255 | unknown
TOP93 | Pump_Duty | 93 | Duty
TOP94 | Zones_State | 0 | Zone1 active
TOP95 | Max_Pump_Duty | 254 | Duty
TOP96 | Heater_Delay_Time | 10 | Minutes
TOP97 | Heater_Start_Delta | -4 | K
TOP98 | Heater_Stop_Delta | -2 | K
TOP99 | Buffer_Installed | 0 | Disabled
TOP100 | DHW_Installed | 1 | Enabled
TOP101 | Solar_Mode | 0 | Disabled
TOP102 | Solar_On_Delta | 10 | K
TOP103 | Solar_Off_Delta | 5 | K
TOP104 | Solar_Frost_Protection | 5 | °C
TOP105 | Solar_High_Limit | 80 | °C
TOP106 | Pump_Flowrate_Mode | 0 | DeltaT
TOP107 | Liquid_Type | 0 | Water
TOP108 | Alt_External_Sensor | 0 | Disabled
TOP109 | Anti_Freeze_Mode | 1 | Enabled
TOP110 | Optional_PCB | 0 | Disabled
TOP111 | Z1_Sensor_Settings | 0 | Water Temperature
TOP112 | Z2_Sensor_Settings | 0 | Water Temperature
TOP113 | Buffer_Tank_Delta | 5 | K
TOP114 | External_Pad_Heater | 0 | Disabled


</body>
</html>


All data is looking good, except one topic : <html>
<body>


TOP36 | Z1_Water_Temp
-- | --



</body>
</html>

I have 1 zone pump option, dont have additional zone and optional pcb board installed.

For now i using heisha in "listen only mode" but few days ago im using only heisha to control heat pump.
Thing i tested:
Basic control eg. on/off, temperatures control, silent modes, powerful mode is working good.
Parameters for pump speed, heat delta also works.

Thanks for your interest, i'm appreciated that.

**Comment by MiG-41** [comment]
I can see , that CZ-TAW1 requesting extra data... Do you see in log similar hexlog , but starts from  "71 C8 01 **21** ...."

If yes , could you please pass booth from the same time ? ( so also these what is passed already)

**Comment by IgorYbema** [comment]
> I can see , that CZ-TAW1 requesting extra data... Do you see in log similar hexlog , but starts from "71 C8 01 **21** ...." (these 21 as 4th byte is difference)
> 
> If yes , could you please pass booth from the same time ? ( so also these what is passed already)

I believe 0x21 is only used for the K/L versions. Maybe this duct extensions uses another value. To be sure we need the dump the CZ-taw1 from his system.

@pvvn3d please connect the cz-taw1 back and put heishamon on listen only. Then copy paste some console log from heishamon when it is running together with cz-taw1

**Comment by MiG-41** [comment]
Yes , looks like after reboot CZ-TAW1 is not asking anymore for 0x21 ,when i feed it with this querty, probably some restovers from L version... So nevermind. 
@pvvn3d ,can you tell exact name of this additional datas for duct in service cloud  ?

Also would be good ,if you  made a PR in here filling all datas: https://github.com/Egyras/HeishaMon/blob/master/HeatPumpType.md
I cen see , that service cloud is recognizing it as: IDU:WH-ADF0309J3E5CM ODU:CU-2WZ71YBE5

EDIT: And for your information TOP36 is valid , when you have optional PCB( then Water temp zone 1 sensor is obligatory) , so everything ok.

**Comment by pvvn3d** [comment]
@IgorYbema 
Both devices is already connected all the time. When i write hex dump in 1st post it is also connected in that way.
How can i read hex dump from cz-taw module like you suggested ?

@MiG-41 
I'm trying to get access to service cloud but my installer does not really want to provide access. But i'm working on it, if i must i change installer to another one :) When i get this acces i let you know immediately.

**Comment by MiG-41** [comment]
Ok , you wrote ,that in service cloud you see some data for duct unit , thought that you have acces to it....
Becouse from your querty ,with i send to Service Cloud i can't see anything more ... Only standard data for HP.

**Comment by pvvn3d** [comment]
I see it on my installer pc... 
To check it you need to have instant acces to the duct values or screenshot will be enaught ?

**Comment by MiG-41** [comment]
Screenshot enough..

**Comment by pvvn3d** [comment]
I check my gallery on phone and i found it...
![_20231110_144929](https://github.com/Egyras/HeishaMon/assets/123091669/6941593a-1dde-47db-9c13-4174d2bf6a62)

Its in polish language but i guessing by your name you are pole :)

For other one starting from left upper corner of duct table is:
Status : on/off
Mode : Heat/Cool/Dry/Went
Temperature set: 23
Fan speed: 
nanoeX: on/off
ECONAVI: 
Outside temperature: 1
Error:

Thanks

**Comment by MiG-41** [comment]
In service cloud i have only upper part , no below table ( this is not a combined picture ?) 
In this case looks like this inner unit S-71WF3E is communicating with CZ-TAW1 other way... 
Please  past log ( with hexdump switched) ,as @IgorYbema  asked :

> @pvvn3d please connect the cz-taw1 back and put heishamon on listen only. Then copy paste some console log from heishamon when it is running together with cz-taw1

**Comment by pvvn3d** [comment]
In service cloud ? How can you see my pump in service cloud? :o 
This ofcourse not combined picture.
Here is log from heisha console (cz-taw i also connectd):
`Sun Nov 12 11:59:45 2023 (485579284): Heishamon stats: Uptime: 5 days 14 hours 52 minutes 59 seconds ## Free memory: 75% ## Heap fragmentation: 3% ## Max free block: 28808 bytes ## Free heap: 29552 bytes ## Wifi: 96% (RSSI: -52) ## Mqtt reconnects: 5 ## Correct data: 99.99%
Sun Nov 12 11:59:46 2023 (485580554): Received 203 bytes data
Sun Nov 12 11:59:46 2023 (485580558): data: 71 C8 01 10 56 55 52 49 00 65 00 01 00 00 00 00 00 00 00 00 59 15 11 55 96 15 55 55 55 99 02 00 
Sun Nov 12 11:59:46 2023 (485580564): data: 00 00 00 00 00 00 85 80 80 80 B4 71 71 FF 99 00 00 00 00 00 00 00 00 00 00 00 80 85 5B 8A 85 85 
Sun Nov 12 11:59:46 2023 (485580576): data: D0 7B 78 1F 7E 1F 1F 79 79 8D 8D A7 9B 71 8F B7 A3 7B 8F 94 85 7B 8F 8A 94 9E 8F 8A 94 9E 85 8F 
Sun Nov 12 11:59:46 2023 (485580589): data: 8A 15 79 7A BC 3D 7E 7C 0B 7C 7E A8 00 00 55 75 55 21 A9 15 59 05 11 12 66 09 00 00 00 00 00 00 
Sun Nov 12 11:59:46 2023 (485580601): data: 00 E2 D4 0D 53 88 02 D5 0C 59 88 A4 00 AB 86 9F A4 32 32 A4 AC 32 32 32 85 A4 A4 B7 96 9F 80 80 
Sun Nov 12 11:59:46 2023 (485580613): data: 80 80 99 75 01 3B 3E 01 01 55 16 41 82 46 01 51 01 01 01 68 11 00 2D 0D 00 46 00 00 0B 00 00 09 
Sun Nov 12 11:59:46 2023 (485580625): data: 01 0E 29 01 01 01 01 02 00 00 01 
Sun Nov 12 11:59:46 2023 (485580631): Checksum and header received ok!
Sun Nov 12 11:59:46 2023 (485580646): received TOP65 Pump_Speed: 3200`

Comunication between units looks like follows:
Duct unit is connected only to outdoor unit (communication and power)
Tank unit is also connected to outdoor unit (communication and power)
Main power is connected to tank unit.
I have service manual for this model if you need that.

If you need more complicated information i think its not problem for me because im a automatician/electrician.
But in ESP and similar things im a newbie..

**Comment by MiG-41** [comment]
I can't see your pump in Service Cloud . I'm sending your responce to service cloud , with gives my HP identical to yours ( only type , so it is not precisly yours).
We need some more logs , then only one answer , especialy during start of CZ-TAW1 ( power up) , then there is some handshake with could be interesting , and enything else then "71 C8 01 10 ..."
Best ,if you make a log file ,when you attach CZ-TAW1 to power.
Could you join slack ? ( link in github) ? https://join.slack.com/t/panasonic-wemos/shared_invite/enQtODg2MDY0NjE1OTI3LTgzYjkwMzIwNTAwZTMyYzgwNDQ1Y2QxYjkwODg3NjMyN2MyM2ViMDM3Yjc3OGE3MGRiY2FkYzI4MzZiZDVkNGE

**Comment by tbrasser** [comment]
Any updates here? I just received my ecoflex and looking to drive it fully locally :)

**Comment by Hopobcn** [comment]
Hi, I would also be interested on `WH-ADF0309J3E5CM + S-71WF3E + CU-2WZ71YBE5`. @pvvn3d would it be possible for you to explain what works and what doesn't?

**Comment by pvvn3d** [comment]
Hi
Unfortunately, I no longer use the ecoflex because I sold my house.
As for the controls, everything works as it does with a standard Aquarea pump – all data and setting changes work correctly.

The only thing Heisha doesn't show is the unit type, but that's a detail.

However, there's no air conditioner control or data. I've had rather poor experiences with this system; Panasonic itself called it a "strange unit."

**Comment by tbrasser** [comment]
Poor on what level? It wan't as efficient as advertised?  Anyway, I will work with the devs to see whether we can get A2A to show up, once my system is up and running.

thanks for replying!

**Comment by pvvn3d** [comment]
Certainly a lower COP than a typical unit without air conditioning. There were problems maintaining continuous operation at above-freezing temperatures if the air conditioner was turned off. The system works best when the water and air are running, and I recommend using it that way. There's one drawback: the defrost icon doesn't display on the unit, and the Heisha doesn't indicate this status either. The defrost icon only appears when defrosting is forced via the controller, and defrosting is performed by the domestic hot water tank. The unit was perfectly matched and serviced by a person from Panasonic's central service center, so there's no question of installation errors. I wouldn't buy it again.

**Comment by tbrasser** [comment]
I'll try and respond here with my own experiences after I get familiar. In my case I was considering using air for bulk of heating and only using water for the few areas I can't lay ducts to. Basically removing as many hydronic radiators (currently 8 on condensating gas combi boiler) as I can get away with.

So potentially that is then how ecoflex operates best? Again I'll try to post experiences here when I can. Thanks for any piece of info given, it's hard to come by on this system.

**Comment by pvvn3d** [comment]
I used the system for 3 years, if you have any questions or doubts - write, I will try to help. If you'll be using an air rather than a water unit, it's better for you. This outdoor unit is closer to air conditioners than a typical "water" unit.
