### ISSUE TITLE
Loading the new rule fails.

### ISSUE THREAD

**Issue by McMagellan** [heishamon/HeishaMon#415]
Since my rules have gotten bigger and bigger, I've often had problems uploading them. I'm using version 3.2.3.
There are different variants of the error. Today I was able to document a process and it is reproducible. I hope this post is helpful in finding the error.

When I upload a new rule, I first empty the window and confirm the empty rule with SAVE.
If the rule text file was then copied in (see appendix Projekt7.13a.txt) and confirmed with SAVE, the upload process gets stuck. 
I recorded this process in the console window that was open at the same time (see Appendix Dump1 Reaching end of read.txt). 
The (Dump2 Reaching end of read.txt) file contains a summary of the "Reaching end of read" messages.

However, if I change this rule file by, for example, inserting a blank line with return in the first 20 lines, the rule is accepted. 
(See appendix [Dump3 Reaching end of read.txt)

This process can be reproduced despite a reboot or hardware reset.

[Projekt7.13a.txt](https://github.com/Egyras/HeishaMon/files/13322587/Projekt7.13a.txt)

[Dump1 Reaching end of read.txt](https://github.com/Egyras/HeishaMon/files/13322591/Dump1.Reaching.end.of.read.txt)

[Dump2 Reaching end of read.txt](https://github.com/Egyras/HeishaMon/files/13322592/Dump2.Reaching.end.of.read.txt)

[Dump3 Reaching end of read.txt](https://github.com/Egyras/HeishaMon/files/13322599/Dump3.Reaching.end.of.read.txt)

**Comment by CurlyMoo** [comment]
I'm first fully invested into getting this PR merged: https://github.com/IgorYbema/HeishaMon/pull/121. When that's done, i will look into these webserver issues.
