### ISSUE TITLE
MQTT for Heat_Power_Production and Heat_Power_Consumption = 0

### ISSUE THREAD

**Issue by Roukie686868** [heishamon/HeishaMon#416]
I did an upgrade to the latest version (3.2.3) last night and since then the MQTT value for both Heat_Power_Production (TOP15) and Heat_Power_Consumption (TOP16) are staying at 0 (Zero) while the webpage is showing realistic values like 3600 Watt and 600 Watt for both topics.

**Comment by Roukie686868** [comment]
I did a downgrade to V3.2 and the result stayed the same. Then I went back to V3.1 that I ran earlier and now the topic is being published again.

**Comment by geduxas** [comment]
From 3.2 all \*\_Energy_* topics renamed to \*\_Power_*

So depending on system you're using. If you configured manually mqtt Topic, please make changes.

**Comment by Roukie686868** [comment]
Thanks for the help. It all works again now

**Comment by geduxas** [comment]
Please close issues if it's resolved :)

**Comment by Roukie686868** [comment]
Yes will doOn Nov 12, 2023, at 17:00, geduxas ***@***.***> wrote:﻿
Please close issues if it's resolved :)
