### ISSUE TITLE
No more data after update to 3.2.3

### ISSUE THREAD

**Issue by woupi** [heishamon/HeishaMon#418]
Hello,

I updated Heishamon today. I had installed version 3.1 and unfortunately didn't realize that version 3.2.3 is only a beta.
After the update to 3.2.3, no more data was displayed.
Unfortunately, a downgrade to 3.1 did not change anything.

I would be very grateful for a hint.

![image](https://github.com/Egyras/HeishaMon/assets/98451301/d4ee564b-473a-4b89-b7f7-6e12c918f44a)

**Comment by geduxas** [comment]
Did you update to 3.2 and only after to 3.2.2? Also do you use expansion card?

**Comment by woupi** [comment]
Did you update to 3.2 and only after to 3.2.2?
Yes, sorry
Also do you use expansion card?
I have purchased HeishaMon Opentherm PCB.

**Comment by geduxas** [comment]
Ok, so think it's 3.2 fault. So upgrade latest version for heishamon, i think it's 3.2.3. 
And to recover data, your pump needs to be switched off completely. So turn of your pump, and disconnect from power supply. Wait for couple second's and turn it on again.

**Comment by woupi** [comment]
Thank you very much, it worked perfectly.
The data is back.
