### ISSUE TITLE
Info: MQTT- Topics Energy renamed to Power in 3.2.3

### ISSUE THREAD

**Issue by Tomtheripper** [heishamon/HeishaMon#420]
Hi,

just for Information:
in 3.2.3 some MQTT - Topics "Energy" has been renamed to "Power".
For example 
old "Heat_Energy_Production"
new "Heat_Power_Production".

Noticed by Grafana Time Series, from Firmware 3.1.0 to 3.2.3

Best regards
Thomas

**Comment by JockelBln** [comment]
This has already changed with v3.2 and is also described in the release notes 😉

**Comment by cuchipandy** [comment]
But not changed in last HA heishamon.yaml

**Comment by geduxas** [comment]
> But not changed in last HA heishamon.yaml

it always was incomplete, and i think will be, now we have HA integration which practically changes manual configuration.., Also feel free to contribute and PR changes to yaml if you think it's important :)

**Comment by cuchipandy** [comment]
> > But not changed in last HA heishamon.yaml
> 
> it always was incomplete, and i think will be, now we have HA integration which practically changes manual configuration.., Also feel free to contribute and PR changes to yaml if you think it's important :)

Thanks... I will PR this update. I should move to integration but i am lazy in redo all renaming entities work jeje

**Comment by HighlyCompressedAir** [comment]
Fixed #423, this issue can be closed.
