### ISSUE TITLE
Heat_power_Consumption is different then Watts used by S0 Port

### ISSUE THREAD

**Issue by Roukie686868** [heishamon/HeishaMon#421]
Love the HeishaMon module in my Panasonic but I'm confused by the energy consumption numbers. On the S0 port 1 I'm reading a very constant 986 Watts to my unit but TOP16 reports 800 Watt. Where does this difference come from. 
<img width="401" alt="800Watt" src="https://github.com/Egyras/HeishaMon/assets/38638852/5c0cf045-cbdc-40b1-b46b-78f226145ff6">
<img width="375" alt="983Watt" src="https://github.com/Egyras/HeishaMon/assets/38638852/d6a723b2-b136-4e0f-92f4-edd1ede08007">

**Comment by MiG-41** [comment]
All topics (including TOP15 and TOP15) are mirrored from this ,What HP "says".   So if HP is showing the same , there is nothing wrong with Heishamon. 
HP shows something with is far from any measurment , it is just guessing acc to actual compressor frequency , outside temp. ect.
This is a question to Panasonic ,why is not measuring precisly and corectly.

**Comment by Roukie686868** [comment]
Thanks for the answer. Might be that Panasonic is subtracting the energy used by the circulation pump or something as the number is about 200 Watts lower no mater the frequency of the Compressor. I'll close the topic.

**Comment by Roukie686868** [comment]
Closed
