### ISSUE TITLE
Add 9KW model WH-SXC09H3E5

### ISSUE THREAD

**Issue by dalis2000** [heishamon/HeishaMon#422]
Please add to the model list:
E2 CF 0D 77 09 12 D0 0C 05 11 | WH-SXC09H3E5 | WH-UX09HE5 | kit-WXC09H3E5 | 9 | 1ph | T-CAP

Debug output:
data: 71 C8 01 10 56 95 52 A1 00 55 00 00 00 00 00 00 00 00 00 00 2A 15 11 55 16 96 55 05 05 00 00 00 
data: 00 00 00 00 00 00 82 80 80 80 B4 71 71 97 99 00 00 00 00 00 00 00 00 00 00 00 80 85 29 8A 85 85 
data: D0 7B 78 1F 7E 1F 1F 79 79 8D 8D A0 9A 7B 8F B7 A3 7B 8F 94 85 71 8F 8A 94 9E 8F 8A 94 9E 85 8F 
data: 8A 03 3D 7A BD 0B 00 00 00 00 00 00 00 00 95 75 55 21 A9 15 59 05 09 12 65 00 00 00 00 00 00 00 
data: 00 E2 CF 0D 77 09 12 D0 0C 05 11 A0 00 B1 88 9C A0 A0 32 9F AB 32 32 32 82 9F A1 AD 9A 9C 80 82 
data: 81 91 92 6E 01 19 18 00 00 E4 0F 1F 51 23 27 1A 01 01 01 D7 0E 00 88 0D 00 01 00 00 01 00 00 0A 
data: 02 06 18 01 01 01 01 00 00 00 22 

the model WH-SXC09H3E5 is present in HeatPumpType.md at value 2 but my aquarea returns a different byte "0C" instead of "OB" in third to last place so i have "TOP92	Heat_Pump_Model	  255	unknown"

**Comment by HighlyCompressedAir** [comment]
This one is still waiting @IgorYbema
