### ISSUE TITLE
Command point are not available in MQTT

### ISSUE THREAD

**Issue by Skol6** [heishamon/HeishaMon#424]
Hi,

which setting do I have to add on HeishaMon to get the command points in MQTT?

- Listen only mode is deactivated
- rest of the data is correct delivered to MQTT
- no command mode is shown

![image](https://github.com/Egyras/HeishaMon/assets/94216949/b72f59bb-43ae-4672-8882-d35abb1bc277)

used firmware ist 3.1
Heatpump model WH-MDC07J3E5

Regards

**Comment by geduxas** [comment]
You just need to create command topic with according command and that should  be without retaining flag. Heishamon will not create command topic, it just listen for it. 

More details:
https://github.com/Egyras/HeishaMon/blob/master/MQTT-Topics.md#command-topics

**Comment by Skol6** [comment]
Thanks for the information. I thought Heishamon creates the values automatically including information in MQTT.
Would be much easier and helpful :)

**Comment by geduxas** [comment]
> Thanks for the information. I thought Heishamon creates the values automatically including information in MQTT. Would be much easier and helpful :)

No, that's why it should be without retaining flag. Command should apperes once.. becouse eatch time it will be executed. 

Please close issue if it's resolved

**Comment by Skol6** [comment]
OK now I have tried to set the MQTT value:
`setState("mqtt.0.panasonic_heat_pump.commands.SetPump", 1, true);`
BUT: feedback was that this data point does not exist?
`State "mqtt.0.panasonic_heat_pump.commands.SetPump" not found`

Also I do need the retain flag, to set the energy meter correctly in iobroker.

**Comment by ClassicGOD** [comment]
I think you misunderstand how MQTT protocol works. "Retained" flag means that the message will be repeated to every client connecting to the MQTT broker and subscribing to the given topic. Retained messages are useful for keeping "last known state" but not good for an "instant" uses like commands for HeishaMon.

If you send a retained message to a command topic the command will be executed every time HeishaMon reconnects to your MQTT broker for any reason (disconnect, reboot, anything). You do not want that (usually) so don't do that.  

Regarding your error - I'm not familiar with ioBroker but with quick google I assume you are trying to use the pubsubclient library for Arduino so you should probably use client.publish (assuming 'client' is your pubsubclient obj)

**Comment by mlapp** [comment]
> OK now I have tried to set the MQTT value: `setState("mqtt.0.panasonic_heat_pump.commands.SetPump", 1, true);` BUT: feedback was that this data point does not exist? `State "mqtt.0.panasonic_heat_pump.commands.SetPump" not found`
> 
Try
sendTo('mqtt.0', 'sendMessage2Client', { 'topic': 'panasonic_heat_pump/commands/SetPump', 'message': ('1') });
