### ISSUE TITLE
2 pieces of HeishaMon in one home assistant/InfluxDB/Grafana

### ISSUE THREAD

**Issue by acefromthebase** [heishamon/HeishaMon#427]
I have two heatpumps. Each of them has its own HeishaMon. I have inserted it into Homeassistant under Adons and can also see all the data from the two heat pumps. But how can I display both heat pumps or Heishamon in InfluxDB and then further in Grafana. I only ever see one HeishaMon. I named them differently. One is called heishamon_eg and the other is called heishamon_og. Each apartment has its own heat pump. I hope you understand what I mean :-)

can everybody help me please or can someone explain to me step by step how I can do this???

Thanks

**Comment by geduxas** [comment]
It's depends how you get Heishamon data to grafana. Though home assistant, or you picking it from mqtt with telegref?

**Comment by acefromthebase** [comment]
I send the data from Heishamon to HomeAssistant via MQTT Broker. I also installed the heishamon integration in homeassistant. So what's the best way to do this now? that I get the data separately from both heishamons in influxDB and then in Grafana. I currently only see Heishamon once in Grafana.

**Comment by geduxas** [comment]
Question is how your data is getting into influxdb? Is it from homeassistant or from mqtt?

**Comment by acefromthebase** [comment]
How can i see this? I think its over mqtt

**Comment by BurgerMario** [comment]
Did HA see all entidys? Of Both Heishamon with different names?

**Comment by geduxas** [comment]
If it's related to HA integration, so it will be wrong place. Use integration repository.
