### ISSUE TITLE
Set External Heater Off

### ISSUE THREAD

**Issue by schwieni01** [heishamon/HeishaMon#430]
Is it possible to disable the backup heater in heishamon?  
<img width="432" alt="Bildschirmfoto 2023-12-01 um 18 59 10" src="https://github.com/Egyras/HeishaMon/assets/152644544/077ac502-918a-42e7-8d8e-0250d0605569">

**Comment by MiG-41** [comment]
No , this values(Backup Heater and Cool Mode)  are "read only" , it is possible to read status , but you can't set it . Only manually from controler you can change state.

**Comment by schwieni01** [comment]
Unfortunately the backup heater can't disabled from the panasonic remote. It can only be disabled from a windows-PC  directly connected with cn-cnt port. 

Witout electric current on the backup-heater, the heat pump will get an error, if the water outlet temperatur is below 28° and the heatpump need to deice

**Comment by geduxas** [comment]
> Unfortunately the backup heater can't disabled from the panasonic remote. It can only be disabled from a windows-PC directly connected with cn-cnt port.
> 
> Witout electric current on the backup-heater, the heat pump will get an error, if the water outlet temperatur is below 28° and the heatpump need to deice

Do you have more detail about software and cable?

**Comment by MiG-41** [comment]
Many people where able to disable Heater thru that menu. What HP you have , and are you able to enter to that menu ?

**Comment by schwieni01** [comment]
My heatpump is an WH-MDC05J3E5. The manual (Service Manual Mini Monobloc R32 Serie J.pdf) tells me on page 120, that on deice condition the backup heater is needed, if the water inlet temperature is below 27°.  
I'm not able to deactivate the backup heater on the panasonic remote, since I can't find it on the panasonic remote.

The manual tells me, to deactivate the heater, I need to connect the PC to the cn-cnt port using an usb-cn-cnt cable, which I haven't done yet.

<img width="716" alt="Bildschirmfoto 2023-12-01 um 23 08 26" src="https://github.com/Egyras/HeishaMon/assets/152644544/d7e8285f-062e-479f-aa93-472b7605d058">

**Comment by MiG-41** [comment]
Turn off HP ,and for 10seconds hołd buttons menu+down+left and you will be in this menu.
It is written in page with you attached in first post.

**Comment by Egyras** [comment]
> Unfortunately the backup heater can't disabled from the panasonic remote. It can only be disabled from a windows-PC directly connected with cn-cnt port.
> 
> Witout electric current on the backup-heater, the heat pump will get an error, if the water outlet temperatur is below 28° and the heatpump need to deice

it wont generate anything, I'am using without it for 5 years. To disable or to leave enabled depends if your house warm enough and other things.

**Comment by MiG-41** [comment]
It will generate an errors when you simply cut off electricity to heater ( i.e. by turn off circuit breaker inside HP ). 
It won't generate errors when you turn it of in Custom menu.   And it is possible to get to that menu via HP controller , don't need to have PC with service program connected....

**Comment by HighlyCompressedAir** [comment]
Not possible, this issue can be closed.
