### ISSUE TITLE
Typo in decode.h

### ISSUE THREAD

**Issue by stjerno** [heishamon/HeishaMon#431]
For my "IDU:WH-ADC0916H9E8, ODU:WH-UX12HE8" setup I get no heat_pump model.

Narrowed it down to a typo in decode.h

HeishaMon/decode.h
"IDU:WH-ADC0916H9E8, ODU:WH-UX12HE8", //13

0xE2, 0xCF, 0x0C, 0x74, 0x09, 0x12, 0xD0, **0x0D**, 0x95, 0x05, //13
0xE2, 0xCF, 0x0C, 0x74, 0x09, 0x12, 0xD0, **0x0C**, 0x95, 0x05, //My reading

So for above entry hex #8 0x0D should be 0x0C.

**Comment by IgorYbema** [comment]
Hi,
This is not a type. You just have a newer revision of the same model. We need to add that to the list

**Comment by stjerno** [comment]
Hi,
Ok, just for reference I got a H-version 12KW T-CAP but IDU and ODU model numbers match description //13 
Thanks for picking this up.

**Comment by HighlyCompressedAir** [comment]
Still missing.

**Comment by geduxas** [comment]
> Still missing.

@HighlyCompressedAir 

Heatpump model/type decode need;s to be reworked.. for now it's not right way it's done.. 
Truly model number:

$${\color{red}0xE2, 0xCF,\color{green}0x0C, 0x74, 0x09,\color{red}0x12, 0xD0, \color{green}0x0C, 0x95, 0x05}$$ 

should be structured in such way:

## Decoded values
 From | To
:--- | --- 
0xCFE2 | 0xCFE1
0x09740C | 0x09740B
0xD012 | 0xD011
0x05950C | 0x05950B

As usual to protocol, all values should be subtracted by -1.
Next question is what does it means? 
Looking for 2 same pump and different values, one is 0x05950C and another is 0x05950B ..  
i think it somehow related to version/revision/release years.. 
first part i think is related to outdoor unit. and second part is for indoor unit.. 
It could be main PCB version, main PCB firmware version/checksum.. 
Monoblock's also has indoor unit PCB and outdoor unit..
