### ISSUE TITLE
Observation Byte 115

### ISSUE THREAD

**Issue by Celphor** [heishamon/HeishaMon#432]
Just for the records:

Byte 115 changed from hex 15 to 25 during deicing operation when the backup heater came on. And back to 15 after the backup heater went off again.
The backup heater was driven with only one phase (3kW) on my 12kW (H)eisha Split. Backup heater setting was 9kW (byte 25)

The backup heater was not needed during deicing until now when outside temperature went below -8 degrees C.

![image](https://github.com/Egyras/HeishaMon/assets/22246844/1508456b-9759-4d56-be26-6f0418b38692)

**Comment by Celphor** [comment]
![image](https://github.com/Egyras/HeishaMon/assets/22246844/4610210b-9d4c-4f31-90a3-28b610dcd727)

**Comment by IgorYbema** [comment]
Hi, what was the state of TOP60? This should already show the state of the (internal) heater which is used during defrosting.

**Comment by IgorYbema** [comment]
And are you sure this is the backup heater (so internal heater) or do you mean the base pan heater (which defrosts the ice below the external unit) during/after de-icing.

**Comment by Celphor** [comment]
TOP 60 also showed the heater active. Yes, I mean the internal heater, see first screenshot - not the base pan heater. Heater limit was set to -8 degree (TOP 78)

**Comment by IgorYbema** [comment]
Ok, now we need to find out why panasonic would have two places for the same information :)

**Comment by MiG-41** [comment]
To know with exacly heater is turned on :)
I simulate byte 115 with values 25 , 19 and 16 , and in all states in table heater was off:
![image](https://github.com/Egyras/HeishaMon/assets/57936100/34dc298c-826b-47a5-89d1-f7c7501a07c6)

But at the same time in graph:

![image](https://github.com/Egyras/HeishaMon/assets/57936100/1d114b2d-0b46-43f3-b074-6eec1ac98668)

So yes , it represent each heater/state/phase...

**Comment by IgorYbema** [comment]
Ah ok, so byte 115 stands for which phase is turned on (and probably only one is enabled on 1 phase heaters only)

**Comment by MiG-41** [comment]
For 3phase yes , but for singlephase have to be confirmed by someone else.
In 3 phase can be configurations like 3x3kW or 3x1kW , but for singlephase ? Could be also 1x1kW even if conected to the same phase...
I also recall , that i saw 1 phase heater connection(Supply 2 )  ,but 3phase compressor/outdoor (Supply 1 )  - for this not sure ,it was long time ago....

**Comment by IgorYbema** [comment]
It was me :)

**Comment by MiG-41** [comment]
Ok :)  So maybe you also have 3x1kW ? Or for sure it is 1x3kW ?

**Comment by IgorYbema** [comment]
You have got me thinking. Maybe you are right and it is 3x1kW. Haven't got time to open the heatpump now. I'll check later. But is is max 3kW.

**Comment by IgorYbema** [comment]
This is mine. So backup (internal) heater is shared on supply 1 (probably 3x 1kW because it would be way too much on the shared supply 1 if it was 3x3kW). And the external heater (for boiler) is 1 phase
![image](https://github.com/Egyras/HeishaMon/assets/20365971/90c32cc7-c174-41d4-9e72-2f92be7d5075)

**Comment by MiG-41** [comment]
Ok , so Supply 2  doesn't mean Backup heaters... Good to know.
So byte 115 simply represent phisical state of particular relays  RY-HT (L1) , RY-HT (L2) and RY-HT (L3) , no matter about power.

**Comment by MiG-41** [comment]
In singlephase there is only  RY-HT (L3) ,with 3kW heater...
![image](https://github.com/Egyras/HeishaMon/assets/57936100/3044ef0f-288b-45d2-88cd-e96889ff6cad)

**Comment by Celphor** [comment]
In 3 phase Supply 2 looks like this: So it is 1x3kW (=3), 2x3kW (=6), 3x3kW (=9)

![image](https://github.com/Egyras/HeishaMon/assets/22246844/149abecb-21d1-4c8a-b68c-bdc45d6b2c73)

**Comment by MiG-41** [comment]
Igor's HP theoretically is also 3phase , but ok , we know better now what byte 115 means.

**Comment by Celphor** [comment]
So TOP114 limits the maximum of partial heaters and Byte 115 shows which (or how many) phases are currently used by the machine. Have to check when boiling domestic water next time.

**Comment by MiG-41** [comment]
Do you have External heater in DHW ,conected to Booster Heater terminal on PCB  or you use Internal ones in HP ?

**Comment by Celphor** [comment]
I have both.

**Comment by MiG-41** [comment]
but they will not work parallel :)

**Comment by Celphor** [comment]
Of course they do, if you plug the external heater directly to the wall ;-)

**Comment by IgorYbema** [comment]
Super fast DHW heating :)

**Comment by Celphor** [comment]
Since electricity at my dynamic rate was cheap last night I can confirm the the right 6 bits of byte 115 represent one of three phases each (01 = off, 10 = on), starting from left to right.
