### ISSUE TITLE
Panasonic KIT-Z60-UD3 heat pump not response

### ISSUE THREAD

**Issue by jemarr** [heishamon/HeishaMon#433]
Hi.

Thanks for your hard work, it's awesome.

I have a Panasonic KIT-Z60-UD3 (indoor unit CS-Z60UD3E) heat pump machine. As an option there is a Wifi adaptor CZ-TACG1 but I tried your device.

I've used a Wemos D1 mini with level converters as described here connected to CN-CNT. I've done a lot of wemos and ESP8266/ESP32 circuits, so my experience is quite good.

So, Wemos is sending data but Panasonic does not answer any bit.

I've used HeishaMon.ino.d1-v3.1.bin file version

Tx goes to D7 (gpio13)
Rx goes to D8 (gpio15)

D1 (gpio5) goes to Rx gate control, after several seconds this D1 turns high level.

Console data in http://heishamon.local/ shows that data is sent but no response from Panasonic.

Do you know what to do ?

Thanks in advance.

**Comment by geduxas** [comment]
It's not heatpump.. it's more to AC. In GitHub i saw couple projects for AC.. and they're using ESP or ESPHome to control instead of CZ-TACG1.. 

Protocol could be looking similar, but didn't analyze it yet.

https://github.com/DomiStyle/esphome-panasonic-ac/blob/master/README.CZTACG1.md

**Comment by jemarr** [comment]
Oh !!!
Ok thanks for your answer.
I'll try that. I've seen it before but don't like the idea of ESPHOME, i preffer your easier solution.

Thanks !!!
