### ISSUE TITLE
Observation Byte 110

### ISSUE THREAD

**Issue by Celphor** [heishamon/HeishaMon#434]
Default is 0x55

Upper nibble reflects quiet/powerful operation:

0101 = Normal operation, not quiet, not powerful (eg. 0x55)
1001 = Quiet mode (any level) (eg 0x95) (Bit 1&2)
0110 = Powerful mode (any level) (eg 0x65) (Bit 3&4)

Lower nibble does not change in context of quiet/powerful mode

Is it needed in addition to TOP 17 and 18? Yes, because on scheduled operation you don't get the actual state

**Comment by MiG-41** [comment]
Indeed it is indicating Quiet and Powerful operation , but don't see any additional information in byte 110. I scheduled a Quiet mode for some time , and TOP18 was Off , same byte 110 unchanged ( at my 0x85), only icon on display apear. When time arrived , TOP18 gives value , and also byte 110 changed and icon become underlined , but when time passed booth come back to previous values. 
So no additional information for me . Thought , that at least it will represent ikon presence on display.

**Comment by Celphor** [comment]
Can't confirm because I don't use any internal schedule. But it's another piece of the puzzle, even if it's not that useful.
Presumably the the other nibble represents 2 other display states (sterilization, holiday, bivalent, solar?)

**Comment by MiG-41** [comment]
In Service Cloud byte 110 reacts on External SW ,Heat-Cool SW, Powerful (Actual), Quiet (Actual).
