### ISSUE TITLE
S0-metering noisy when Opentherm is used

### ISSUE THREAD

**Issue by jacco-hass** [heishamon/HeishaMon#437]
My (Emat) S0-meters work fine, but once I turn on Opentherm processing, the readings become very noisy (spikes up to 50000 W). I have a Plugwise Anna + Smile thermostat, which is right next to the Heishamon and connected via a thick, short wire. I tried several hardware solutions (STP grounded wire, ferrite beads, different PSU's, condensators to stabilize 5V), but the only solution so far has been to either turn off Opentherm in the settings or to disconnect it altogether.

In the terminal, I noticed that the Heishamon is receiving Opentherm data every second: 
![image](https://github.com/Egyras/HeishaMon/assets/62347605/353cc417-cf84-45e0-b5c4-a96e9456add2)

My theory is that the Heishamon gets overloaded with Opentherm data from my thermostat, somehow messing up the timing. Any suggestions? Is there a way to limit the rate at which Opentherm data is processed?

**Comment by jacco-hass** [comment]
Just tested with a different thermostat (Remeha Celcia 20) and the S0 meters still show very high (erratic) power values.

**Comment by IgorYbema** [comment]
Limiting opentherm isn't possible. It is in the specs for opentherm to send at least one message each second (or something like that). Which version are you using? 

Please try this firmware which is compiled with 160mhz cpu instead of 80mhz cpu speed.

[HeishaMon.ino.d1_mini.zip](https://github.com/Egyras/HeishaMon/files/13678416/HeishaMon.ino.d1_mini.zip)

**Comment by jacco-hass** [comment]
My Heishamon was on the latest version (3.2.3), testing with the 3.2.4-beta that you sent delivers the same results. This is the history from last night, showing the noise on the S0-meter. I physically disconnected the thermostat at 10AM, after which the correct value (~500W) was shown.
![image](https://github.com/Egyras/HeishaMon/assets/62347605/840cce7e-8299-45a8-b2ff-968de29b2642)

Let me know if there's anything I can test/measure to help diagnose the issue!

**Comment by IgorYbema** [comment]
Can you try this one? It disables all log messages about opentherm. So you won't see them in console also. Just to see if skipping the log_messages helps.
[HeishaMon.ino.d1_mini.zip](https://github.com/Egyras/HeishaMon/files/13687610/HeishaMon.ino.d1_mini.zip)

**Comment by IgorYbema** [comment]
Also please check the other value, Watthour, and get the difference over a few minutes. Then calculate it back to Watt (or just post it here so I can calculate it back to Watt for your) to see if the amount of pulses still is correct (if yes, then it is a timing issue, if there are too many pulses, there is a noise issue)

**Comment by jacco-hass** [comment]
Disabling the log messages didn't work, the high peaks are still there.

The average power seems allright, as you can see in this plot. Here, I disconnected the thermostat at ~10AM.
![image](https://github.com/Egyras/HeishaMon/assets/62347605/099a8afe-be0e-401e-bbbc-97b7168da657)

**Comment by IgorYbema** [comment]
Yes looks like it. 500W is 0,5kWh each our and that is what the graph is showing also (maybe a bit more).

The watt is calculated by heishamon by counting the time between two pulses. A pulse is detected by an interrupt from the S0 input. But also the opentherm is interrupt driven. It looks like this messes up the timing for the S0. I'll try to find a solution but I don't think it is easy.

**Comment by IgorYbema** [comment]
Can you please also share your s0 settings in heishamon? pulses per second and the min and max pulse time?

**Comment by jacco-hass** [comment]
The pulse width is approximately 80ms. Average pulse width in Heishamon is 79ms, and I verified this with an oscilloscope:
![image](https://github.com/Egyras/HeishaMon/assets/62347605/59e6c04d-0eb1-409a-a9de-a92195dbbc12)

So I left the S0 settings at default, with 60/100 min/max and 1000 imp/kWh. When Opentherm is off, this works fine and the console reports very little bad pulses.

**Comment by IgorYbema** [comment]
Can you try to make the pulse gap larger? Set min. to for example 20 and max to 200.
I'm guessing that it can't keep up with the 80ms pulse window and for example sometimes sees a pulse of 120ms wide. It will then ignore that pulse (because it is out of the window). It will however grab the last edge of the pulse for the start of the new pulse and therefore can count a pulse as a time between pulses and not the pulse itself (and a 80ms pulse 'gap' calculate to about 45kW, the high peaks you are seeing). Making the window longer might helpt.

In older versions heishamon only measured on a rising edge and didn't care about the falling edge (of a pulse). But that wasn't stable enough also, mainly in noisy situations.

**Comment by IgorYbema** [comment]
Also please test this test firmware. It changes to count on falling edges only. Maybe this is better in your situation. Please provide the result of this and the previous question (previous one about s0 pulse width chaging with running previous firmware without opentherm logging)
[HeishaMon.ino.d1_mini.zip](https://github.com/Egyras/HeishaMon/files/13696376/HeishaMon.ino.d1_mini.zip)

**Comment by jacco-hass** [comment]
3.2.4-beta (without OT logging), min 20 max 200: not working
3.2.4-s0-test, min 20 max 200: works
3.2.4-s0-test, min 60 max 100: works

So the last firmware you sent solved the issue for me! For your information, I'm using a 2 meter (properly shielded) S/FTP cable between the kWh-meters and the Heishamon, so there should be very little noise in my S0 lines.

**Comment by IgorYbema** [comment]
Great! Can you post a graph just for the comparison?

I'll think about how to add this change to the final code. Maybe a user switch to choose which S0 measuring algorithm is used. Ofcourse you can keep running this test firmware for now.

**Comment by jacco-hass** [comment]
This was the heat pump's power use last night, no noise at all and the power nicely corresponds to the total energy used!

![Screenshot_20231218_084111_Home Assistant](https://github.com/Egyras/HeishaMon/assets/62347605/504645d3-1571-4188-a783-ff7eb5bdd3d1)

One more thing: I was having some stability issues (random reboots every couple of hours), which seem to have been solved as well. It's a bit early to say, but it's been running for 16 hours continuously now.
Thanks for your efforts!
