### ISSUE TITLE
Help for old F-Type model

### ISSUE THREAD

**Issue by khwelter** [heishamon/HeishaMon#440]
I know it's not an issue, but don't know how or where to start...
I just received my heishamon H/W which - as I somehow expected - work's (on H/W level) with my F-Model Aquarea but the protocol of this model seems to be way of the actual implementation.
Does anybody have any idea where I could start digging for more info on the protocol, or will I just have to have patience and look into the reply almost from scratch?
Thanx, and please let me know if this was a wrong way to place this question.

**Comment by Mastiff-Ltd** [comment]
This has previously been suggested:
[https://github.com/v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy](https://github.com/v-s-c-o-p-e/geisha_aquarea_panasonic_arduino_esp8266_proxy)
