### ISSUE TITLE
MQTT Topic base add to MQTT password

### ISSUE THREAD

**Issue by Bohoo69** [heishamon/HeishaMon#441]
Hello,

I have installed the HeishaMon card on an Aquarea T-Cap and it's running great. Thanks a lot for the job done and sharing ! I am currrently working on Jeedom integration but I have discovered an issue with MQTT topic base setting. The fiield is automatically add to the password when send to the mqtt server. For the example below I select PAC as MQTT topic it's then added to the password has showed on the capture below. It's running perfectly if the MQQ Topic Field is left blank.

![17-12-2023 14-25-4CCCC3](https://github.com/Egyras/HeishaMon/assets/150486356/0dae2329-8648-4665-8121-d354bcae1661)

![17-12-2023 14-18-31](https://github.com/Egyras/HeishaMon/assets/150486356/bb8e1135-edfb-4029-a9f9-03144a77936d)

Kind regards

Ludovic

**Comment by IgorYbema** [comment]
Is your normal mqtt password 64 chars long? Or did it extend the password also?

**Comment by Bohoo69** [comment]
Hello,I did not count but the Jeedom password was very long !!

**Comment by ahoh77** [comment]
Hello,

Same here! I just started with HeishaMon, I installed it today and tried to get it working. But - I was wonderting why I can't get a MQTT connection to the home assistent broker- the log just showed "lost MQTT connection!" After several hours of fault searching I found this issue here and simply tried to clear the Mqqt topic base. And finally the connection was working, but only with a blank topic! I counted my password chars and yes, it has 64 chars. It is an automatically created random password...

(edit:) I just tried it out with another username/password - I entered a password with just 20 chars, and then it is working also with a Mqtt topic base

kind regards
Andreas

**Comment by IgorYbema** [comment]
I think I found the bug. Length of 64 was the max and it didn't had room for the 65th NULL character ending a string so it just reads on the next string in memory which is the topic :-)
Can you try this beta firmware?
(removed, not sure if this is working or breaking stuff)

**Comment by Bohoo69** [comment]
Hello,

I upload the firmware, it was fine. When i add the MQTT Topic 'PAC_Panasonic' i get a message thet the WiFi password was changed (i am sure i was on the MQQ Topic) and i lost the HeishaMon. I am not on site, il will try to get it back using the wifi connection on a PC in the same room. Let you know later

**Comment by IgorYbema** [comment]
Ok thanks for the feedback. I'll try to reproduce that

**Comment by Bohoo69** [comment]
Just let me check first it's on my side... I working on Jeedom integration, i can now get all the data thought the MQQ Manager of Jeedom in listen mode.... I have seen trouble on few data, i will make a another ticket

**Comment by IgorYbema** [comment]
I removed the beta above. Testing it with a long password caused my test to stop working.
If this is the case for you also, you can only restore it with doing the factory reset (twice reset button within 0.5 sec causing the blue led to blink fast). And then upload a production firmware in the hotspot mode (so on the 192.168.4.1 webpage)
I'll take a look what is happening

**Comment by IgorYbema** [comment]
The beta introduced a new bug :( but fixed in this one. I tested the long password myself now also and seems to work properly now
[HeishaMon.ino.zip](https://github.com/Egyras/HeishaMon/files/13797767/HeishaMon.ino.zip)

**Comment by Bohoo69** [comment]
Do not success to get control back at distance, will need to be on site next weekend !

**Comment by IgorYbema** [comment]
Yes I am sorry about that

**Comment by Bohoo69** [comment]
Hello, i sucess to acess to the HeishaMon whom return in a near factory mode mode though the hotspot. After reset factory and install last firmware i can confirm that the last firmware is ok with a long password... Many thanks, great job !

**Comment by IgorYbema** [comment]
Thanks for exposing this bug

**Comment by Bohoo69** [comment]
Thanks for having done this great integretation of Panasonic Heat Pumps !
