### ISSUE TITLE
No more data

### ISSUE THREAD

**Issue by drinkits** [heishamon/HeishaMon#452]
Hello,

After latest update Heishamon stopped retrieve any data from heatpump. As you can see in first picture heatpump was restarted on December 16 and data was coming for three days. Then blackout again.

I have tried to downgrade from 3.2.3 to 3.0/3.1, but Heishamon still does not get any data. Restarting heatpump also does not fix this.

Heatpump: WH-MDC05J3E5 5 1ph HP

![image](https://github.com/Egyras/HeishaMon/assets/10533962/9b4ca3dc-03bf-4f37-a0fb-fe337bfda0ac)
![image](https://github.com/Egyras/HeishaMon/assets/10533962/bafaa7d6-a3d4-43bb-be6e-79fc174bd35d)

**Comment by IgorYbema** [comment]
Hi,
The only firmware reason that we know of which causes this is v3.2.0 and when you have the optional pcb installed. Did you run v3.2.0 and do you have the optional pcb? v3.2.3 fixes it but you need to power down the heatpump to get it working after the firmware upgrade again (power cycle, not just a 'reset').

**Comment by drinkits** [comment]
No optional PCB. I am using HeishaMon normal PCB bought from Tindie. It worked like a charm for 2 years. Problems started after updated from default/shipped firmware (version 2.0).

Now I am on version 3.2.3, restarted heatpump - > no data. Maybe physical reconnect to heatpump can fix this?

![image](https://github.com/Egyras/HeishaMon/assets/10533962/a859c27d-4e2b-4bcf-97e1-ac9a8ec2b2e7)

**Comment by drinkits** [comment]
I have found a problem. Water got inside the box where HeishaMon was placed. Looks like it is not possible to fix water damaged PCB. 
![image](https://github.com/Egyras/HeishaMon/assets/10533962/46fd34e3-54c5-4baf-be1d-6c244f9dbd5b)

**Comment by IgorYbema** [comment]
I'm sorry for you that your board got water on it. I would be happy to give you some discount on a new board. Just contact me (the seller) on the tindie platform.
