### ISSUE TITLE
bivalent connection

### ISSUE THREAD

**Issue by meavric** [heishamon/HeishaMon#455]
Hi, is posible to get state bivalent connection from WH-SDC0709J3E5 9 1ph HP ?

**Comment by meavric** [comment]
Hi,
I have a heater connected to the buffer as a bivalent source (it turns on at -15 degrees C). Is it possible to derive the fact that this heater is turned on from the heat pump?
I mean this functionality:  : https://www.manualslib.com/manual/1273892/Panasonic-Wh-Sdc09h3e8.html?page=129#manual

**Comment by MiG-41** [comment]
For a real state of bivalent relay (and maybe defrost state if Bivalent is not active in J and higher models) , is responsible Bit1&2 in byte 112... Please ask @IgorYbema ,if he is willing to add this information in TOPs :)

**Comment by boon244** [comment]
Hello, I would also be interested in this...who can I buy a coffee for?
@IgorYbema

**Comment by Ioniq88** [comment]
Is it possible to integrate the Parameters for bivalent  connection to Heishamon?

- Enable/disable bivalent connection
- set outdoor temperature for turn ON Bivalent connectin
- Bivalent mode Alternative, Parallel, Advanced Parallel
- External Pump ON/Off 

This would be grate

Best regards Uli

**Comment by Ioniq88** [comment]
Did you  integrate the Parameters for bivalent connection to Heishamon?

Best regards Uli

**Comment by geduxas** [comment]
is this same as #377 ?
