### ISSUE TITLE
 Received 0 bytes data

### ISSUE THREAD

**Issue by SimonBard** [heishamon/HeishaMon#458]
For some days, Heishamon is no more sending current data. It sends only outdated data via MQTT. The heatpump is now again controlled by the control panel of panasonic. The values given that way are not reflected by heishamon. 

I now updated to 3.2.3, but still have the same issue. 

I get a log in MQTT, but what exactly does it say?

```
sent bytes: 111 including checksum value: 18 
Previous read data attempt failed due to timeout!
 Received 0 bytes data
```

Can that be a problem with the cable? Or does it mean the physical connection is ok, but its a software problem? 
MQTT is at least powered by the heatpump electronic. I can also reach the "Heisha monitor" (see screenshot)
![image](https://github.com/Egyras/HeishaMon/assets/63670466/ab423304-8623-42e8-8463-26038bb74ec0)

**Comment by IgorYbema** [comment]
Did you try power cycle the heatpump? So pull all the power from the heatpump so it resets.
We have, for now, only seen this in firmware v3.2.0 with the optional pcb installed. A power cycle resolves the issue.

Of course the cable can also be broken but that doesn't happen suddenly.

The message you see is just that heishamon is sending it's query for the data but it doesn't receive the answer back.

**Comment by PGnl** [comment]
Make sure you first switch off the heatpump on the controller and wait a minut before taking the power off.

**Comment by SimonBard** [comment]
Thank you for the prompt reply. I switched the power off and on and it works again. Sorry for the stupid issue.

**Comment by JockelBln** [comment]
@SimonBard Can you please close this issue if everything is ok again?
Thanks

**Comment by Coowly** [comment]
I have, sinds previous update (2-3 weeks back) (dont know if it was H.A. or heishamon, they both updated at the same time) exactly the same issue. Unfortunately a power cycle doesn't work. At start I got onetime correct values after that i have the exact same line;

sent bytes: 111 including checksum value: 18 
Previous read data attempt failed due to timeout!
 Received 0 bytes data
