### ISSUE TITLE
Issue with TOP 13, 115 and 66

### ISSUE THREAD

**Issue by Bohoo69** [heishamon/HeishaMon#460]
Hello,

I have seen some issues with the following topic 
- TOP13 Main Schedule State stays always at 0 even if Scheduled state is activated (showed on Heat Pump screen)
- TOP66 Low water pressure is always at 0. I find the attached schematic, slighty different than the one and there is no low pressure sensor on Aquerea ? Is this for other models than Aquerea T-Cap ?

As seen in issue resquest #445, water pressure is negative -0.02 for me

Many thanks in advance

Ludovic

![PAC avec apport électrique 2](https://github.com/Egyras/HeishaMon/assets/150486356/40a7cfcd-2c0a-4b40-8a19-c3b427bda770)

**Comment by MiG-41** [comment]
You dont have a water pressure sensor in your HP , so you recive sch data. This sensor is onlynin new K/L models.
 Also TOP66 is not for water , it is for gaś pressure ,and also your HP don't have it (and to be honest don' know with have . )
Regarding TOP13 i can't say anything.

**Comment by Bohoo69** [comment]
Ok thanks for the return I remove this two items... Perhaps TOP66 is present on multisplit or otherequipements

**Comment by MiG-41** [comment]
Witch sensor you belive it is Copressor Tank Temp ?

**Comment by Bohoo69** [comment]
I beleive - not sure - that this is top 55. What is surprising is when HP is down TOP55 is higher than 5 to 10°C from external temperature near the room temp where is situated internal parts of the HP. On the maintenance documents of Panasonic, the IPM temperature is located outside. I hesitate between compressor temp and frequency convertor driving the compressor.

![image](https://github.com/Egyras/HeishaMon/assets/150486356/ca428a4f-2495-4fd7-a9bf-ef6b4d44bdf1)

**Comment by geduxas** [comment]
IPM, it's measuring temperature of power module (inverter)

**Comment by MiG-41** [comment]
https://americas.fujielectric.com/faqwd/what-does-ipm-mean/

**Comment by Bohoo69** [comment]
Ok thanks for the information, this is the inverter temp and not compressor temp.
