### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Bohoo69** [heishamon/HeishaMon#461]
Hello,

Your card is making a great job and is way better than the original Panasonic ones. Nevertheless there is few features that the 'official' panasonic cloud manage that is not available on the HeishaMon ;
- Estimated power consumption in DHW and Heeting, i a am trying to compute that through Jeedom using 1 minute average but it will not be very precise. I am also computing heating and DHW power production. Seems that power consumption showed only show heater and compressor consumption but not including pumps and other elements (for example when the heat pumps starts, primary pumps stard immediatly and compressor few minutes later, electrical consumption stays at 0 until compressor start). I make estimatiation of power production using deta T and water flow, seems that heat pump is a little pessimistic but values are very near. By computing electrical comsuption using amps and sustracting that to power production it's possible to compute backup heater consumption.
- Heating and DHW, it is possible through the panasonic Cloud to set it from -5° to +5°C from the temperature set point, this is usefull for vacation to avoid full power when restarting the heat exchanger
- Through the panasonic cloud it's possible to manage shedule

Many thanks, kind regards

Ludovic

**Comment by MiG-41** [comment]
Heishamon is intended to pass only informations from HP , and only this with HP shows , so no calculations , no estimations ect. this you can make individually in your automations.

Panasonic cloud shedule  is also something different then this inside steering controller. 
Schedule from cloud is onlu inside CZ-TAW1 module , no in HP , so CZ-TAW1  sets on-off and changes temperatures , modes , not HP it self.  In Heishamon it is equal to that your automation do it ( changing temperatures , modes at pressed earlier times).
