### ISSUE TITLE
Resend homeassistant discovery topic

### ISSUE THREAD

**Issue by SimonBard** [heishamon/HeishaMon#463]
Is there a chance to resend the mqtt discovery topic?

I have rebooted heishamon and visited "http://192.168.178.45/togglelog". It sends the mqtt data, but homeassistant need a config topic, which I cannot see in the mosquitto logs. 

How can I trigger resending the config messages?

**Comment by geduxas** [comment]
Heishamon don't have it.

**Comment by SimonBard** [comment]
@geduxas: Thanks for the reply, which I do not understand. 
Is heishamon not sending config topics at all?
Or is there no resend function? Because the resend function needs to be triggered at some point automatically. I just wanted to know when exactly so I am able to trigger is myself.

![image](https://github.com/Egyras/HeishaMon/assets/63670466/705541fd-e993-467b-b1bd-8661065e5767)

**Comment by geduxas** [comment]
Sorry for too short answer, yes heishamon don't send any discovery/config topic. It's sends only it's data. 
As i understand from screenshot your referring to heishamon integration. So this issue should be rised in integration repository. 

Try to look in mqtt server via mqttexplorer or similar tool, maybe topic is not updated at all.
