### ISSUE TITLE
Date/Time wrong after power failure

### ISSUE THREAD

**Issue by stumbaumr** [heishamon/HeishaMon#472]
Experienced a power failure and the time did not get set as the internet router was not yet connected again.
Proposal:
Everyday at 0:05 call the NTP function.

So after a power failure the time would get set properly five minutes after power is back and the date/time on HeishaMon is properly in sync everyday after midnight...

**Comment by stumbaumr** [comment]
Relates to https://github.com/Egyras/HeishaMon/issues/465#issuecomment-1930132107
Relates to https://github.com/Egyras/HeishaMon/issues/483

**Comment by CurlyMoo** [comment]
https://github.com/IgorYbema/HeishaMon/pull/134

**Comment by stumbaumr** [comment]
Tested and fixed. Thanks @IgorYbema and @CurlyMoo!
