### ISSUE TITLE
settings lock

### ISSUE THREAD

**Issue by manuhassio1** [heishamon/HeishaMon#473]
The home screen correctly indicates the heat pump data, while if I go into the wifi configuration screen it remains stuck with:Please wait, loading saved settings...
I tried resetting the board and turning off the power but it remains blocked.

**Comment by manuhassio1** [comment]
![Screenshot_20240314_213401_Firefox](https://github.com/Egyras/HeishaMon/assets/140329892/9f22f4f7-5e0c-4296-ac5f-71c95d4d89dd)

**Comment by geduxas** [comment]
Which version you're running?

**Comment by manuhassio1** [comment]
Version 3.2.3.
yesterday I also tried to replace the firmware with an older one but nothing changed, the home screen gives me the aquarea values ​​while setting remains stuck waiting.

**Comment by manuhassio1** [comment]
I reset everything and reinstalled with a usb-ttl cable from version 3.2 to 3.2.3 and with all of them, once the mqtt section was set and the configuration was saved, the heishamon network reappears.

**Comment by henkedk** [comment]
@Egyras 
Is there a fix?
I just upgrade to 3.8 - my settings page is stuck on
"Please wait, loading saved settings..."

**Comment by geduxas** [comment]
@henkedk try to open in incognito mode and check.. it could be something cashed in your browser.

**Comment by henkedk** [comment]
> @henkedk try to open in incognito mode and check.. it could be something cashed in your browser.

Same thing - I think you got a bug due to special chars in the MQTT password - I got both " and ! in mine.

**Comment by geduxas** [comment]
@henkedk could you somehow share your password with @IgorYbema to check it out.. if it's reproducible it maybe possible to fix, or at least warn other about it..

**Comment by henkedk** [comment]
> @henkedk could you somehow share your password with @IgorYbema to check it out.. if it's reproducible it maybe possible to fix, or at least warn other about it..

I've sent him an email

**Comment by henkedk** [comment]
> @henkedk could you somehow share your password with @IgorYbema to check it out.. if it's reproducible it maybe possible to fix, or at least warn other about it..

I didn't hear anything from him, mind checking in with him to see if he got my email? :)
