### ISSUE TITLE
Help to integrate two aquarea t-cap (gen H)

### ISSUE THREAD

**Issue by Lazarus57** [heishamon/HeishaMon#476]
Hello,
I've got two Aquarea T-CAP with each one his HeishaMon module.
In home assistant I've got one HeishaMon integration.
Each Heishamon is actually publishing in MQTT Topic /panasonic_heat_pump
In home assistant, it seems that values are switching between the two heat pumps.
Before I tried to publish in two differents topic on MQTT server but COP was'nt shown correctly for the second in home assistant.
So my question is how to integrate correctly multiple heat pumps.
Additionnaly, how to add heat pump type. TOP92 is unknown.
Thank's

**Comment by geduxas** [comment]
First, this repository is not responsible for HA integration module, second you need to publish in different topics. Please close it here as not related, and if you have more questions, please open in integration github repository.
