### ISSUE TITLE
REQ: option to disable the WiFi hotspot

### ISSUE THREAD

**Issue by RichieB2B** [heishamon/HeishaMon#484]
Now that Heisamon supports wired Ethernet, it should be possible to disable the WiFi hotspot completely.
This setting should also prevent Heisamon to automatically present the passwordless hotspot when it cannot connect to the configured WiFi network.

Alternative: add the option to set a password for the hotspot. This way we can still use it as fallback but it will be more secure.

**Comment by IgorYbema** [comment]
Yes, already working on this

**Comment by schellevis** [comment]
Will this also be available for Heishamon Small? In my case, the Heishamon setup hotspot is accessible from the street. I don't have Ethernet on my Heishamon, but the trade-off of having to reset the device with the onboard button for increased security seems acceptable to me.

**Comment by HighlyCompressedAir** [comment]
Feature implemented #517, issue can be closed.
