### ISSUE TITLE
Communication Error H74

### ISSUE THREAD

**Issue by Skol6** [heishamon/HeishaMon#487]
Hi Folks,

Heishamon was running for several weeks without any issues.
during the last days I got multiple times commincation error H74.

Not nowing what could be the problem I have performed a complete power cycle of my aquarea heat pump.
Afterwards everything is running normal again.

Can someone confirm this issue?

**Comment by Keisha0815** [comment]
Hi Skol6,
my Heishamon yesterday losts its connection to the heatpump too. Where have you read the error number?
I´ve tried to reboot but it does not run. After a complete power cycle it would connect again and now it works until ...?
In the OptionalPCB.md you can see the error H74 is a problem with OptionalPCB:

Remark 3: Setting in HP Service settings Optional PCB to YES gives expectation ,that Optional PCB emulator ( HeishaMon) will sent continuously Optional PCB Set Command. When communication disappear (for around 40s) HP generates H74 error and switches off to StandBy. So ensure continiues communication is very important , be aware during switch off , factory default of HeishaMon , or similar action.

Maybe this was my problem too ...Testing the Options
Good Luck, Armin

**Comment by Skol6** [comment]
Hi,
the error number was shown directly in the heat pump menu.

Thanks for the remark information. BUT I did not change anything when the failures where coming up.
Maybe the reason is full memory and slow communication. I will try to keep an eye on it.

Regards

**Comment by Keisha0815** [comment]
Hi, i‘ve not seen any errors in the heishamon menu. Have you installed the CZ-NS5P?
Wifi-Problems?

**Comment by Skol6** [comment]
I am not using the  CZ-NS5P.

**Comment by IgorYbema** [comment]
Not using the CZ-NS5P but you are getting H74? Then you most be using the optional pcb emulation in heishamon and enable the optional pcb in the heatpump.
The emulation is not perfect. If heishamon fails/get delayed the communication stops and causing the H74. This can be caused by so many reason but mainly network related as heishamon is a single threaded device not able to handle network delays together with communication to the heatpump at the same time.

**Comment by Skol6** [comment]
Yes I am using the PCB emulation to control the heat pump. 
H74 is really only for communication between main PCB and optional PCB - that is simulated by heishamon.

So bug must be something to do with the Heishamon Software.

**Comment by IgorYbema** [comment]
Yes but as I said the emulation is not perfect. The H74 pops up if heishamon is a bit too busy and therefore not delivering the messages in time. It helps if you keep heishamon not to active like lowering the timers.
