### ISSUE TITLE
Does the 3D-model "normal case" still make sense

### ISSUE THREAD

**Issue by klausj1** [heishamon/HeishaMon#490]
I ordered the "small" version in the Tindie-shop, and I 3D-printed the case "[HeishaMon normal case.stl](https://github.com/Egyras/HeishaMon/blob/master/HeishaMon%20normal%20case.stl)". This case is much too small, I assume I need [HeishaMon opentherm case.stl](https://github.com/Egyras/HeishaMon/blob/master/HeishaMon%20opentherm%20case.stl).

If the normal case is not needed anymore, I would vote for removing it from the repo.

Thanks,
Klaus

**Comment by IgorYbema** [comment]
Yes you are right. The 'normal' isn't used anymore and we can remove that. The opentherm is now the main one (called 'small' heishamon board)

**Comment by HighlyCompressedAir** [comment]
Files have been renamed properly, this issue can be closed.

**Comment by klausj1** [comment]
Thanks, closed.
