### ISSUE TITLE
Where my Variables in the Console? (Heishamon V5, SW 3.5)

### ISSUE THREAD

**Issue by Binifada1956** [heishamon/HeishaMon#493]
Today, installed the new Heishamon. I was wondering while i don't see my Global Variables in the Console. Now no Control what my Rules doing!

**Comment by stumbaumr** [comment]
V3.5 still has some bugs.
See
https://github.com/IgorYbema/HeishaMon/pull/121
and 
https://github.com/IgorYbema/HeishaMon/pull/133

**Comment by Binifada1956** [comment]
I tested a diversion today with print(...). Here I can output the variables in the console, but is that the way it's meant to be?
In addition, the print command requires a lot of resources.

**Comment by stumbaumr** [comment]
Without showing your code it is really hard to say what goes wrong...

**Comment by Binifada1956** [comment]
With Heishamon V4 was no Problem. I saw all my Variables in the Console. After changed to V5 i saw nothing. No Change in Rules.
See also issue #486

**Comment by stumbaumr** [comment]
I would recommend that you try the build from here https://github.com/IgorYbema/HeishaMon/actions/runs/9553126605 and check to see if that fulfills your requirements.

If you are still missing functionality get involved [here](https://github.com/IgorYbema/HeishaMon/pull/133)...

**Comment by Binifada1956** [comment]
ok, Variables are in Cconsole again 👍
