### ISSUE TITLE
How to trigger backup heater using optional PCB or RS485 protocol 

### ISSUE THREAD

**Issue by PeterRiddersholmLauridsen** [heishamon/HeishaMon#495]
Hi all 

I hope this is possible on my Panasonic heat pump: :)
Is it possible to trigger the backup heater directly using the optional PCB or the CN-CNT port. 
Thanks in advance. 

Best regards 
Peter

**Comment by geduxas** [comment]
No, it's backup, it's used by panasonic logic for backup operations.. not main..

**Comment by PeterRiddersholmLauridsen** [comment]
Thanks for this information.

But is it possible to force this backup heater to start if the right rs485 command is send to the main PCB?




Peter Riddersholm Lauridsen | Software og SGX Cloud ansvarlig

E: ***@***.******@***.***>

www.smartgrid-x.com<http://www.smartgrid-x.com/>


SMARTGRID-X, Skolegade 85, DK - 6700 Esbjerg

 [facebook icon] <https://www.facebook.com/profile.php?id=100087068707161>   [youtube icon] ***@***.***>   [linkedin icon] <https://www.linkedin.com/company/smartgrid-x/>



________________________________
