### ISSUE TITLE
Aquarea Heatpump Model "L": Two different sensors for domestic hot water (Tank)

### ISSUE THREAD

**Issue by DRDavidRu** [heishamon/HeishaMon#506]
There are two sensors for the temperature of the domestic water in the "L" model with internal storage. One sensor is at the top and one is in the middle of the tank. This can be selected in the heat pump menu and can also be set in the ServiceCloud. So far, only one value is output via Heishamon. Is it possible to read both values ​​at the same time?

**Comment by geduxas** [comment]
Both are available, one in same topic and another in extra if i remember correctly..

**Comment by MiG-41** [comment]
In "All-In-One" models from H and J series it is possible to select Top or middle sensor , but read only from selected sensor. 
I assume nothing changed.
