### ISSUE TITLE
UI stuck in "...Loading..." since 3.7

### ISSUE THREAD

**Issue by bagbag** [heishamon/HeishaMon#510]
After updating to 3.7, the UI doesn't show any values anymore. The table is stuck in `...Loading...` state.

Network monitor of developer console says `SyntaxError: JSON.parse: bad control character in string literal at line 1 column 7300 of the JSON data` for the new json request.

Visual studio code tells me the following for the response:
![image](https://github.com/user-attachments/assets/1fab6e39-46c2-4780-95cd-3413bb41be92)

Hex view:
![image](https://github.com/user-attachments/assets/a8d5a3a3-8b32-45d9-9f2a-8051b0228eeb)

**Comment by bagbag** [comment]
The problem seems to be the tab after `IDU:` instead of a regular space. It has to be either a space or escaped to `\t`.

**Comment by IgorYbema** [comment]
Thanks. I'll upload a new v3.7 asap (will keep it at v3.7, just look at different timestamp)

**Comment by bagbag** [comment]
Great!
New binary from your repository works fine.
