### ISSUE TITLE
Release version 3.7 contains "Alpha" + commit identifier, instead of actual release version 

### ISSUE THREAD

**Issue by mi-hol** [heishamon/HeishaMon#513]
https://github.com/Egyras/HeishaMon/blob/master/.github/workflows/main.yml sets 

```

 - name: Update version.h
        if: github.ref != 'refs/heads/main' #do not change version in main branch run
        run: cd HeishaMon && echo "static const char *heishamon_version = \"Alpha-$(git rev-parse --short HEAD)\";" > version.h && cat version.h
        shell: bash'''

```

Suggest a separate yaml for release build

**Comment by geduxas** [comment]
Nope release contains correct build 
![Screenshot_2024-09-06-17-54-24-33_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/732087ca-7b01-40a2-936c-d087c640ab57)

**Comment by IgorYbema** [comment]
Only if you take the build from main or directly the file from the binaries folder you will see proper v3.7

**Comment by mi-hol** [comment]
in the meantime I downloaded and opened for example https://github.com/Egyras/HeishaMon/blob/master/binaries/model-type-large/HeishaMon.ino.esp32-v3.7.bin in an editor

There is indeed a proper version number

![image](https://github.com/user-attachments/assets/b965a8b9-5333-4315-a244-a0c17f0c7b9e)
