### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by krzbor** [heishamon/HeishaMon#518]
For devices that I can connect to (e.g., via HTTP), I use static IP addresses outside of the DHCP pool. Is it possible to add static IP configuration (including mask and gateway, of course) in HeishaMon?

**Comment by IgorYbema** [comment]
Yes I'll add that to my list of todo's :)

**Comment by krzbor** [comment]
Is the list long? :)

**Comment by stumbaumr** [comment]
When using DHCP just assign a fixed IP to the MAC address in your DHCP server.
Best practise: Maintaining IPs centrally is much easier in the long run than setting them on the devices directly.

**Comment by krzbor** [comment]
I've changed routers many times in my life. The manufacturers of this equipment have also changed several times. However, I have NEVER changed the addressing of my network. The answer is simple - a static IP is a better solution than DHCP. The pool of private addresses was defined in the last century and hasn't really changed. So what is more permanent - the router with its configuration or the static IP address defined in RFC1918?

**Comment by geduxas** [comment]
Yes with static IP you could survive while recovering dhcp router ;)

**Comment by stumbaumr** [comment]
You change the router from Speedport to Fritzbox, you use the old WLAN and PSK in the new router, but then you realize the IP address range is different...

When your DHCP router reboots/recovers your other devices do not suddenly loose the currently assigned IPs...

I rather click a checkbox in the router and assign a fixed IP instead of hacking in IP, Netmask, DNS and router IP on a mobile within a webUI...

**Comment by geduxas** [comment]
@stumbaumr is it really? Manufactures blocks ip range? :D i thought it's fing form far far past :D

**Comment by krzbor** [comment]
For my devices – the server, virtual machines, an Ethernet RS485 controller, cameras, underfloor heating control, IP intercom, and additional APs – I have static IP addresses, which I document in a file. They remain unchanged, even when I replace the router. Now it's probably clear why I want to add Heishamon to this "collection".

**Comment by stumbaumr** [comment]
> @stumbaumr is it really? Manufactures blocks ip range? :D i thought it's fing form far far past :D

They do not block you from changing that - but at least in the FritzBox you have to activate the expert mode.

**Comment by stumbaumr** [comment]
> For my devices – the server, virtual machines, an Ethernet RS485 controller, cameras, underfloor heating control, IP intercom, and additional APs – I have static IP addresses, which I document in a file. They remain unchanged, even when I replace the router. Now it's probably clear why I want to add Heishamon to this "collection".

We are fighting in IgorYbema's repo against memory issues causing reboots and here you request features no one really needs. You should print that file out on paper and laminate it...

**Comment by krzbor** [comment]
Now I understand – you're criticizing all my ideas just because you want IgorYbema to focus on an issue that's important to you – memory problems and reboots. From experience, I know that tracking down such issues is a complex task. In the case of using MQTT, reboots don't matter much since the ESP restarts in just a few seconds. DeepSleep for this processor is a commonly used feature in battery-powered solutions, and every return from DeepSleep is nothing more than a reboot. If you think no one needs a static IP, then why is the option to configure a static IP available in almost all network-controlled devices (e.g., those with a built-in web server)?

**Comment by geduxas** [comment]
It's not Igor repo, there is no need to fight, static ip should be implemented, don't think there is any problem with that. It just needs time. 
Why should anyone prove why one or another function is important for them. I didn't see anywhere system which works only on DHCP..

**Comment by stumbaumr** [comment]
As always with opensource... just clone, build and ask for the pull request to be merged...

**Comment by krzbor** [comment]
Do you happen to know when this feature will be available?
