### ISSUE TITLE
RESET DEFAULT HEISHAMON 4.7

### ISSUE THREAD

**Issue by dimaregabriele** [heishamon/HeishaMon#528]
Hi everyone. I have a heishamon 4.7 pcb board. I can no longer connect to the same wifi network set. so I have to reset it to factory settings to be able to access its hotspot. how can I reset it? inside there are two buttons: flash and reset. how should I press them? Thank you

**Comment by IgorYbema** [comment]
If you are running the latest firmware just hold the boot button for more than 10 seconds
On older versions, you need to double reset the board within about 0.5 seconds.

In both cases you will see the led flickering fast. Then a reset will take you back in factory mode

**Comment by IgorYbema** [comment]
Also, on older firmware there was no option to disable the hotspot. If heishamon can not connect to the wifi, and if the hotspot setting is enabled, it will eventually present the hotspot again. Even without factory reset.

**Comment by dimaregabriele** [comment]
but which button should I press? reset ? for how long?
