### ISSUE TITLE
Feature Request: Enable Temperature Readings of optional PCB

### ISSUE THREAD

**Issue by baddivot** [heishamon/HeishaMon#530]
Hi there,

I would like to run my Aquarea in a bivalent mode with a buffer. For this to work, I would need the optional PCB CZ-S5P for attaching a temperature sensor (it gets attached to E45)
Since Heishamon can emulate that optional PCB for outgoing controls (The heatpump controling external devices), I thought it should also be possible that it allows incoming readings and pass these to the heatpump, i.e. I could write the temperature I measure with my own hardware into a topic and heishamon sends it via E45 to the heatpump. 

Let me know what you think...I would prefer not having to buy the optional PCB for only one temperature reading.
Regards
baddi

**Comment by HighlyCompressedAir** [comment]
Yes, you can do that. On top of that you can add 1wire temperature sensor directly to Heishamon to make it simple and reliable.

**Comment by baddivot** [comment]
Thanks for your quick reply. If I understand you correctly, I can already emulate PCP readings? So how can I do that? I looked at the code and I found that all the setters for the opt Topics are skeletons and not implemented. I guess it is important for the HP to receive the temp through E45. Can I write directly to that register from whichever topic?

**Comment by HighlyCompressedAir** [comment]
Are you sure you're looking at the latest version?
@SetBufferTemp = 30 makes the heat pump think the buffer temperature is 30 degrees. You can write to it anything you want whether as a rule directly in Heishamon or through mqtt server, Home Assistant and such. 1wire temperature sensor connected to Heishamon and a simple rule should be the easiest way, something like:

on ds18b20#2800000000000000 then
@SetBufferTemp = ds18b20#2800000000000000
end

Buffer temperature should then update automatically. If not there has to be a timer set up, I'm not sure, I haven't used 1wire yet, but it's easy either way.

**Comment by HighlyCompressedAir** [comment]
Sorry, I didn't realize that the buffer tank sensor connection got moved from optional pcb to mainboard in newer pumps, but that's actually good for your case. All you have to do is connect a temperature sensor to the pump, enable optional pcb emulation and then enable buffer tank in settings. No rules or automations required. In fact @SetBufferTemp becomes useless, as with a physical connector present the pump always reads actual values, they can't be set at will.

**Comment by baddivot** [comment]
Hi and thanks for following up on this. I have no problem with the buffer temperature, though. 

I'm referring to the outlet temp from the buffer which is read through connector E45 on the PCB. I attached the image of the hydraulic schematic. I highlighted the sensor in question. (PAW-A2W-TSHC [E45]. 
I also attached the schematic of the PCB. There I highlighted the actual connector E45.
I'm expecting that that is a controlled/set heating inlet temperature and is usually different from the actual buffer temp in a bivalent setup, if the bivalent heat source is an oil or wood oven or so. There the buffer temp is generally higher than the required heating inlet temp, So I need to use  a mixer which in turn needs the actual temp at that position.

![image](https://github.com/user-attachments/assets/8df63c67-6161-4da7-9309-4c8ba695e4ad)
![image](https://github.com/user-attachments/assets/1dc1e20d-49d1-41fb-8e62-4564a749a837)

BTW, if anybody here is in for a discussion of the official Panasonic schematics, like the one I attached, let me know. For starters, I don't understand why Panasonic does not put a mixer into the buffer outlet/heating inlet in a bivalent setup.

**Comment by geduxas** [comment]
For mixer valve..  it's depends on setup.. i think by default it's left for installer to decide how will be driven heating equipment. 

As for Panasonic side, you can install mixing valve, and it will work as should, because there is no additional setup for mixing valve, Panasonic always thinks valve exist in system.

**Comment by HighlyCompressedAir** [comment]
Ok, I get it, you're reffering to water sensor zone 1. Your issue actually may correlate with another one, I think we have to figure some stuff out regarding optional pcb sensors. The setup you want is actually described in the service manual:
![bivalent](https://github.com/user-attachments/assets/a28998dc-dd61-4e36-9f27-ea7e645ad495)

As you can see it requires connecting sensors to main pcb, not optional. It looks like some zone 1 sensors on optional pcb aren't really used.
Oh, there's only one such sensor - zone 1 room sensor. So water sensor zone 1 can be emulated the way I described in my second post.

**Comment by geduxas** [comment]
Also to take a note! Optional pcb emulation was made for H/J series HP. As for K/,L we just making presumption that it should work.. but really there is not tested enough.
