### ISSUE TITLE
Factory reset not working

### ISSUE THREAD

**Issue by westerner0101** [heishamon/HeishaMon#534]
Hi, I have a board marked "Heishamon OT v1.3".  I mistakenly uploaded the wrong firmware ('large', when it should have been 'small'), and now the Heishamon no longer responds.  I am now trying to factory reset the board by pressing the reset button twice in 0.5 seconds but the blue LED just flashes once each time I press the reset button (I have connected wires to 5V and GND, via a TTL module).  It never blinks rapidly, and the default hotspot never appears.  There is a single green LED constantly lit on the board.

Can anyone please tell me exactly what I should do to factory reset the board?  Or if anyone knows a Youtube video that shows the procedure, it would be a great help.

Thank you for your time.

**Comment by geduxas** [comment]
Please read #502

**Comment by westerner0101** [comment]
Thanks, but I still have no success with that method.  It says "When connected you put the heishamon in firmware update mode by holding the boot button while resetting it. You can release the boot button after the reset".

I don't have a boot button, only reset and flash.  If I hold down the flash button then press (once?) the reset button, nothing happens - I can't connect with this tool: https://espressif.github.io/esptool-js/ - "failed to connect with the device".  What baudrate is recommended?

Thank you.

**Comment by IgorYbema** [comment]
Please join https://github.com/Egyras/HeishaMon/issues/535

**Comment by qbakk** [comment]
everything looks exactly the same for me and it doesn't work
