### ISSUE TITLE
Flash by TTL (v4.7)

### ISSUE THREAD

**Issue by qbakk** [heishamon/HeishaMon#535]
Hi, I made a mistake and I tried flash board v4.7 by "model-type-large" 3.8 firmware.

I wan't to fix it and i try to use
CP2102 Board and I have problem with connection on website: https://espressif.github.io/esptool-js/

All my try end that:
![image](https://github.com/user-attachments/assets/8f8e26e7-3fc5-47f7-9e99-02d82b79b6d2)

(on the screen I tried use the FT232RL from my friend)

what i do wrong?

**Comment by IgorYbema** [comment]
Make sure tx and rx are placed correctly AND press-and-hold flash button while resetting the board to get the board into manual firmware upload mode.

**Comment by IgorYbema** [comment]
Also make sure you upload the heishamon binary to address 0x0000 and not 0x1000

**Comment by qbakk** [comment]
I make sure the tx and rx i correctly (I saw the post with similar problem). When I hold the flash button nothing happens always green led is on. When I click reset button blue led blink (on esp)

**Comment by westerner0101** [comment]
> Make sure tx and rx are placed correctly AND press-and-hold flash button while resetting the board to get the board into manual firmware upload mode.

"while resetting the board" - can you please clarify this procedure? Do you mean holding the reset button, or something else? 

Also, when using a TTL module with Dupont wires, is it TX-TX & RX-RX or TX-RX & RX-TX?

Thanks again.

**Comment by IgorYbema** [comment]
1) press-and-hold flash button
2) press reset
3) release flash button after a second

This will bring it into flash mode.

The wiring should be TX->RX and vice versa. But if that doesn't work just try it the other way arround  (maybe the markings on your dupont wire is wrong).

**Comment by qbakk** [comment]
for me work's all fine!

**Comment by westerner0101** [comment]
> 1. press-and-hold flash button
> 2. press reset
> 3. release flash button after a second
> 
> This will bring it into flash mode.
> 
> The wiring should be TX->RX and vice versa. But if that doesn't work just try it the other way arround (maybe the markings on your dupont wire is wrong).

Thank you very much for your help, it's all working again now 👍🏻 (it was TX-RX for me)

**Comment by Egyras** [comment]
resolved
