### ISSUE TITLE
Aquaera doesn't get any orders from Heishamon

### ISSUE THREAD

**Issue by hubsi5** [heishamon/HeishaMon#540]
I have the Panasonic INET module and the large Heishamon running in parallel.

I get all the data.

I can control via the Panasonic Cloud.

Heishamon reliably provides me with all the data.

But now I want to send commands with Heishamon and unfortunately that's just a game of chance.

Sometimes it works, sometimes it doesn't.

I already have the Panasonic module and Heishamon directly on the LAN.

Regardless of whether I send commands via MQTT or HTTP, Heishamon only passes them on every now and then.

But in the Heishamonlog I see that the command arrives.
![pasted-from-clipboard](https://github.com/user-attachments/assets/48a23140-dcd6-4360-a353-a2f9a184a9c8)

**Comment by IgorYbema** [comment]
You said you have the INET module (cz-taw1) parallel. This will not work if heishamon is also running. You need to connect this cz-taw1 to the proxy port of the heishamon and not directly to the heatpump

**Comment by hubsi5** [comment]
Oh thank you.
I guess I had a blackout then
Thanks, it works now!
