### ISSUE TITLE
How to do a firmware update

### ISSUE THREAD

**Issue by klausj1** [heishamon/HeishaMon#542]
The firmware update description in the readme is pretty short ;)

Just to be sure: To get the correct binaries (currently 3.8), download `source.zip` from [here](https://github.com/Egyras/HeishaMon/releases/tag/v3.8), and from `HeishaMon-3.8\binaries\model-type-small` (I have the small board, no LAN), take `HeishaMon.ino.d1-v3.8.`bin.

Correct?

A small update of the documentation would be great ;)

**Comment by IgorYbema** [comment]
No need to download the complete sources. You can easily download the binary from https://github.com/Egyras/HeishaMon/tree/master/binaries

Also take the .md5 file and read the content. Paste that md5 text into the md5 input field of the heishamon update page.

**Comment by klausj1** [comment]
Lightning-fast, as usual 😊 Thanks! A link to this page in the docu would be great.

**Comment by Stueckgold** [comment]
I try to flash from 3.2.3 to 3.8 or any other binary:
I always get errors
"Update failed! Please try again...ERROR[7]: MD5 Failed"
or without md5 it´s
"Update failed! Please try again...ERROR[10]: Magic byte is wrong, not 0xE9"

small version

**Comment by IgorYbema** [comment]
@Stueckgold you are probably not downloading the files correctly. Downloading the HTML content instead of the real/raw binary file.
And try to upload without a second tab open to heishamon (no console log running)

**Comment by Stueckgold** [comment]
You was right, no right-click save to...
Eventhough it looks like a directory...
