### ISSUE TITLE
Consumption data

### ISSUE THREAD

**Issue by askpet** [heishamon/HeishaMon#547]
Hi,
I have tried searching but no luck.

For quite some time I lost some attributes, where the most annoying is the consumption data (in W). 

I just update FW to 3.8 (newest build) but the issue is still there.

Anyone have an idea on why that is?

No changes to my Aquera unit.

Kind regards
Anders

**Comment by geduxas** [comment]
Some time back it was renamed from energy to power or vice versa.. maybe your didn't noticed that? In mqtt topic

#420

**Comment by askpet** [comment]
Facepalm! Thank you Geduxas.
