### ISSUE TITLE
Heishamon does not reconnect automatically after WLAN-Outage

### ISSUE THREAD

**Issue by klausj1** [heishamon/HeishaMon#550]
I have the Heishamon Firmware 3.8, the small version, connected via WLAN.

Today I had a 5-10 minutes outage of my WLAN, and the Heishamon did not reconnect when it was back again. Instead, it created an own access point to connect to. I connected to this access point with my mobile, and rebooted the Heishamon via UI. Afterwards it was connected again to the WLAN.

Would be good if it reconnects to the WLAN automatically.

I know there is the setting "Enable WiFi hotspot when not connected", it is checked. But if I uncheck it and the WLAN (password) changes for whatever reason, then I cannot connect to the Heishamon at all, right? If this is true, this solution would also not be that good.

**Comment by jllussa** [comment]
You have to uncheck "Enable WiFi hotspot when not connected" and Heishamon will reconnect automatically.

If you ever change your wifi then you will have to factory reset the board.
Press 10 seconds reset button on PCB.
Then hotspot will reappear.

**Comment by klausj1** [comment]
Thanks, that was somehow clear. Still it would be great if the Heishamon checks every 5 minutes or so if the configured WLAN is  available again (as long as no client is connected to the hotspot), and if not, open the hotspot again. Then there is no risk that you have to search for the reset button and you do not know how to reset.

**Comment by IgorYbema** [comment]
I should auto-reconnect already but in some situations I also noticed that it doesn't. I still don't know why. So for now, just reset the board if this happens.

**Comment by klausj1** [comment]
Then I'll leave the "Enable WiFi hotspot when not connected" checked and hope I do not have too many WLAN-problems. Esp. when I am not at home ...
