### ISSUE TITLE
Getting values individually via HTTP

### ISSUE THREAD

**Issue by lkakas** [heishamon/HeishaMon#553]
Is it possible to get values from heishamon with a http get method one by one or individually instead of a big chunk of json? Like the "command" url which can be used to set params. The problem with the JSON is that there arent uniq rows as each value is in a " value:" row which makes impossible to distinguish between the params with loxone. 

I need this to be able to integrate with loxone.

Thanks

**Comment by geduxas** [comment]
json is in array of objects.. so each object has it's values, and names.. i am unfamiliar with loxone, how about mqtt?

**Comment by lkakas** [comment]
I can process JSON which contains uniqe names in the structure for the objects: 

![kép](https://github.com/user-attachments/assets/68b43cc6-c6bb-45c2-891f-9cc6dbfda993)

But not like the heishamon:
![kép](https://github.com/user-attachments/assets/39807641-320d-4e73-8141-4f233e3b8412)


Loxone isn't smart enough to interpret the whole json structure :-( 

On the other hand I don't want to install another appliance with MQTT capability.

**Comment by lkakas** [comment]
I managed to extract the values from the objects in Json. 

For example with the following "Command recognition"  in Loxone:  

\i"Heatpump_State","Value":\i\v
\i"Operations_Counter","Value":\i\v

**Comment by lkakas** [comment]
I managed to extract the values from the objects in Json. 

For example with the following "Command recognition"  in Loxone:  

\i"Heatpump_State","Value":\i\v
\i"Operations_Counter","Value":\i\v
