### ISSUE TITLE
Set1: SetHeatpump not working with Panasonic wh-mdc07j3e5

### ISSUE THREAD

**Issue by agenstarburst** [heishamon/HeishaMon#554]
If I send a mqtt command set1 SetHeatpump=1 on my wh-mdc07j3e5 the command will not be followed. This happens no matter if I use the mqtt sendto block in blockly (iobroker) nor if I send the command via URL command http://192.168.xxx.xx/command?setHeatPump=0. 

There is no fundamental malfunction as other commands (e.g. as Set29 SetHeatingOffOutdoorTemp=15°C) are properly working. Let me know if you need any further data for analysis.

**Comment by geduxas** [comment]
So you're trying to set it to 0 or 1? 1 will turn it on from suspension, 0 will bring it off. Also if i remember correctly beep will also be hered in control panel

**Comment by agenstarburst** [comment]
I tried both already. So if the pump was off, I tried to switch it on via SetHeatpump=1 and also if it was on, I tried to switch it off by SetHeatpump=0. If I use the URL interface with other commands as e.g. the Set29, I get an acknowledge that the value was set. If I use the SetHeatpump command, the page just stays blank.

**Comment by geduxas** [comment]
For me in latest version everything work's fine, so you have issue.. do you run rule's? Try disable rules and then set commands, or maybe you have some retained set commands in mqtt? Try disable mqtt..also send logs from console while executing commant

**Comment by agenstarburst** [comment]
It's a fresh setup done in 09/24 using HeishaMon.ino.d1-v3.8.bin, no rules used yet. This command did not work from the first day on. I exported the logfile that was created during sending the command via http://192.168.xxx.xx/command?setHeatPump=0. I sent the command SetHeatingOffOutdoorTemp=16°C before setHeatPump=0 and sent SetHeatingOffOutdoorTemp=15°C after the setHeatPump=0 command so it is easier to identify the timing. 

Tue Oct 15 09:50:48 2024 (15002): Starting initial wifi scan ...
Tue Oct 15 09:50:48 2024 (15006): Connecting to mqtt server ...
Tue Oct 15 09:50:48 2024 (15081): Heishamon stats: Uptime: 0 days 0 hours 0 minutes 15 seconds ## Free memory: 70% ## Heap fragmentation: 7% ## Max free block: 25336 bytes ## Free heap: 27088 bytes ## Wifi: 50% (RSSI: -75) ## Mqtt reconnects: 1 ## Correct data: 100.00% Rules active: 0
Tue Oct 15 09:50:48 2024 (15099): Requesting new panasonic data
Tue Oct 15 09:50:48 2024 (15106): sent bytes: 111 including checksum value: 18 
Tue Oct 15 09:50:49 2024 (15519): Received 203 bytes data
Tue Oct 15 09:50:49 2024 (15520): Checksum and header received ok!
Tue Oct 15 09:50:49 2024 (15545): received TOP0 Heatpump_State: 1
Tue Oct 15 09:50:49 2024 (15547): received TOP1 Pump_Flow: 0.13
Tue Oct 15 09:50:49 2024 (15548): received TOP2 Force_DHW_State: 0
Tue Oct 15 09:50:49 2024 (15553): received TOP3 Quiet_Mode_Schedule: 0
Tue Oct 15 09:50:49 2024 (15560): received TOP4 Operating_Mode_State: 0
Tue Oct 15 09:50:49 2024 (15567): received TOP5 Main_Inlet_Temp: 25.75
Tue Oct 15 09:50:49 2024 (15572): received TOP6 Main_Outlet_Temp: 26
Tue Oct 15 09:50:49 2024 (15582): received TOP7 Main_Target_Temp: 30
Tue Oct 15 09:50:49 2024 (15584): received TOP8 Compressor_Freq: 0
Tue Oct 15 09:50:49 2024 (15590): received TOP9 DHW_Target_Temp: 52
Tue Oct 15 09:50:49 2024 (15597): received TOP10 DHW_Temp: -128
Tue Oct 15 09:50:49 2024 (15601): received TOP11 Operations_Hours: 245
Tue Oct 15 09:50:49 2024 (15645): received TOP12 Operations_Counter: 216
Tue Oct 15 09:50:49 2024 (15647): received TOP13 Main_Schedule_State: 0
Tue Oct 15 09:50:49 2024 (15648): received TOP14 Outside_Temp: 12
Tue Oct 15 09:50:49 2024 (15656): received TOP15 Heat_Power_Production: 0
Tue Oct 15 09:50:49 2024 (15662): received TOP16 Heat_Power_Consumption: 0
Tue Oct 15 09:50:49 2024 (15668): received TOP17 Powerful_Mode_Time: 0
Tue Oct 15 09:50:49 2024 (15674): received TOP18 Quiet_Mode_Level: 0
Tue Oct 15 09:50:49 2024 (15682): received TOP19 Holiday_Mode_State: 0
Tue Oct 15 09:50:49 2024 (15686): received TOP20 ThreeWay_Valve_State: 0
Tue Oct 15 09:50:49 2024 (15692): received TOP21 Outside_Pipe_Temp: 13
Tue Oct 15 09:50:49 2024 (15699): received TOP22 DHW_Heat_Delta: -8
Tue Oct 15 09:50:49 2024 (15744): received TOP23 Heat_Delta: 2
Tue Oct 15 09:50:49 2024 (15746): received TOP24 Cool_Delta: 5
Tue Oct 15 09:50:49 2024 (15747): received TOP25 DHW_Holiday_Shift_Temp: -15
Tue Oct 15 09:50:49 2024 (15753): received TOP26 Defrosting_State: 0
Tue Oct 15 09:50:49 2024 (15760): received TOP27 Z1_Heat_Request_Temp: -1
Tue Oct 15 09:50:49 2024 (15767): received TOP28 Z1_Cool_Request_Temp: 0
Tue Oct 15 09:50:49 2024 (15772): received TOP29 Z1_Heat_Curve_Target_High_Temp: 40
Tue Oct 15 09:50:49 2024 (15782): received TOP30 Z1_Heat_Curve_Target_Low_Temp: 31
Tue Oct 15 09:50:49 2024 (15786): received TOP31 Z1_Heat_Curve_Outside_High_Temp: 5
Tue Oct 15 09:50:49 2024 (15794): received TOP32 Z1_Heat_Curve_Outside_Low_Temp: -12
Tue Oct 15 09:50:49 2024 (15802): received TOP33 Room_Thermostat_Temp: 23
Tue Oct 15 09:50:49 2024 (15846): received TOP34 Z2_Heat_Request_Temp: 0
Tue Oct 15 09:50:49 2024 (15847): received TOP35 Z2_Cool_Request_Temp: 0
Tue Oct 15 09:50:49 2024 (15849): received TOP36 Z1_Water_Temp: -78
Tue Oct 15 09:50:49 2024 (15855): received TOP37 Z2_Water_Temp: -78
Tue Oct 15 09:50:49 2024 (15862): received TOP38 Cool_Power_Production: 0
Tue Oct 15 09:50:49 2024 (15868): received TOP39 Cool_Power_Consumption: 0
Tue Oct 15 09:50:49 2024 (15874): received TOP40 DHW_Power_Production: 0
Tue Oct 15 09:50:49 2024 (15882): received TOP41 DHW_Power_Consumption: 0
Tue Oct 15 09:50:49 2024 (15887): received TOP42 Z1_Water_Target_Temp: 30
Tue Oct 15 09:50:49 2024 (15894): received TOP43 Z2_Water_Target_Temp: 38
Tue Oct 15 09:50:49 2024 (15901): received TOP44 Error: No error
Tue Oct 15 09:50:49 2024 (15947): received TOP45 Room_Holiday_Shift_Temp: -15
Tue Oct 15 09:50:49 2024 (15948): received TOP46 Buffer_Temp: -78
Tue Oct 15 09:50:49 2024 (15950): received TOP47 Solar_Temp: -78
Tue Oct 15 09:50:49 2024 (15959): received TOP48 Pool_Temp: -78
Tue Oct 15 09:50:49 2024 (15961): received TOP49 Main_Hex_Outlet_Temp: 25
Tue Oct 15 09:50:49 2024 (15967): received TOP50 Discharge_Temp: 33
Tue Oct 15 09:50:49 2024 (15974): received TOP51 Inside_Pipe_Temp: 18
Tue Oct 15 09:50:49 2024 (15982): received TOP52 Defrost_Temp: -31
Tue Oct 15 09:50:49 2024 (16011): received TOP53 Eva_Outlet_Temp: 17
Tue Oct 15 09:50:49 2024 (16012): received TOP54 Bypass_Outlet_Temp: -31
Tue Oct 15 09:50:49 2024 (16041): received TOP55 Ipm_Temp: 19
Tue Oct 15 09:50:49 2024 (16043): received TOP56 Z1_Temp: 26
Tue Oct 15 09:50:49 2024 (16044): received TOP57 Z2_Temp: -128
Tue Oct 15 09:50:49 2024 (16048): received TOP58 DHW_Heater_State: 0
Tue Oct 15 09:50:49 2024 (16054): received TOP59 Room_Heater_State: 0
Tue Oct 15 09:50:49 2024 (16061): received TOP60 Internal_Heater_State: 0
Tue Oct 15 09:50:49 2024 (16067): received TOP61 External_Heater_State: 0
Tue Oct 15 09:50:49 2024 (16073): received TOP62 Fan1_Motor_Speed: 0
Tue Oct 15 09:50:49 2024 (16080): received TOP63 Fan2_Motor_Speed: 0
Tue Oct 15 09:50:49 2024 (16085): received TOP64 High_Pressure: 11.2
Tue Oct 15 09:50:49 2024 (16092): received TOP65 Pump_Speed: 0
Tue Oct 15 09:50:49 2024 (16098): received TOP66 Low_Pressure: 0
Tue Oct 15 09:50:49 2024 (16156): received TOP67 Compressor_Current: 0.0
Tue Oct 15 09:50:49 2024 (16157): received TOP68 Force_Heater_State: 0
Tue Oct 15 09:50:49 2024 (16158): received TOP69 Sterilization_State: 0
Tue Oct 15 09:50:49 2024 (16165): received TOP70 Sterilization_Temp: 65
Tue Oct 15 09:50:49 2024 (16172): received TOP71 Sterilization_Max_Time: 10
Tue Oct 15 09:50:49 2024 (16178): received TOP72 Z1_Cool_Curve_Target_High_Temp: 15
Tue Oct 15 09:50:49 2024 (16185): received TOP73 Z1_Cool_Curve_Target_Low_Temp: 10
Tue Oct 15 09:50:49 2024 (16193): received TOP74 Z1_Cool_Curve_Outside_High_Temp: 30
Tue Oct 15 09:50:49 2024 (16200): received TOP75 Z1_Cool_Curve_Outside_Low_Temp: 20
Tue Oct 15 09:50:49 2024 (16207): received TOP76 Heating_Mode: 0
Tue Oct 15 09:50:49 2024 (16214): received TOP77 Heating_Off_Outdoor_Temp: 5
Tue Oct 15 09:50:49 2024 (16255): received TOP78 Heater_On_Outdoor_Temp: -15
Tue Oct 15 09:50:49 2024 (16257): received TOP79 Heat_To_Cool_Temp: 15
Tue Oct 15 09:50:49 2024 (16259): received TOP80 Cool_To_Heat_Temp: 10
Tue Oct 15 09:50:49 2024 (16265): received TOP81 Cooling_Mode: 0
Tue Oct 15 09:50:49 2024 (16272): received TOP82 Z2_Heat_Curve_Target_High_Temp: 55
Tue Oct 15 09:50:49 2024 (16278): received TOP83 Z2_Heat_Curve_Target_Low_Temp: 35
Tue Oct 15 09:50:49 2024 (16285): received TOP84 Z2_Heat_Curve_Outside_High_Temp: 15
Tue Oct 15 09:50:49 2024 (16294): received TOP85 Z2_Heat_Curve_Outside_Low_Temp: -5
Tue Oct 15 09:50:49 2024 (16300): received TOP86 Z2_Cool_Curve_Target_High_Temp: 15
Tue Oct 15 09:50:49 2024 (16308): received TOP87 Z2_Cool_Curve_Target_Low_Temp: 10
Tue Oct 15 09:50:50 2024 (16655): received TOP88 Z2_Cool_Curve_Outside_High_Temp: 30
Tue Oct 15 09:50:50 2024 (16657): received TOP89 Z2_Cool_Curve_Outside_Low_Temp: 20
Tue Oct 15 09:50:50 2024 (16660): received TOP90 Room_Heater_Operations_Hours: 0
Tue Oct 15 09:50:50 2024 (16668): received TOP91 DHW_Heater_Operations_Hours: 0
Tue Oct 15 09:50:50 2024 (16675): received TOP92 Heat_Pump_Model: 27
Tue Oct 15 09:50:50 2024 (16681): received TOP93 Pump_Duty: 0
Tue Oct 15 09:50:50 2024 (16686): received TOP94 Zones_State: 0
Tue Oct 15 09:50:50 2024 (16795): received TOP95 Max_Pump_Duty: 154
Tue Oct 15 09:50:50 2024 (16796): received TOP96 Heater_Delay_Time: 30
Tue Oct 15 09:50:50 2024 (16798): received TOP97 Heater_Start_Delta: -4
Tue Oct 15 09:50:50 2024 (16805): received TOP98 Heater_Stop_Delta: -2
Tue Oct 15 09:50:50 2024 (16816): received TOP99 Buffer_Installed: 0
Tue Oct 15 09:50:50 2024 (16818): received TOP100 DHW_Installed: 0
Tue Oct 15 09:50:50 2024 (16822): received TOP101 Solar_Mode: 0
Tue Oct 15 09:50:50 2024 (16828): received TOP102 Solar_On_Delta: 10
Tue Oct 15 09:50:50 2024 (16835): received TOP103 Solar_Off_Delta: 5
Tue Oct 15 09:50:50 2024 (16841): received TOP104 Solar_Frost_Protection: 5
Tue Oct 15 09:50:50 2024 (16847): received TOP105 Solar_High_Limit: 80
Tue Oct 15 09:50:50 2024 (16854): received TOP106 Pump_Flowrate_Mode: 0
Tue Oct 15 09:50:50 2024 (16859): received TOP107 Liquid_Type: 0
Tue Oct 15 09:50:50 2024 (16866): received TOP108 Alt_External_Sensor: 1
Tue Oct 15 09:50:50 2024 (16872): received TOP109 Anti_Freeze_Mode: 1
Tue Oct 15 09:50:50 2024 (16878): received TOP110 Optional_PCB: 1
Tue Oct 15 09:50:50 2024 (16884): received TOP111 Z1_Sensor_Settings: 0
Tue Oct 15 09:50:50 2024 (16891): received TOP112 Z2_Sensor_Settings: 0
Tue Oct 15 09:50:50 2024 (16896): received TOP113 Buffer_Tank_Delta: 5
Tue Oct 15 09:50:50 2024 (16903): received TOP114 External_Pad_Heater: 1
Tue Oct 15 09:50:50 2024 (16909): received TOP115 Water_Pressure: -0.02
Tue Oct 15 09:50:50 2024 (16916): received TOP116 Second_Inlet_Temp: -128
Tue Oct 15 09:50:50 2024 (16922): received TOP117 Economizer_Outlet_Temp: -128
Tue Oct 15 09:50:50 2024 (16929): received TOP118 Second_Room_Thermostat_Temp: -128
Tue Oct 15 09:50:50 2024 (17095): sending raw value
Tue Oct 15 09:50:50 2024 (17097): sent bytes: 1 including checksum value: 0 
Tue Oct 15 09:50:50 2024 (17166): sending raw value
Tue Oct 15 09:50:50 2024 (17169): Already sending data. Buffering this send request
Tue Oct 15 09:50:52 2024 (19099): Previous read data attempt failed due to timeout!
Tue Oct 15 09:50:52 2024 (19101): Received 0 bytes data
Tue Oct 15 09:50:52 2024 (19102): Sending command from buffer
Tue Oct 15 09:50:52 2024 (19106): sent bytes: 1 including checksum value: 0 
Tue Oct 15 09:50:53 2024 (20008): Heishamon stats: Uptime: 0 days 0 hours 0 minutes 20 seconds ## Free memory: 75% ## Heap fragmentation: 13% ## Max free block: 25336 bytes ## Free heap: 29104 bytes ## Wifi: 48% (RSSI: -76) ## Mqtt reconnects: 1 ## Correct data: 75.00% Rules active: 0
Tue Oct 15 09:50:53 2024 (20026): Requesting new panasonic data
Tue Oct 15 09:50:53 2024 (20028): Already sending data. Buffering this send request
Tue Oct 15 09:50:54 2024 (21115): Previous read data attempt failed due to timeout!
Tue Oct 15 09:50:54 2024 (21117): Received 0 bytes data
Tue Oct 15 09:50:54 2024 (21118): Sending command from buffer
Tue Oct 15 09:50:54 2024 (21122): sent bytes: 111 including checksum value: 18 
Tue Oct 15 09:50:55 2024 (21565): Received 203 bytes data
Tue Oct 15 09:50:55 2024 (21567): Checksum and header received ok!
Tue Oct 15 09:50:55 2024 (21570): received TOP50 Discharge_Temp: 32
Tue Oct 15 09:50:55 2024 (21572): received TOP53 Eva_Outlet_Temp: 18
Tue Oct 15 09:50:58 2024 (25009): Heishamon stats: Uptime: 0 days 0 hours 0 minutes 25 seconds ## Free memory: 75% ## Heap fragmentation: 13% ## Max free block: 25336 bytes ## Free heap: 29080 bytes ## Wifi: 48% (RSSI: -76) ## Mqtt reconnects: 1 ## Correct data: 66.67% Rules active: 0
Tue Oct 15 09:50:58 2024 (25027): Requesting new panasonic data
Tue Oct 15 09:50:58 2024 (25029): sent bytes: 111 including checksum value: 18 
Tue Oct 15 09:50:58 2024 (25465): Received 203 bytes data
Tue Oct 15 09:50:58 2024 (25468): Checksum and header received ok!
Tue Oct 15 09:50:58 2024 (25470): received TOP6 Main_Outlet_Temp: 25.75
Tue Oct 15 09:50:58 2024 (25474): received TOP53 Eva_Outlet_Temp: 17
Tue Oct 15 09:50:58 2024 (25479): received TOP56 Z1_Temp: 25
Tue Oct 15 09:51:00 2024 (27231): set heating off outdoor temp 16
Tue Oct 15 09:51:00 2024 (27233): sent bytes: 111 including checksum value: 2 
Tue Oct 15 09:51:01 2024 (27708): Received 203 bytes data
Tue Oct 15 09:51:01 2024 (27709): Checksum and header received ok!
Tue Oct 15 09:51:01 2024 (27711): received TOP6 Main_Outlet_Temp: 26
Tue Oct 15 09:51:01 2024 (27716): received TOP56 Z1_Temp: 26
Tue Oct 15 09:51:03 2024 (30010): Heishamon stats: Uptime: 0 days 0 hours 0 minutes 30 seconds ## Free memory: 75% ## Heap fragmentation: 12% ## Max free block: 25336 bytes ## Free heap: 28888 bytes ## Wifi: 46% (RSSI: -77) ## Mqtt reconnects: 1 ## Correct data: 75.00% Rules active: 0
Tue Oct 15 09:51:03 2024 (30028): Requesting new panasonic data
Tue Oct 15 09:51:03 2024 (30031): sent bytes: 111 including checksum value: 18 
Tue Oct 15 09:51:03 2024 (30439): Received 203 bytes data
Tue Oct 15 09:51:03 2024 (30441): Checksum and header received ok!
Tue Oct 15 09:51:03 2024 (30443): received TOP1 Pump_Flow: 25.55
Tue Oct 15 09:51:03 2024 (30446): received TOP6 Main_Outlet_Temp: 25.75
Tue Oct 15 09:51:03 2024 (30453): received TOP56 Z1_Temp: 25
Tue Oct 15 09:51:03 2024 (30458): received TOP65 Pump_Speed: 3300
Tue Oct 15 09:51:03 2024 (30465): received TOP77 Heating_Off_Outdoor_Temp: 16
Tue Oct 15 09:51:03 2024 (30471): received TOP93 Pump_Duty: 133
Tue Oct 15 09:51:08 2024 (35011): Heishamon stats: Uptime: 0 days 0 hours 0 minutes 35 seconds ## Free memory: 75% ## Heap fragmentation: 12% ## Max free block: 25336 bytes ## Free heap: 28888 bytes ## Wifi: 48% (RSSI: -76) ## Mqtt reconnects: 1 ## Correct data: 77.78% Rules active: 0
Tue Oct 15 09:51:08 2024 (35029): Requesting new panasonic data
Tue Oct 15 09:51:08 2024 (35031): sent bytes: 111 including checksum value: 18 
Tue Oct 15 09:51:09 2024 (35510): Received 203 bytes data
Tue Oct 15 09:51:09 2024 (35512): Checksum and header received ok!
Tue Oct 15 09:51:09 2024 (35514): received TOP1 Pump_Flow: 16.96
Tue Oct 15 09:51:09 2024 (35518): received TOP65 Pump_Speed: 2300
Tue Oct 15 09:51:09 2024 (35524): received TOP93 Pump_Duty: 103
Tue Oct 15 09:51:12 2024 (38623): set heating off outdoor temp 15
Tue Oct 15 09:51:12 2024 (38625): sent bytes: 111 including checksum value: 3 
Tue Oct 15 09:51:12 2024 (39020): Received 203 bytes data
Tue Oct 15 09:51:12 2024 (39023): Checksum and header received ok!
Tue Oct 15 09:51:12 2024 (39025): received TOP51 Inside_Pipe_Temp: 17
Tue Oct 15 09:51:12 2024 (39029): received TOP93 Pump_Duty: 113
Tue Oct 15 09:51:13 2024 (40012): Heishamon stats: Uptime: 0 days 0 hours 0 minutes 40 seconds ## Free memory: 74% ## Heap fragmentation: 12% ## Max free block: 25336 bytes ## Free heap: 28672 bytes ## Wifi: 44% (RSSI: -78) ## Mqtt reconnects: 1 ## Correct data: 81.82% Rules active: 0
Tue Oct 15 09:51:13 2024 (40030): Requesting new panasonic data
Tue Oct 15 09:51:13 2024 (40032): sent bytes: 111 including checksum value: 18 
Tue Oct 15 09:51:13 2024 (40483): Received 203 bytes data
Tue Oct 15 09:51:13 2024 (40485): Checksum and header received ok!
Tue Oct 15 09:51:13 2024 (40487): received TOP1 Pump_Flow: 20.18
Tue Oct 15 09:51:13 2024 (40492): received TOP65 Pump_Speed: 2650
Tue Oct 15 09:51:18 2024 (45013): Heishamon stats: Uptime: 0 days 0 hours 0 minutes 45 seconds ## Free memory: 74% ## Heap fragmentation: 11% ## Max free block: 25336 bytes ## Free heap: 28528 bytes ## Wifi: 48% (RSSI: -76) ## Mqtt reconnects: 1 ## Correct data: 83.33% Rules active: 0
Tue Oct 15 09:51:18 2024 (45031): Requesting new panasonic data
Tue Oct 15 09:51:18 2024 (45033): sent bytes: 111 including checksum value: 18 
Tue Oct 15 09:51:18 2024 (45456): Received 203 bytes data
Tue Oct 15 09:51:18 2024 (45459): Checksum and header received ok!
Tue Oct 15 09:51:18 2024 (45461): received TOP1 Pump_Flow: 19.82
Tue Oct 15 09:51:18 2024 (45465): received TOP65 Pump_Speed: 2700
Tue Oct 15 09:51:18 2024 (45470): received TOP77 Heating_Off_Outdoor_Temp: 15
Tue Oct 15 09:51:23 2024 (50014): Heishamon stats: Uptime: 0 days 0 hours 0 minutes 50 seconds ## Free memory: 75% ## Heap fragmentation: 12% ## Max free block: 25336 bytes ## Free heap: 28736 bytes ## Wifi: 48% (RSSI: -76) ## Mqtt reconnects: 1 ## Correct data: 84.62% Rules active: 0
Tue Oct 15 09:51:23 2024 (50032): Requesting new panasonic data
Tue Oct 15 09:51:23 2024 (50034): sent bytes: 111 including checksum value: 18 
Tue Oct 15 09:51:23 2024 (50430): Received 203 bytes data
Tue Oct 15 09:51:23 2024 (50432): Checksum and header received ok!
Tue Oct 15 09:51:23 2024 (50434): received TOP5 Main_Inlet_Temp: 25.50

**Comment by geduxas** [comment]
I don't see any commands between 16 and 15 values, wait around 5s between commands, also turn on debug log

**Comment by agenstarburst** [comment]
I don't see the command either. Suppose that is the reason why it's not working. Question is, why is the command not published via heishamon? This time I waited at least 5 seconds after sending http://192.168.xxx.xx/command?SetHeatingOffOutdoorTemp=6 and sending http://192.168.xxx.xx/command?setHeatpump=0 (I tried multiple times). End of process is shown by http://192.168.xxx.xx/command?SetHeatingOffOutdoorTemp=5.

"Debug log to MQTT topic from start" was activated in settings. 

Tue Oct 15 17:30:59 2024 (27625355): Heishamon stats: Uptime: 0 days 7 hours 40 minutes 25 seconds ## Free memory: 73% ## Heap fragmentation: 10% ## Max free block: 25336 bytes ## Free heap: 28112 bytes ## Wifi: 48% (RSSI: -76) ## Mqtt reconnects: 6 ## Correct data: 99.64% Rules active: 0
Tue Oct 15 17:30:59 2024 (27625374): Requesting new panasonic data
Tue Oct 15 17:30:59 2024 (27625376): sent bytes: 111 including checksum value: 18 
Tue Oct 15 17:30:59 2024 (27625806): Received 203 bytes data
Tue Oct 15 17:30:59 2024 (27625808): Checksum and header received ok!
Tue Oct 15 17:30:59 2024 (27625811): received TOP49 Main_Hex_Outlet_Temp: 28
Tue Oct 15 17:31:04 2024 (27630356): Heishamon stats: Uptime: 0 days 7 hours 40 minutes 30 seconds ## Free memory: 70% ## Heap fragmentation: 7% ## Max free block: 25336 bytes ## Free heap: 27088 bytes ## Wifi: 50% (RSSI: -75) ## Mqtt reconnects: 6 ## Correct data: 99.64% Rules active: 0
Tue Oct 15 17:31:07 2024 (27633325): Requesting new panasonic data
Tue Oct 15 17:31:07 2024 (27633325): sent bytes: 111 including checksum value: 18 
Tue Oct 15 17:31:07 2024 (27633339): set heating off outdoor temp 6
Tue Oct 15 17:31:07 2024 (27633341): Already sending data. Buffering this send request
Tue Oct 15 17:31:07 2024 (27633802): Received 203 bytes data
Tue Oct 15 17:31:07 2024 (27633803): Checksum and header received ok!
Tue Oct 15 17:31:07 2024 (27633805): received TOP49 Main_Hex_Outlet_Temp: 27
Tue Oct 15 17:31:07 2024 (27633813): Sending command from buffer
Tue Oct 15 17:31:07 2024 (27633816): sent bytes: 111 including checksum value: 12 
Tue Oct 15 17:31:08 2024 (27634290): Received 203 bytes data
Tue Oct 15 17:31:08 2024 (27634291): Checksum and header received ok!
Tue Oct 15 17:31:09 2024 (27635356): Lost MQTT connection!
Tue Oct 15 17:31:09 2024 (27635357): Reconnecting to mqtt server ...
Tue Oct 15 17:31:09 2024 (27635371): Heishamon stats: Uptime: 0 days 7 hours 40 minutes 35 seconds ## Free memory: 62% ## Heap fragmentation: 8% ## Max free block: 22096 bytes ## Free heap: 23888 bytes ## Wifi: 52% (RSSI: -74) ## Mqtt reconnects: 7 ## Correct data: 99.64% Rules active: 0
Tue Oct 15 17:31:09 2024 (27635390): Requesting new panasonic data
Tue Oct 15 17:31:09 2024 (27635393): sent bytes: 111 including checksum value: 18 
Tue Oct 15 17:31:09 2024 (27635850): Received 203 bytes data
Tue Oct 15 17:31:09 2024 (27635852): Checksum and header received ok!
Tue Oct 15 17:31:09 2024 (27635856): received TOP77 Heating_Off_Outdoor_Temp: 6
Tue Oct 15 17:31:09 2024 (27635925): sending raw value
Tue Oct 15 17:31:09 2024 (27635927): sent bytes: 1 including checksum value: 0 
Tue Oct 15 17:31:11 2024 (27637694): sending raw value
Tue Oct 15 17:31:11 2024 (27637696): Already sending data. Buffering this send request
Tue Oct 15 17:31:11 2024 (27637930): Previous read data attempt failed due to timeout!
Tue Oct 15 17:31:11 2024 (27637932): Received 0 bytes data
Tue Oct 15 17:31:11 2024 (27637933): Sending command from buffer
Tue Oct 15 17:31:11 2024 (27637938): sent bytes: 1 including checksum value: 0 
Tue Oct 15 17:31:13 2024 (27639947): Previous read data attempt failed due to timeout!
Tue Oct 15 17:31:13 2024 (27639949): Received 0 bytes data
Tue Oct 15 17:31:14 2024 (27640358): Heishamon stats: Uptime: 0 days 7 hours 40 minutes 40 seconds ## Free memory: 73% ## Heap fragmentation: 10% ## Max free block: 25336 bytes ## Free heap: 28168 bytes ## Wifi: 52% (RSSI: -74) ## Mqtt reconnects: 7 ## Correct data: 99.60% Rules active: 0
Tue Oct 15 17:31:14 2024 (27640376): Requesting new panasonic data
Tue Oct 15 17:31:14 2024 (27640379): sent bytes: 111 including checksum value: 18 
Tue Oct 15 17:31:14 2024 (27640824): Received 203 bytes data
Tue Oct 15 17:31:14 2024 (27640826): Checksum and header received ok!
Tue Oct 15 17:31:14 2024 (27640829): received TOP49 Main_Hex_Outlet_Temp: 28
Tue Oct 15 17:31:19 2024 (27645359): Heishamon stats: Uptime: 0 days 7 hours 40 minutes 45 seconds ## Free memory: 73% ## Heap fragmentation: 10% ## Max free block: 25336 bytes ## Free heap: 28120 bytes ## Wifi: 50% (RSSI: -75) ## Mqtt reconnects: 7 ## Correct data: 99.60% Rules active: 0
Tue Oct 15 17:31:19 2024 (27645377): Requesting new panasonic data
Tue Oct 15 17:31:19 2024 (27645380): sent bytes: 111 including checksum value: 18 
Tue Oct 15 17:31:19 2024 (27645797): Received 203 bytes data
Tue Oct 15 17:31:19 2024 (27645799): Checksum and header received ok!
Tue Oct 15 17:31:24 2024 (27650360): Heishamon stats: Uptime: 0 days 7 hours 40 minutes 50 seconds ## Free memory: 73% ## Heap fragmentation: 10% ## Max free block: 25336 bytes ## Free heap: 28088 bytes ## Wifi: 40% (RSSI: -80) ## Mqtt reconnects: 7 ## Correct data: 99.60% Rules active: 0
Tue Oct 15 17:31:24 2024 (27650379): Requesting new panasonic data
Tue Oct 15 17:31:24 2024 (27650381): sent bytes: 111 including checksum value: 18 
Tue Oct 15 17:31:24 2024 (27650771): Received 203 bytes data
Tue Oct 15 17:31:24 2024 (27650773): Checksum and header received ok!
Tue Oct 15 17:31:24 2024 (27650776): received TOP49 Main_Hex_Outlet_Temp: 27
Tue Oct 15 17:31:24 2024 (27650779): received TOP50 Discharge_Temp: 25
Tue Oct 15 17:31:24 2024 (27650786): received TOP51 Inside_Pipe_Temp: 22
Tue Oct 15 17:31:25 2024 (27651238): set heating off outdoor temp 5
Tue Oct 15 17:31:25 2024 (27651241): sent bytes: 111 including checksum value: 13 
Tue Oct 15 17:31:25 2024 (27651648): Received 203 bytes data
Tue Oct 15 17:31:25 2024 (27651651): Checksum and header received ok!
Tue Oct 15 17:31:25 2024 (27651653): received TOP50 Discharge_Temp: 26
Tue Oct 15 17:31:29 2024 (27655361): Heishamon stats: Uptime: 0 days 7 hours 40 minutes 55 seconds ## Free memory: 73% ## Heap fragmentation: 10% ## Max free block: 25336 bytes ## Free heap: 28104 bytes ## Wifi: 44% (RSSI: -78) ## Mqtt reconnects: 7 ## Correct data: 99.60% Rules active: 0
Tue Oct 15 17:31:29 2024 (27655380): Requesting new panasonic data
Tue Oct 15 17:31:29 2024 (27655382): sent bytes: 111 including checksum value: 18 
Tue Oct 15 17:31:29 2024 (27655842): Received 203 bytes data
Tue Oct 15 17:31:29 2024 (27655844): Checksum and header received ok!
Tue Oct 15 17:31:29 2024 (27655846): received TOP6 Main_Outlet_Temp: 28
Tue Oct 15 17:31:29 2024 (27655850): received TOP56 Z1_Temp: 28
Tue Oct 15 17:31:29 2024 (27655857): received TOP77 Heating_Off_Outdoor_Temp: 5
Tue Oct 15 17:31:34 2024 (27660362): Heishamon stats: Uptime: 0 days 7 hours 41 minutes 0 seconds ## Free memory: 73% ## Heap fragmentation: 11% ## Max free block: 25336 bytes ## Free heap: 28216 bytes ## Wifi: 42% (RSSI: -79) ## Mqtt reconnects: 7 ## Correct data: 99.60% Rules active: 0
Tue Oct 15 17:31:34 2024 (27660380): Requesting new panasonic data
Tue Oct 15 17:31:34 2024 (27660383): sent bytes: 111 including checksum value: 18 
Tue Oct 15 17:31:34 2024 (27660815): Received 203 bytes data
Tue Oct 15 17:31:34 2024 (27660817): Checksum and header received ok!
Tue Oct 15 17:31:34 2024 (27660819): received TOP6 Main_Outlet_Temp: 27.50
Tue Oct 15 17:31:34 2024 (27660829): received TOP56 Z1_Temp: 27

**Comment by agenstarburst** [comment]
I haven't tried all other MQTT command topics, but 5-6 that I have tried did work as expected. Only the setheatpump command does not work. 

Want to use it for deactivating the heat pump when I receive high pricing from Tibber.

**Comment by geduxas** [comment]
Oh, i missed fact that you trying **set** command instead of **Set**! Commands are case sensitive. So that's why not working for you

**Comment by agenstarburst** [comment]
Unbelievable. I must have typed it incorrectly the first time I tried and from then on the browser always took the wrong command from history. Thank you so much!!! 

The only thing that is strange, if I request SetHeatpump=1, the command responds "set heatpump state to 2", while it responds "set heatpump state to 1" if i request SetHeatpump=0. The behavior of the heatpump switches to off and on as expected so it is thus correct.

**Comment by geduxas** [comment]
Yes, because in heatpump telemetry data all values are +1 

So if issue is resolved, please don't forget to close
