### ISSUE TITLE
High energy consumption by the pump in the off state.

### ISSUE THREAD

**Issue by krzbor** [heishamon/HeishaMon#559]
I have a "K" series heat pump. When reading the "_Power_Consumption" and "_Power_Production" parameters, I was getting incorrect values of -200. However, I found in the source code (unfortunately, this is not documented in the MQTT guide) the parameters "_Power_Consumption_Extra" and "_Power_Production_Extra," which return reasonable values.

I have a question, though—when the pump is turned off, it consumes about 40W according to this data, and when it’s on but not operating, it consumes about 70W. This higher value is probably due to the operation of the water circulation pump. However, I am surprised by such a high consumption in the off state. 40W amounts to 1kWh per day!

I compared the power consumption for October. In HA, it was significantly higher than on the heat pump. However, when I subtracted 1kWh for each day, the results matched.

Is the reported 40W consumption reasonable and realistic? Are the "*_Extra" parameters reported by the pump, or are they calculated in HeishaMon?

**Comment by geduxas** [comment]
How you metered it? Is it just showed in pump?

**Comment by geduxas** [comment]
I can confirm, my pump (H series) while idle consumes around same amount 
![Screenshot_2024-10-19-21-42-25-87_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/874aea45-91ee-4278-8595-6cb2df9a8396)

**Comment by geduxas** [comment]
And i was totally wrong, o forgot that i in 2 zone setup (which i have) zone pumps are always running and drived from pump.. here is updated graph after switch pump's off

![Screenshot_2024-10-19-21-52-23-41_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/80ec6ba9-11ad-4a57-be78-832e17adb86d)

**Comment by krzbor** [comment]
My pump (K series) – off state: 41W. The value comes from "Aquarea Heat Power Consumed"; topic: "panasonic_heat_pump/extra/Heat_Power_Consumption_Extra". I find it hard to believe that the new series consumes 4 times more power than the old series.

**Comment by geduxas** [comment]
> My pump (K series) – off state: 41W. The value comes from "Aquarea Heat Power Consumed"; topic: "panasonic_heat_pump/extra/Heat_Power_Consumption_Extra". I find it hard to believe that the new series consumes 4 times more power than the old series.

Yes _extra topic is for new pumps K/L series, heishamon don't do any calculations, everything is fetched from pump. Also please pay attention that pump don't have any energy metering devices. All is done by calculating by pump itself.. so don't blindly trust. Second if consumption is real.. it could be from heating elements.. it could be compressor heater, it could be drain pipe heater.. and so on..

**Comment by krzbor** [comment]
Maybe someone has measured the actual power consumption in the off state? If the pump doesn't have a power consumption meter, it must be calculating it somehow. It's interesting that the value shown on the pump's own graph is different from what is reported through MQTT.

**Comment by stumbaumr** [comment]
I have two S0 energy meters in my power distribution cabinet that feed into the HeishaMons S0 counters - one for the heatpump and one for the heating element of the heatpump.
My 5 kW J Aquarea takes 8W in idle mode. The 200W stepping factor of the calculated power consumption is the main reason for wrong COP calculation results.
![grafik](https://github.com/user-attachments/assets/72bf6128-0a28-4e01-8cad-75e9c9c61aa6)

**Comment by geduxas** [comment]
So ok, J an H series consumes almost same amount.. i doubth that K/L series will consume more.. it's almost same pcb. So in your @krzbor case it's something else.. it's not just pcb in idle mode or meter is incorrect

**Comment by krzbor** [comment]
I believe it's the meter in the pump that's at fault. I don't think the power consumption would increase, especially by such a significant amount, in the new generation of pumps. Every manufacturer aims to reduce idle power consumption. If anyone has measurements of energy usage when the pump is off for the "K" series, please share this information.

**Comment by Egyras** [comment]
first of all circulation pump consumes ~ 40W and antifrost protection for outside unit also uses +40W on top depending on outside temperature ;) Keep in mind that antifrost for outside unit kicks in not constantly. In total idle state it will consume 8-10W. These values are from external power meter.

**Comment by geduxas** [comment]
@Egyras for outside unit, do you talk about basepan heater or compressor crankcase?

**Comment by Egyras** [comment]
> @Egyras for outside unit, do you talk about basepan heater or compressor crankcase?

original basepan heater user much more then +40W and it has 2 option for usage :)  Its just antifreeze control when circulation pump works a little bit harder, logic defined in service manual.

**Comment by krzbor** [comment]
It shows 41W in the off state (the circulation pump is not working). The outside temperature is above zero.
When the circulation pump is running but there is no heating, the displayed power is 58-71W.

**Comment by MiG-41** [comment]
Above 0 , but how much ? As i recall compressor heater is turning on at +3 deg....

**Comment by krzbor** [comment]
The power consumption is constant and remains at 41W even with an outside temperature of 8°C

**Comment by MiG-41** [comment]
Then it is too much... 
Maybe in K counter is more precise  ( in Hor J it has resolution 0,2kW ) , but looks like still not perfect . ( Or somthing else is stealing energy). Witchout  external Wattmeter you will not be able to compare...

**Comment by geduxas** [comment]
> Above 0 , but how much ? As i recall compressor heater is turning on at +3 deg....

Do crankshaft heater works all the time, or just preheats compressor before starting it? Never noticed that..

**Comment by MiG-41** [comment]
All the time ( at least when compressor is not working).
