### ISSUE TITLE
Auto-discovery doesn't work with HeishaMon module

### ISSUE THREAD

**Issue by Maystero14** [heishamon/HeishaMon#564]
I have been trying to integrate HeishaMon with Home Assistant for some time to manage my Panasonic heat pump. I have searched for help on discussion forums. To no avail. I currently have an ESP8266 module running with HeishaMon firmware 3.8. MQTT server configured and running. Ping communication between devices works. And Home Assistant does not detect entities from the HeishaMon device I also installed packages from HACS Heishamon, but that didn't help either. MQTT Explorer sees mqtt packets, so the system seems to be working correctly.

![462146079_1004041798142923_471863067258804714_n](https://github.com/user-attachments/assets/d910b91d-61f8-4d1c-b0db-9ad79e03c601)
![Zrzut ekranu 2024-10-24 194923](https://github.com/user-attachments/assets/f96597a8-9aca-4b7e-9e75-a93b67b3d91d)

Thanks in advance for every help.

**Comment by geduxas** [comment]
There is no autodiscovery compatible with HA in heishamon, earlier we used manual configuration, now it's outdated a lot.. i suggest you to use Heishamon integration from HACS. 

Sorry, didn't noticed that you are trying with integration, I don't see topics in your mqtt, do you get any values in heishamon web page?

**Comment by Maystero14** [comment]
> Sorry, didn't noticed that you are trying with integration, I don't see topics in your mqtt, do you get any values in heishamon web page?


You means from ESP8266?

**Comment by Maystero14** [comment]
Fixed
