### ISSUE TITLE
Set time in Aquarea Controller from HeishaMon

### ISSUE THREAD

**Issue by stumbaumr** [heishamon/HeishaMon#570]
Last weekend the time changed to winter time - my time based rules worked perfectly, but the Panasonic controller still shows the summer time.
Is there any possibility to get the time of the controller changed from HeishaMon? For example set the time of the controller when the NTP sync is done.

**Comment by geduxas** [comment]
No, there is no access to RC from pump side,  think about RC as external controller.. or another type of heishamon.. it's working on his own logic and getting same data from pump as Heishamon

**Comment by stumbaumr** [comment]
Thanks for your fast reply!
