### ISSUE TITLE
How to add relays in v0.5?

### ISSUE THREAD

**Issue by kamil2466** [heishamon/HeishaMon#579]
Do you guys know how to add relays so they can be controlled in Home Assistant? I need to add 1 relay to control the circulating pump. I've looked on the forums but don't see anywhere how to add it.

**Comment by MiG-41** [comment]
Quote from ReadMe:

`To control the relay just send a value of 1 or 0 to the MQTT topic "panasonic_heat_pump/gpio/relay/one" for relay one or "panasonic_heat_pump/gpio/relay/two" for relay two.`

You have to made siutable to this entities.

**Comment by kamil2466** [comment]
Can you send an example of how to do this for Home Assistant, I see 2 not available entities for relays in HA

**Comment by McMagellan** [comment]
And how can you control the relays from Rules and also query the status?

Is it possible to control the relays like a Shelly relay with: 
`http://192.168.xxx.xxx/relay/0?turn=on `

as a simple local URL command like: 
`http://192.168.178.36/command? SetZ1HeatRequestTemperature=1`

**Comment by kamil2466** [comment]
Ideally, it would be added to the software the ability to select the option to enable relays as it looks with the DS18b20 option
